import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { COMPLETE_CORE_CHARACTER_NODES, COMPLETE_CORE_READING_SENSES } from "../../games/hanzi-radical-battle/complete/content-graph/core-characters";
import { decomposeMarkedSyllable, markedToNumbered } from "../../games/hanzi-radical-battle/complete/support/pinyin/orthography";
import type { PinyinBand, PinyinReadingRecord } from "../../games/hanzi-radical-battle/complete/support/pinyin/types";

const output = resolve("games/hanzi-radical-battle/complete/support/pinyin/manifest.ts");
const check = process.argv.includes("--check");
const readings = new Map(COMPLETE_CORE_READING_SENSES.map((reading) => [reading.characterId, reading]));

function revisionHash(payload: unknown): string {
  return createHash("sha256").update(JSON.stringify(payload)).digest("hex");
}

const records: PinyinReadingRecord[] = COMPLETE_CORE_CHARACTER_NODES.map((character) => {
  const reading = readings.get(character.id);
  if (!reading) throw new Error(`Missing core ReadingSense for ${character.glyph}`);
  const parsed = decomposeMarkedSyllable(reading.pinyin);
  const band: PinyinBand = character.familiarity === "advanced-optional" || reading.pronunciationRisk === "fixed-context-polyphone"
    ? "optional-advanced"
    : character.familiarity === "high" ? "starter" : "story";
  const riskFlags = [
    ...(reading.pronunciationRisk === "fixed-context-polyphone" ? ["FIXED_CONTEXT_POLYPHONE"] : []),
    ...(parsed.tone === 5 ? ["NEUTRAL_TONE"] : []),
    ...(parsed.yWOrthography ? ["Y_W_ORTHOGRAPHY"] : []),
    ...(parsed.umlautOmissionRule !== "none" ? ["UMLAUT_OMISSION"] : []),
    ...(parsed.contractionRule !== "none" ? ["CONTRACTED_FINAL"] : []),
    ...(parsed.wholeSyllableTeaching ? ["WHOLE_SYLLABLE_TEACHING"] : []),
  ];
  const payload = {
    id: `pinyin.${reading.id}`,
    characterId: character.id,
    readingSenseId: reading.id,
    glyph: character.glyph,
    fixedPhrase: reading.fixedPhrase,
    citationPinyinMarked: reading.pinyin.normalize("NFC"),
    citationPinyinNumbered: markedToNumbered(reading.pinyin),
    ...(character.glyph === "们" ? { spokenPhrasePinyin: "tā men" } : {}),
    phonologicalOnset: parsed.phonologicalOnset,
    teachingInitial: parsed.teachingInitial,
    canonicalFinal: parsed.canonicalFinal,
    writtenFinal: parsed.writtenFinal,
    medial: parsed.medial,
    tone: parsed.tone,
    toneMarkVowelIndex: parsed.toneMarkVowelIndex,
    zeroInitial: parsed.zeroInitial,
    yWOrthography: parsed.yWOrthography,
    umlautOmissionRule: parsed.umlautOmissionRule,
    contractionRule: parsed.contractionRule,
    wholeSyllableTeaching: parsed.wholeSyllableTeaching,
    neutralTone: parsed.tone === 5,
    sandhiStatus: character.glyph === "们" ? "fixed-context-explicit" as const : reading.pronunciationRisk === "fixed-context-polyphone" ? "citation-only" as const : "not-applicable" as const,
    band,
    sourceIds: [...new Set(["pinyin-scheme-1958", "gbt-16159-2012", "repo-hanzi-v3-reading-senses", ...reading.sourceIds])],
    riskFlags,
  };
  return { ...payload, revisionHash: revisionHash(payload) };
});

const contentRevision = revisionHash(records.map(({ revisionHash }) => revisionHash));
const rendered = `// Generated by tools/chinese-support/generate-pinyin-manifest.ts. Do not edit by hand.\nimport type { PinyinReadingRecord } from "./types";\n\nexport const PINYIN_READING_MANIFEST = ${JSON.stringify(records, null, 2)} as const satisfies readonly PinyinReadingRecord[];\n\nexport const PINYIN_CONTENT_REVISION = ${JSON.stringify(contentRevision)};\n`;

if (check) {
  if (!existsSync(output) || readFileSync(output, "utf8") !== rendered) {
    console.error("Pinyin manifest drift detected. Run pnpm run pinyin:generate.");
    process.exitCode = 1;
  } else console.log(`Pinyin manifest: 72/72 PASS; revision ${contentRevision}`);
} else {
  writeFileSync(output, rendered, "utf8");
  console.log(`Generated ${records.length} PinyinReadingRecord entries at ${output}`);
}
