import {describe,it,expect} from 'vitest';
import {freshDesk,arrange,advanceDesk,totalGrain,validDesk,restoreDesk,delivered,obstacle,canAdvance} from '../games/world-in-a-box/chancellor-model';
describe('chancellor physical grain flow',()=>{
 for(const route of [['cart-river','cart-mountain'],['boat-river','boat-river','cart-mountain']] as const)it(route.join(' / '),()=>{let s=freshDesk();s.repair=true;for(const j of route)s=arrange(s,j);let guard=0;while(canAdvance(s)&&guard++<40){s=advanceDesk(s);expect(totalGrain(s)).toBe(12);expect(validDesk(s)).toBe(true);expect(restoreDesk(s)).toEqual(s);}expect(delivered(s)).toBe(true);expect(s.warehouse+s.cart+s.boat).toBe(0);expect(s.active).toBeNull();});
 it('blocks bridge, allows repair without losing queued work',()=>{let s=arrange(freshDesk(),'cart-mountain');expect(obstacle(s,'cart-mountain')).toContain('桥');s=advanceDesk(s);expect(s.mountain).toBe(0);s.repair=true;for(let i=0;i<12;i++)s=advanceDesk(s);expect(s.mountain).toBe(6);expect(totalGrain(s)).toBe(12);});
 it('one transport team cannot deliver twice or overload',()=>{let s=freshDesk();s.repair=true;for(let i=0;i<3;i++)s=arrange(s,'cart-river');for(let i=0;i<30;i++)s=advanceDesk(s);expect(s.river).toBe(6);expect(s.queue).toHaveLength(2);expect(totalGrain(s)).toBe(12);expect(obstacle(s,'cart-river')).toContain('够粮');});
 it('rejects corrupted and incompatible saves',()=>{expect(restoreDesk({...freshDesk(),cart:9})).toEqual(freshDesk());expect(validDesk({...freshDesk(),active:{job:'boat-river',step:1}})).toBe(false);expect(validDesk({...freshDesk(),content:'old'})).toBe(false);});
 it('explains a partial village and recovers with a smaller batch',()=>{let s=arrange(freshDesk(),'boat-river');s.repair=true;for(let i=0;i<5;i++)s=advanceDesk(s);expect(s.river).toBe(3);expect(obstacle(s,'cart-river')).toContain('还需3袋');s=arrange(s,'boat-river');s=arrange(s,'cart-mountain');for(let i=0;i<10;i++)s=advanceDesk(s);expect(delivered(s)).toBe(true);expect(totalGrain(s)).toBe(12);});
});
