import {describe,it,expect} from 'vitest';
import {initial,apply,clone,LEVELS,eye,sight,position,route,space,validSave,freshSave,type State,type Action,type Ability} from '../games/oddity-puzzles/model';
const run=(s:State,actions:Action[],disabled:Ability[]=[])=>{for(const a of actions){const r=apply(s,a,disabled);if(r.error)throw Error(JSON.stringify(a)+': '+r.error);s=r.state;}return s;};
const l1:Action[]=[{type:'move',node:'window'},{type:'ring',target:'lamp',direction:1},{type:'move',node:'box'},{type:'take',item:'box'},{type:'move',node:'exit'}];
const l2:Action[]=[{type:'restore'},{type:'move',node:'door'},{type:'portal'},{type:'cross'}];
const l3:Action[]=[{type:'capture',target:'b'},{type:'ring',target:'photo',node:'tray'},{type:'take',item:'photo',actor:'npc'},{type:'release',node:'release',actor:'npc'},{type:'switch',actor:'b'},{type:'move',node:'left'},{type:'hold',switch:'left'},{type:'move',node:'right',actor:'npc'},{type:'hold',switch:'right',actor:'npc'},{type:'move',node:'exit'},{type:'move',node:'exit',actor:'npc'},{type:'switch',actor:'a'},{type:'move',node:'exit'}];
describe('same-layout greybox rules',()=>{
 for(const [i,actions] of [l1,l2,l3].entries())it(`room ${i+1} both abilities win and removing either rejects the path`,()=>{expect(run(initial(i+1),actions).won).toBe(true);for(const ability of LEVELS[i].abilities)expect(()=>run(initial(i+1),actions,[ability])).toThrow();});
 it('box hidden from every external node and sampled reachable corridor edge',()=>{const s=initial(1);for(const z of [1.45,2,2.7,4,4.4])for(let x=-5;x<=5;x+=.2){const copy=clone(s);LEVELS[0].nodes.push({id:'probe',label:'test',p:[x,0,z]});copy.actors[0].node='probe';expect(sight(copy,position(copy,'box'))).toContain('挡');LEVELS[0].nodes.pop();}expect(apply(s,{type:'ring',target:'box',node:'hand'}).error).toContain('挡');});
 it('window transmits sight but rejects bodies; lamp reachable only after channel',()=>{let s=run(initial(1),[{type:'move',node:'window'}]);expect(sight(s,position(s,'lamp'))).toBeNull();expect(route(s,'window','lamp')).toBeNull();expect(apply(s,{type:'lamp',direction:1}).error).toContain('够不到');s=run(s,[{type:'ring',target:'lamp',direction:1},{type:'move',node:'lamp'},{type:'lamp',direction:2},{type:'lamp',direction:1}]);expect(route(s,'lamp','exit')).not.toBeNull();});
 it('taking box alone is not success',()=>expect(run(initial(1),l1.slice(0,-1)).won).toBe(false));
 it('broken door, collapsed corridor, stable door identity, repeated restore',()=>{let s=initial(2);expect(apply(s,{type:'portal'}).error).toContain('门坏');expect(apply(s,{type:'cross'}).error).toContain('断开');s=run(s,[{type:'restore'}]);expect(route(s,'start','safe')).toBeNull();expect(s.items.filter(o=>o.id==='door')).toHaveLength(1);expect(apply(s,{type:'restore'}).error).toContain('复制');expect(s.won).toBe(false);});
 it('empty photo return without reset, repeated capture and release',()=>{let s=run(initial(3),[{type:'ring',target:'photo',node:'tray'},{type:'take',item:'photo',actor:'npc'}]);expect(apply(s,{type:'release',node:'release',actor:'npc'}).error).toContain('空');s=run(s,[{type:'drop',item:'photo',actor:'npc'},{type:'ring',target:'photo',node:'hand'},{type:'capture',target:'b'}]);expect(apply(s,{type:'capture',target:'npc'}).error).toContain('已经有');expect(apply(s,{type:'switch',actor:'b'}).error).toContain('照片里');s=run(s,[{type:'release',node:'friend'},{type:'capture',target:'b'}]);expect(s.photo).toBe('b');});
 it('cannot transport person through slot or remotely release held photo',()=>{const s=initial(3);expect(apply(s,{type:'ring',target:'b',node:'release'}).error).toMatch(/挡|投递/);const inside=run(s,l3.slice(0,3));expect(apply(inside,{type:'ring',target:'photo',node:'hand'}).error).toContain('别人手上');expect(apply(inside,{type:'release',node:'friend'}).error).toContain('拿起');});
 it('all outside eye positions blocked from switch faces; one held switch not enough',()=>{const s=initial(3);for(let x=-5;x<=5;x+=.25)for(const z of [1.5,2.5,3.5,4.4]){LEVELS[2].nodes.push({id:'probe',label:'test',p:[x,0,z]});const c=clone(s);c.actors[0].node='probe';for(const target of ['left','right'])expect(sight(c,position(c,target))).toContain('遮板');LEVELS[2].nodes.pop();}expect(run(s,l3.slice(0,7)).latched).toBe(false);expect(run(s,l3.slice(0,9)).latched).toBe(true);});
 it('ownership, no self capture, fixed structures, blocked release, invalid actions preserve source',()=>{let s=initial(3);for(const a of [{type:'capture',target:'a'},{type:'ring',target:'tray',node:'hand'},{type:'move',node:'left'}] as Action[]){const r=apply(s,a);expect(r.error).toBeTruthy();expect(r.state).toBe(s);}s=run(s,l3.slice(0,3));expect(apply(s,{type:'release',node:'tray',actor:'npc'}).error).toContain('空位');});
 it('ability items left outside on capture and roles may reverse',()=>{let s=initial(3);s=run(s,[{type:'give',item:'photo',to:'b'},{type:'switch',actor:'b'},{type:'capture',target:'a'}]);expect(s.items.find(i=>i.id==='ring')?.holder).toBeNull();expect(s.active).toBe('b');s=run(s,[{type:'take',item:'ring'},{type:'ring',target:'photo',node:'tray'}]);expect(s.photo).toBe('a');});
 it('save validates all snapshots, corrupt state rejected',()=>{const save=freshSave();expect(validSave(save)).toBe(true);save.levels[1].history=[run(initial(1),l1)];expect(validSave(save)).toBe(true);(save.levels[1].state.items[0].p as number[])[0]=NaN;expect(validSave(save)).toBe(false);});
 it('cut certificates: neither ability can be omitted through alternative exterior positions',()=>{
  // The crossing cut is geometry, not a list of forbidden objects or a prescribed sequence.
  const one=initial(1),outside=LEVELS[0].nodes.filter(n=>n.p[2]>1);
  for(const n of outside){const s=clone(one);s.actors[0].node=n.id;expect(route(s,n.id,'box')).toBeNull();expect(apply(s,{type:'lamp',direction:1},['ring']).error).toBeTruthy();for(const t of ['lamp','box'])expect(apply(s,{type:'ring',target:t,node:'hand'},['ring']).error).toBeTruthy();expect(apply(s,{type:'ring',target:'lamp',direction:1},['lamp']).error).toBeTruthy();}
  for(const disabled of ['camera','key'] as Ability[]){let s=initial(2);for(const n of LEVELS[1].nodes.filter(n=>n.id!=='safe')){s.actors[0].node=n.id;const r=apply(s,{type:'restore'},[disabled]);if(!r.error)s=r.state;const k=apply(s,{type:'portal'},[disabled]);if(!k.error)s=k.state;expect(s.portal).toBe(false);expect(route(s,n.id,'safe')).toBeNull();}}
  const three=initial(3),outer=LEVELS[2].nodes.filter(n=>n.p[2]>1),inner=LEVELS[2].nodes.filter(n=>n.p[2]<1);
  for(const n of outer){const s=clone(three);s.actors[0].node=n.id;for(const d of inner){expect(route(s,n.id,d.id)).toBeNull();expect(apply(s,{type:'ring',target:'b',node:d.id},['photo']).error).toBeTruthy();}for(const sw of ['left','right'])expect(apply(s,{type:'ring',target:sw},['photo']).error).toBeTruthy();expect(apply(s,{type:'ring',target:'photo',node:'tray'},['ring']).error).toBeTruthy();}
  // A hand-held photo cannot cross the wall, and hands cannot reach the high slot.
  for(const n of outer){const s=clone(three);s.actors[0].node=n.id;s.items.find(o=>o.id==='photo')!.holder=null;s.items.find(o=>o.id==='photo')!.p=clone(LEVELS[2].slot!);expect(apply(s,{type:'take',item:'photo'}).error).toBeTruthy();}
  // The sole inside body can choose either switch in any order, never maintain both.
  let npc=three;for(const sw of ['left','right','left','right']){npc=run(npc,[{type:'move',node:sw,actor:'npc'},{type:'hold',switch:sw,actor:'npc'}]);expect(npc.latched).toBe(false);}
 });
 it('flat-photo slot swept volume accepts photo and rejects a human at exactly the same coordinates',()=>{const s=initial(3);expect(space(s,[0,2.7,1.65],[0,2.7,.35],[.24,.02,.17])).toBeNull();expect(space(s,[0,2.7,1.65],[0,2.7,.35],[.26,.84,.26])).not.toBeNull();expect(space(s,[0,4.8,-.3],[0,.85,-.3],[.26,.84,.26])).toContain('顶板');expect(space(s,[0,-1,-.3],[0,.85,-.3],[.26,.84,.26])).toContain('地板');});
 it('camera recovers original moved component, preserves others, and rejects occupied record volume',()=>{const s=initial(2),original=clone(s.items.find(i=>i.id==='door')!.p);s.items.find(i=>i.id==='door')!.p=[3,1.3,2];const restored=run(s,[{type:'restore'}]);expect(restored.items.find(i=>i.id==='door')!.p).toEqual(original);expect(restored.items.filter(i=>i.id!=='door')).toEqual(s.items.filter(i=>i.id!=='door'));const copy=initial(2);LEVELS[1].nodes.push({id:'record-area',label:'test',p:[0,0,-1.5]});copy.actors[0].node='record-area';expect(apply(copy,{type:'restore'}).error).toContain('先让开');LEVELS[1].nodes.pop();});
 it('rejects untrusted labels and impossible ownership from imported saves',()=>{const s=freshSave();s.levels[1].state.actors[0].label='<img src=x>';expect(validSave(s)).toBe(false);const t=freshSave();t.levels[1].state.portal=true;expect(validSave(t)).toBe(false);});
});
