import {describe,it,expect} from 'vitest';
import {freshCity,freshMotion,stepMotion,removeCity,moveRide,type Routes} from '../games/world-in-a-box/dresden-model';
import {soundPreferences} from '../games/world-in-a-box/audio';
const r:Routes={tramStart:.4,tramStops:{north:7.8,oldtown:.4,campus:-8.7},bridge:[.8,7.2],boatStart:-6.6,boatEnd:7.3,berth:{x:5.8,north:3.52}};
describe('STEP03 semantic motion and preference boundaries',()=>{
 it('retains negative heading at exact destination; only real reverse travel changes it',()=>{const ride={position:1,destination:0,direction:-1,speed:1,running:true,blocked:false};let n=ride;for(let i=0;i<50;i++)n=moveRide(n,.05,1);expect(n.position).toBe(0);expect(n.direction).toBe(-1);expect(moveRide({...n,running:true},.05,1).direction).toBe(-1);expect(moveRide({...n,running:true,destination:2},.05,1).direction).toBe(1);});
 it('berthing includes lateral movement, pause is stationary, departure clears bank before along-river motion',()=>{const s={...freshCity(),placed:['paddle_steamer','river_pier'] as const};let m=freshMotion(r);m.boat.position=m.boat.destination=5.8;m.boat.running=true;m.dock=true;const n=stepMotion(m,{...s,placed:[...s.placed]},r,.05);expect(n.boat.running).toBe(true);expect(n.boatSpeed).toBeGreaterThan(0);expect(n.boatNorth).toBeLessThan(4);const paused=stepMotion({...n,boat:{...n.boat,running:false}},{...s,placed:[...s.placed]},r,.05);expect(paused.boatNorth).toBe(n.boatNorth);expect(paused.boatSpeed).toBe(0);m=n;for(let i=0;i<40;i++)m=stepMotion(m,{...s,placed:[...s.placed]},r,.05);expect(m.boatNorth).toBe(3.52);expect(m.boat.running).toBe(false);const depart=stepMotion({...m,dock:false,boat:{...m.boat,running:true,destination:7.3}},{...s,placed:[...s.placed]},r,.05);expect(depart.boatNorth).toBeGreaterThan(3.52);expect(depart.boat.position).toBe(5.8);});
 it('removing pier or ship clears dock movement and speed',()=>{let m=freshMotion(r);m.dock=true;m.boatNorth=3.7;m.boatSpeed=.45;m.boat.running=true;const s={...freshCity(),placed:['paddle_steamer','river_pier'] as ('paddle_steamer'|'river_pier')[]};for(const id of ['river_pier','paddle_steamer'] as const){const n=removeCity(s,m,id,r);expect(n.motion.boatNorth).toBe(4);expect(n.motion.boat.running).toBe(false);expect(n.motion.boatSpeed).toBe(0);}});
 it('preserves legacy mute and zero channel volume; rejects invalid levels',()=>{expect(soundPreferences(null,true)).toEqual({version:1,muted:true,music:.25,sfx:.55,ambient:.15});expect(soundPreferences({music:0,sfx:9,ambient:NaN,muted:true})).toEqual({version:1,muted:true,music:0,sfx:1,ambient:.15});});
});
