import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {FROZEN_IDS,freshFrozen,freshFrozenMotion,restoreFrozen,assemble,magic,startRide,startSkate,undoFrozen,stepFrozen} from '../games/world-in-a-box/frozen-model';
const advance=(s:ReturnType<typeof freshFrozen>,m:ReturnType<typeof freshFrozenMotion>,seconds:number)=>{for(let i=0;i<seconds*20;i++)stepFrozen(s,m,.05);};
describe('Frozen independent assembly and reversible play',()=>{
 it('exports sixteen named roots, five characters, nonconstant animation and seated morphs',()=>{const bytes=readFileSync('public/assets/world-in-a-box/frozen/frozen-elsa-playground.glb');const gltf=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)).toString());const names=gltf.nodes.map((n:{name:string})=>n.name);for(const id of FROZEN_IDS)expect(names.filter((name:string)=>name==='piece_'+id)).toHaveLength(1);expect(names).toContain('elsa');expect(gltf.animations.some((a:{samplers:{output:number}[]})=>a.samplers.some(s=>gltf.accessors[s.output].count>2))).toBe(true);expect(gltf.meshes.some((m:{primitives:{targets?:unknown[]}[]})=>m.primitives.some(p=>p.targets?.length))).toBe(true);});
 it('all sixteen are independent and completion has no spell requirement',()=>{const s=freshFrozen();for(const id of [...FROZEN_IDS].reverse())expect(assemble(s,id,id)).toBe(true);expect(s.placed).toHaveLength(16);expect(s.bridge).toBe(false);expect(s.rink).toBe(false);});
 it('rejects corrupt, duplicate and foreign ids',()=>{expect(restoreFrozen({schemaVersion:1,placed:['anna','anna','elsa','bad'],bridge:'yes'})).toEqual({...freshFrozen(),placed:['anna']});});
 it('columns are interchangeable and other mismatches fail',()=>{const s=freshFrozen();expect(assemble(s,'palace_column_left','palace_column_right')).toBe(true);expect(assemble(s,'anna','olaf')).toBe(false);});
 it('all three spells work at zero; bridge only ready after growth',()=>{const s=freshFrozen(),m=freshFrozenMotion(s);magic(s,m,'bridge');expect(m.bridge).toBe('growing');magic(s,m,'bridge');advance(s,m,4);expect(m.bridge).toBe('ready');magic(s,m,'rink');advance(s,m,4);expect(m.rink).toBe('ready');magic(s,m,'snow');expect(m.snow).toBe(10);expect(s.placed).toHaveLength(0);advance(s,m,11);expect(m.snow).toBe(0);});
 it('unbridged palace trip stops while lake trip completes',()=>{const s={...freshFrozen(),placed:[...FROZEN_IDS]},m=freshFrozenMotion(s);startRide(s,m,'palace');advance(s,m,15);expect(m.ride.t).toBe(.22);expect(m.ride.blocked).toBe(true);const lake=freshFrozenMotion(s);startRide(s,lake,'lake');advance(s,lake,25);expect(lake.ride.t).toBe(1);});
 it('bridge removal visibly evacuates before clearing',()=>{const s={...freshFrozen(),bridge:true,placed:[...FROZEN_IDS]},m=freshFrozenMotion(s);m.ride.route='palace';m.ride.t=.5;magic(s,m,'bridge');expect(m.bridge).toBe('ready');expect(m.pending?.kind).toBe('bridge');advance(s,m,8);expect(m.ride.t).toBe(.22);expect(m.bridge).toBe('off');});
 it('rink removal returns Olaf to edge, and undo only removes requested actor',()=>{const s={...freshFrozen(),rink:true,placed:[...FROZEN_IDS]},m=freshFrozenMotion(s);startSkate(s,m,'eight');advance(s,m,3);magic(s,m,'rink');expect(m.rink).toBe('ready');advance(s,m,5);expect(m.skate.entry).toBe(0);expect(m.rink).toBe('off');m.ride.t=.2;undoFrozen(s,m,'anna');advance(s,m,12);expect(s.placed).not.toContain('anna');expect(s.placed).toContain('sven');expect(s.placed).toContain('kristoff');});
 it('new revision reset drops pending evacuation and old motions',()=>{const s={...freshFrozen(),bridge:true},m=freshFrozenMotion(s);m.ride.route='palace';m.ride.t=.5;magic(s,m,'bridge');const reset=freshFrozenMotion(freshFrozen(),m.revision+1);advance(freshFrozen(),reset,30);expect(reset.bridge).toBe('off');expect(reset.pending).toBe(null);expect(reset.ride.t).toBe(0);});
 it('background pause does not advance spells or skating until explicit resume',()=>{const s={...freshFrozen(),rink:true,placed:[...FROZEN_IDS]},m=freshFrozenMotion(s);startSkate(s,m,'eight');magic(s,m,'snow');m.paused=true;advance(s,m,20);expect(m.snow).toBe(10);expect(m.skate.t).toBe(0);m.paused=false;advance(s,m,1);expect(m.skate.t).toBeGreaterThan(0);});
 it('a walking friend reserves the narrow bridge',()=>{const s={...freshFrozen(),bridge:true,placed:[...FROZEN_IDS]},m=freshFrozenMotion(s);m.bridgeWalk=.5;expect(startRide(s,m,'palace')).toBe(false);expect(startRide(s,m,'lake')).toBe(true);});
 it('undo Olaf does not wait on an unrelated parked sleigh',()=>{const s={...freshFrozen(),rink:true,placed:[...FROZEN_IDS]},m=freshFrozenMotion(s);m.ride.t=1;startSkate(s,m,'circle');advance(s,m,2);undoFrozen(s,m,'olaf');advance(s,m,3);expect(s.placed).not.toContain('olaf');expect(s.placed).toContain('sleigh');expect(m.ride.t).toBe(1);});
});
