import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {CITY_IDS,freshCity,restoreCity,placeCity,removeCity,freshMotion,stepMotion,canSection,clockParts,type Routes} from '../games/world-in-a-box/dresden-model';
const glb=readFileSync('public/assets/world-in-a-box/dresden/dresden-river-campus.glb');const doc=JSON.parse(glb.subarray(20,20+glb.readUInt32LE(12)).toString());
const route=doc.nodes.find((n:{name:string})=>n.name==='tram_route').extras,boat=doc.nodes.find((n:{name:string})=>n.name==='boat_route').extras;
const routes:Routes={tramStart:.4,tramStops:{campus:route.points[route.stops.campus][1],north:route.points[route.stops.north][1],oldtown:route.points[route.stops.oldtown][1]},bridge:route.bridgeLimits,boatStart:boat.points[0][0],boatEnd:boat.points[1][0],berth:{x:5.8,north:3.52}};
describe('Dresden assembly and independently movable mechanisms',()=>{
 it('exports exactly 18 semantic roots and all slots, no mesh-count progress',()=>{expect(doc.nodes.filter((n:{name:string})=>/^piece_[a-z_]+$/.test(n.name)&&(CITY_IDS as readonly string[]).includes(n.name.slice(6))).length).toBe(18);for(const id of CITY_IDS){expect(doc.nodes.some((n:{name:string})=>n.name==='slot_'+id)).toBe(true);expect(doc.nodes.some((n:{name:string})=>n.name==='anchor_'+id)).toBe(true);}});
 it('accepts arbitrary order, upper pieces first, ignores wrong matches and duplicate submissions',()=>{let s=freshCity();for(const id of [...CITY_IDS].reverse()){const before=s;s=placeCity(s,id,id);expect(s.placed.length).toBe(before.placed.length+1);expect(placeCity(s,id,id)).toBe(s);}expect(s.placed.length).toBe(18);expect(placeCity(freshCity(),'yellow_tram','river_pier').placed).toEqual([]);});
 it('restores only schema 2 known pieces and settings, never restores motion',()=>{expect(restoreCity({version:1,placed:CITY_IDS})).toEqual(freshCity());expect(restoreCity({schemaVersion:2,placed:['yellow_tram','unknown','yellow_tram'],night:true}).placed).toEqual(['yellow_tram']);expect(freshMotion(routes).tram.running).toBe(false);});
 it('same bank travel works without bridge; crossing stops safely and resumes after bridge',()=>{let s=placeCity(freshCity(),'yellow_tram','yellow_tram'),m=freshMotion(routes);m.tram.destination=routes.tramStops.campus;m.tram.running=true;for(let i=0;i<200;i++)m=stepMotion(m,s,routes,.05);expect(m.tram.position).toBe(routes.tramStops.campus);m.tram.destination=routes.tramStops.north;m.tram.running=true;for(let i=0;i<250;i++)m=stepMotion(m,s,routes,.05);expect(m.tram.position).toBe(routes.bridge[0]);expect(m.tram.blocked).toBe(true);s=placeCity(s,'augustus_bridge','augustus_bridge');m.tram.running=true;for(let i=0;i<150;i++)m=stepMotion(m,s,routes,.05);expect(m.tram.position).toBe(routes.tramStops.north);});
 it('bridge removal while crossing safely resets tram, reverse direction also blocks',()=>{const s={...freshCity(),placed:[...CITY_IDS]},m=freshMotion(routes);m.tram.position=4;m.tram.running=true;m.tram.destination=7.8;const n=removeCity(s,m,'augustus_bridge',routes);expect(n.bridgeReset).toBe(true);expect(n.motion.tram.position).toBe(routes.tramStart);expect(n.motion.tram.running).toBe(false);m.tram.position=7.8;m.tram.destination=.4;m.tram.running=true;let r=m;for(let i=0;i<20;i++)r=stepMotion(r,n.state,routes,.05);expect(r.tram.position).toBe(routes.bridge[1]);});
 it('boat moves without bridge or pier and removing transport cancels its motion/follow',()=>{let s=placeCity(freshCity(),'paddle_steamer','paddle_steamer'),m=freshMotion(routes);m.boat.running=true;m.follow='boat';for(let i=0;i<220;i++)m=stepMotion(m,s,routes,.05);expect(m.boat.position).toBe(routes.boatEnd);m.boat.running=true;const n=removeCity(s,m,'paddle_steamer',routes);expect(n.motion.boat.running).toBe(false);expect(n.motion.follow).toBe(null);expect(removeCity(s,m,'river_pier',routes).state.placed).toEqual(s.placed);});
 it('section requires its two pieces and removing either closes it without affecting others',()=>{let s=freshCity();expect(canSection(s)).toBe(false);s=placeCity(s,'slub_skylight','slub_skylight');s=placeCity(s,'slub_surface','slub_surface');expect(canSection(s)).toBe(true);const m=freshMotion(routes);m.section=true;const n=removeCity(s,m,'slub_surface',routes);expect(n.motion.section).toBe(false);expect(n.state.placed).toEqual(['slub_skylight']);});
 it('large background dt is clamped and paused mechanisms never move',()=>{const s={...freshCity(),placed:[...CITY_IDS]},m=freshMotion(routes);expect(stepMotion(m,s,routes,10000)).toEqual(m);m.tram.running=true;m.tram.destination=7.8;expect(stepMotion(m,s,routes,10000).tram.position-m.tram.position).toBeLessThan(.1);});
 it('authored dimensions clear pier edges, arch and banks including paddles',()=>{expect(4-boat.halfWidth).toBeGreaterThan(3.2+.11);expect(4+boat.halfWidth).toBeLessThan(4.8-.11);expect(boat.top).toBeLessThan(boat.archClearance);expect(routes.bridge[0]+.65).toBeLessThan(1.6);expect(routes.bridge[1]-.65).toBeGreaterThan(6.4);});
});
describe('real timezone clocks',()=>{
 it.each([['2026-01-01T16:30:00Z','2026-01-02 00:30','2026-01-01 17:30'],['2026-07-01T16:30:00Z','2026-07-02 00:30','2026-07-01 18:30'],['2026-10-25T01:30:00Z','2026-10-25 09:30','2026-10-25 02:30'],['2026-03-29T01:30:00Z','2026-03-29 09:30','2026-03-29 03:30']])('%s uses IANA rules',(utc,china,germany)=>{const d=new Date(utc);expect(clockParts(d,'Asia/Shanghai').text).toBe(china);expect(clockParts(d,'Europe/Berlin').text).toBe(germany);});
 it('hour hand includes minutes across midnight and noon',()=>{expect(clockParts(new Date('2026-01-01T16:30:00Z'),'Asia/Shanghai').hourAngle).toBe(15);expect(clockParts(new Date('2026-01-01T04:30:00Z'),'Asia/Shanghai').hourAngle).toBe(15);});
});
