import {ActionCoordinator} from './action-coordinator';
import {OddityLifetime} from './runtime-lifecycle';
import {planAction,actorName,type Plan} from './intent';
import {selectionLandmarks,entityName,symbols,type Landmark} from './landmarks';
import type {MountGameContext} from '../../packages/game-core';
import {bindInputLifecycle,ignoreGameKey,rovingGroup,preserveRegionFocus} from '../../packages/ui/input';
import {LEVELS,initial,apply,actor,layout,item,routeObstacle,position,freshSave,validSave,type Save,type Action,type ActorId,type Ability} from './model';
import {OddityScene} from './scene';
import {OddityAudio} from './audio';
import {demonstration} from './demo';
import type {Pick} from './selection';
import {createActionPanel} from './action-panel';
import {createLandmarkView} from './landmark-view';
import './styles.css';
const names:Record<Ability,string>={ring:'扳指',lamp:'台灯',photo:'照片',camera:'相机',key:'钥匙'};
const rules:Record<Ability,string>={ring:'眼睛看得到，扳指才够得着。玻璃透视，墙会挡住；路也要够宽。',lamp:'灯一直照着墙的一小块，那一块才能穿过。转开灯，通道就关闭。',photo:'拿照片的人碰到同伴，才可收进一人。外面的人拿起照片，在身旁空地放出同伴。奇物留在外面。',camera:'只把预存照片里的普通物件恢复原样。还是原来那件，不会多出一件，也不会让所有事情倒退。',key:'拿钥匙走到完整门旁，选一个已知的安全地方；还要亲自穿过门。'};
const hints=[['先观察窗内的灯和墙，再看看档案盒被什么挡住。','扳指可以隔着玻璃转动关节；台灯照到的墙面才会出现通道。','在观察窗前用扳指把灯转向通道墙；进去绕过L形隔板，带盒子沿光区返回。'],['门坏了，外面的走廊也断了。相机记住了哪些东西？','相机只恢复门；钥匙需要完整锁孔，能把门接到已知安全地点。','先预览并恢复门，走到门前用钥匙连接小院，再走过门。'],['投递口很窄。室内有人能接住东西，两处开关却相隔很远。','照片能收一人；扳指能搬照片。照片要由外面的人实际拿着，才能收放。','收纳同伴，把照片送到托盘，请接应员拿起并释放。让两人分别保持开关；门会保持打开，再让全员出门。']];
const button=(id:string,label:string,extra='')=>`<button type="button" data-cmd="${id}" ${extra}>${label}</button>`;
export function mountOddity(context:MountGameContext){
 const root=context.container;root.className='oddity-mount';let save:Save=freshSave(),warning='';
 try{const raw=context.storage.get<unknown>('v1',null);if(raw===null&&localStorage.getItem('family-games/oddity-puzzles/v1')!==null)warning='旧记录无法读取，已打开新的现场。其他游戏记录保留。';if(raw!==null){if(validSave(raw))save=raw;else warning='旧记录无法读取，已打开新的现场。其他游戏记录保留。';}}catch{warning='无法读取本机记录，本次可以继续玩。';}
 const audio=new OddityAudio();audio.music=save.music;audio.sfx=save.sfx;

 let scene:OddityScene|undefined,dead=false,loaded=false,paused=false,epoch=0,selected='',picking:Pick|null=null,more=false,notice='看地标认位置；点物件看动作，点脚印走过去。',opener:HTMLElement|null=null,selectionOpener:string|null=null;
 const intention=new ActionCoordinator(()=>save.levels[save.current]);const lifetime=new OddityLifetime(),signal=lifetime.signal;let performingActor:ActorId='a';let currentMarks:Landmark[]=[];let actionFocus:string|null=null;let expandedLandmarks=false;let pointer:{x:number;y:number;id:number;target:EventTarget|null}|null=null,canceledPointer=false;

 root.innerHTML=`<main class="oddity" aria-label="奇物事务所"><header class="odd-header"><a tabindex="0" href="${new URLSearchParams(location.search).get('from')==='hub'?'?hub=classic&from=world':'?world=my-game-world'}" class="odd-home">← 返回大厅</a><div><p class="odd-kicker">ODDITY OFFICE · 0.2</p><h1>奇物事务所</h1></div><button type="button" data-top="sound">声音</button></header><nav class="odd-levels" aria-label="三个案件"></nav><section class="odd-goal"><span class="odd-seal" aria-hidden="true">奇</span><div><h2></h2><p></p></div></section><div class="odd-play"><section class="odd-stage-wrap" aria-label="微缩房间"><div class="odd-stage" data-ready="false"></div><p class="odd-preview" aria-live="polite">脚印是人物终点；方框是搬运落点；人形是释放空位。</p><div class="odd-views" aria-label="观察角度">${button('view0','主视角')}${button('view1','另一侧')}${button('view2','俯看')}${button('landmarks','查看全部站位')}</div><p class="odd-caption">地标引线连着实物 · 墙仍会挡住行动</p><div class="odd-cards" aria-label="本关两种能力"></div></section><section class="odd-controls" aria-label="调查操作"><div class="odd-actors" aria-label="切换调查员"></div><p class="odd-status" role="status" aria-live="polite"></p><p class="odd-save" role="alert"></p><p class="odd-intent"></p><div class="odd-commands" aria-label="对象动作"></div><div class="odd-tools">${button('cancel','取消 · Esc','hidden')}${button('hint','提示')}${button('undo','撤回一步 · Z')}${button('reset','重置本关')}${button('resume','继续调查','hidden')}</div><p class="odd-help">Tab 换区域 · 方向键选地标 · Enter / 空格操作<br>Esc 取消 · Z 撤回 · Q 换调查员</p><div class="odd-complete" hidden></div></section></div><dialog class="odd-dialog" aria-label="调查说明"></dialog></main>`;
 const q=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;
 const host=q('.odd-stage'),commands=q('.odd-commands'),cards=q('.odd-cards'),dialog=q<HTMLDialogElement>('dialog');
 const labels=document.createElement('div');labels.className='odd-labels';labels.setAttribute('aria-label','场景地标');
 const leaders=document.createElementNS('http://www.w3.org/2000/svg','svg');leaders.classList.add('odd-leaders');leaders.setAttribute('aria-hidden','true');
 const groups=[rovingGroup(q('.odd-levels'),{items:'button'}),rovingGroup(cards,{items:'button'}),rovingGroup(commands,{items:'button'}),rovingGroup(q('.odd-actors'),{items:'button'}),rovingGroup(labels,{items:'button'})];
 const state=()=>save.levels[save.current].state;
 const landmarkView=createLandmarkView(host,labels,leaders,()=>groups[4].refresh());
 const actionPanel=createActionPanel({state,perform,startPicking,selectEntity,preserve:html=>preserve(commands,html),refresh:()=>groups[2].refresh(),preview:q('.odd-preview')});
 const {callbacks,previews}=actionPanel;
 function persist(){try{context.storage.set('v1',save);if(JSON.stringify(context.storage.get<unknown>('v1',null))!==JSON.stringify(save))throw Error('write');if(warning.startsWith('本机记录没有保存成功'))warning='';}catch{warning='本机记录没有保存成功。可以继续玩，请暂时不要关闭页面。';}q('.odd-save').textContent=warning;}
 function preserve(region:HTMLElement,html:string){preserveRegionFocus(region,()=>{region.innerHTML=html;},e=>e.dataset.cmd??null,id=>region.querySelector(`[data-cmd="${id}"]`),()=>region.querySelector('button'));}
 function render(){const s=state(),l=layout(s);root.dataset.level=String(s.level);root.dataset.active=s.active;root.dataset.won=String(s.won);root.dataset.state=JSON.stringify(s);root.dataset.history=String(save.levels[save.current].history.length);root.dataset.intent=picking?.kind??(intention.active?'running':'none');
  q('.odd-goal h2').textContent=`${s.level.toString().padStart(2,'0')} / ${l.title}`;q('.odd-goal p').textContent=l.goal;q('.odd-status').textContent=intention.active?actorName(s,performingActor)+'正在行动：'+intention.label+'；可以取消或撤回。':notice;q('.odd-save').textContent=warning;
  preserve(q('.odd-levels'),LEVELS.map(l=>button('level'+l.id,l.title,`${l.id>save.unlocked?'disabled':''} aria-current="${l.id===s.level?'step':'false'}"`)).join(''));
  preserve(q('.odd-actors'),s.actors.filter(a=>a.id!=='npc').map(a=>button('actor'+a.id,`${symbols[a.id]} ${actorName(s,a.id)}${a.inside?' · 照片中':a.id===s.active?' · 当前':''}`,`${a.inside?'disabled':''} aria-pressed="${a.id===s.active}"`)).join(''));
  preserve(cards,l.abilities.map(a=>{const o=item(s,a),loc=o.fixed?'固定灯座':o.holder?actorName(s,o.holder)+'持有':'在场景中';return `<button type="button" class="odd-card" data-cmd="ability${a}"><img alt="" src="${scene?.thumbnail(a==='photo'&&s.photo?'actor_'+s.photo:'item_'+a)??''}"><span><strong>${names[a]}</strong><small>${loc}${a==='photo'?(s.photo?' · 内有'+actorName(s,s.photo):' · 空片'):''}</small></span></button>`;}).join(''));
  q<HTMLButtonElement>('[data-cmd=resume]').hidden=!paused;q<HTMLButtonElement>('[data-cmd=cancel]').hidden=!picking&&!intention.active;q<HTMLButtonElement>('[data-cmd=undo]').disabled=!save.levels[s.level].history.length;
  q('.odd-intent').textContent=picking?`${actorName(s,picking.who)} · ${picking.tool==='lamp'?'用手':picking.kind.startsWith('ring')||picking.tool==='ring'?'用扳指':picking.kind==='release'||picking.kind==='capture'?'用照片':'接受请求'}${picking.target?' · 对'+entityName(s,picking.target):''} · ${picking.kind==='lamp-wall'?'选择墙面':picking.kind==='ring-target'||picking.kind==='capture'?'选择人物或物件':picking.kind==='npc-hold'?'选择开关':picking.kind==='release'?'选择身旁释放空位':'选择落点'}`:'';
  renderCommands();renderMarks();const complete=q('.odd-complete');complete.hidden=!s.won||intention.active;complete.innerHTML=s.won?`<h3>大家平安到达了！</h3>${s.level<3?button('next','下一个案件'):'<p>三个案件完成，可以回大厅或再探索一次。</p>'}`:'';groups.forEach(g=>g.refresh());
 }
 function startPicking(p:Pick){picking=p;more=false;selectionOpener=(document.activeElement as HTMLElement)?.dataset.cmd??null;scene?.clearGuide();render();}
 function renderCommands(){actionPanel.render({selected,picking,more,active:intention.active,scene});}
 function renderMarks(){currentMarks=selectionLandmarks(state(),picking,selected,expandedLandmarks);landmarkView.render(currentMarks,selected,picking,scene);}
 const positionLabels=()=>landmarkView.position();
 const highlightMark=(id:string)=>landmarkView.highlight(id);
 function cancelIntent(message='已取消，重新选择。'){pointer=null;canceledPointer=true;const before=intention.cancel();if(before){scene?.cancel();persist();}audio.stop();picking=null;scene?.clearGuide();notice=message;render();if(selectionOpener)root.querySelector<HTMLElement>(`[data-cmd="${selectionOpener}"]`)?.focus({preventScroll:true});selectionOpener=null;}
 function perform(plan:Plan,label:string){if(!loaded)return;if(paused){notice='已暂停，点“继续调查”后再行动。';render();return;}if(intention.active||scene?.busy)return;if(plan.error){notice=plan.error;if(plan.obstacle)scene?.showObstacle(plan.obstacle.p);else scene?.clearGuide();render();return;}actionFocus=(document.activeElement as HTMLElement)?.dataset.cmd??null;if(!intention.begin(plan,label))return;picking=null;scene?.clearGuide();step();if(document.activeElement===document.body)q<HTMLButtonElement>('[data-cmd=cancel]').focus({preventScroll:true});}
 function step(){const next=intention.next();if(!next){intention.finish();scene?.clearGuide();const s=state();if(s.won)save.unlocked=Math.max(save.unlocked,Math.min(3,s.level+1));notice=s.won?'目标完成了。':s.latched?'门锁已解除，可以主动选择一起出去。':'完成了。观察现场，再选下一步。';persist();render();restoreActionFocus();return;}
  if(next.error){notice=next.error+' 行动已停止。';intention.finish();persist();render();return;}performingActor='actor'in next.action&&next.action.actor?next.action.actor:state().active;scene?.start(next.motions);if(next.action.type==='ring'&&next.action.target!=='lamp')scene?.showRoute(next.motions,'carry');else if(next.action.type==='release')scene?.showRoute(next.motions,'release');audio.cue(next.sound??'place');persist();render();
 }
 function restoreActionFocus(){if(actionFocus&&(document.activeElement===document.body||(document.activeElement as HTMLElement)?.dataset.cmd==='cancel')){const el=root.querySelector<HTMLElement>(`[data-cmd="${actionFocus}"]`)??labels.querySelector<HTMLElement>(`[data-entity-id="${selected}"]`)??commands.querySelector<HTMLElement>('button');el?.focus({preventScroll:true});}actionFocus=null;}
 function changeActor(id:ActorId){if(id==='npc'){selectEntity('npc');return;}cancelIntent('已切换调查员。');const result=apply(state(),{type:'switch',actor:id});if(result.error){notice=result.error;render();return;}save.levels[save.current].state=result.state;selected=id;persist();render();scene?.select(id);}
 function selectEntity(id:string){if(intention.active)return;selected=id;more=false;scene?.select(id);if(id==='lamp'){const s=state(),hand=!apply(s,{type:'lamp',direction:(s.lamp+1)%3}).error,ring=item(s,'ring').holder===s.active;if(!(hand&&ring)){startPicking({kind:'lamp-wall',who:s.active,target:'lamp',tool:ring?'ring':'lamp'});return;}}render();}
 function choose(mark:Landmark){if(intention.active||paused)return;const s=state(),node=mark.node??(picking&&mark.entity==='tray'?'tray':undefined),id=mark.entity;
  if(picking){const pick=picking;if(pick.kind==='ring-target'&&id){selected=id;scene?.select(id);if(id==='lamp'){selected='lamp';startPicking({kind:'lamp-wall',who:pick.who,target:'lamp',tool:'ring'});}else startPicking({kind:'ring-place',who:pick.who,target:id,tool:'ring'});return;}
   if(pick.kind==='capture'&&id&&s.actors.some(a=>a.id===id)){perform(planAction(s,{type:'capture',target:id as ActorId},true),'用照片收纳'+entityName(s,id));return;}
   if(pick.kind==='npc-hold'&&id&&['left','right'].includes(id)){perform(planAction(s,{type:'hold',switch:id,actor:'npc'},true),'请求接应员走近并保持'+entityName(s,id));return;}
   if(pick.kind==='lamp-wall'&&mark.direction!==undefined){perform(planAction(s,pick.tool==='ring'?{type:'ring',target:'lamp',direction:mark.direction}:{type:'lamp',direction:mark.direction}),actorName(s,pick.who)+'转灯');return;}
   if(node){if(pick.kind==='ring-place')perform(planAction(s,{type:'ring',target:pick.target!,node}),'用扳指搬'+entityName(s,pick.target!));else if(pick.kind==='release')perform(planAction(s,{type:'release',node,actor:pick.who}),actorName(s,pick.who)+'释放同伴');else if(pick.kind==='npc-move')perform(planAction(s,{type:'move',node,actor:'npc'}),'请求接应员走到'+mark.label);return;}
   notice='当前正在'+q('.odd-intent').textContent+'。先选目标，或取消。';render();return;
  }
  if(mark.kind==='actor'&&id!=='npc'){changeActor(id as ActorId);return;}
  if(mark.kind==='wall'&&selected==='lamp'){const ring=s.items.some(o=>o.id==='ring'&&o.holder===s.active),hand=!apply(s,{type:'lamp',direction:(s.lamp+1)%3}).error;if(ring&&hand){notice='这里可以手调，也可以用扳指，请先选工具。';render();return;}perform(planAction(s,ring?{type:'ring',target:'lamp',direction:mark.direction}:{type:'lamp',direction:mark.direction!}),'转灯朝向'+mark.label);return;}
  if(node){perform(planAction(s,node==='safe'?{type:'cross'}:{type:'move',node,actor:s.active},node==='safe'),actorName(s)+'走到'+mark.label);return;}
  selectEntity(id??mark.id);
 }
 function previewMark(mark:Landmark){if(intention.active)return;highlightMark(mark.id);scene?.select(mark.entity??'');const s=state();let a:Action|undefined,kind:'walk'|'carry'|'release'|'interaction'='walk';const node=mark.node??(picking&&mark.entity==='tray'?'tray':undefined);
  if(node){if(picking?.kind==='ring-place'){a={type:'ring',target:picking.target!,node};kind='carry';}else if(picking?.kind==='release'){a={type:'release',node,actor:picking.who};kind='release';}else if(!picking||picking.kind==='npc-move')a={type:'move',node,actor:picking?.who??s.active};}
  if(a){const r=apply(s,a);scene?.showRoute(r.motions,kind);if(r.error&&a.type==='move'){const obstacle=routeObstacle(s,actor(s,a.actor??s.active).node,a.node);if(obstacle)scene?.showObstacle(obstacle.p);}q('.odd-preview').textContent=r.error?`${mark.label}：${r.error}`:`${kind==='carry'?'▧ 搬运轨迹与照片落点':kind==='release'?'♙ 人形释放空位':'♧ 人物脚印终点'} · ${mark.label}`;}
  else if(mark.kind==='wall'&&mark.direction!==undefined){scene?.showLamp(mark.direction);q('.odd-preview').textContent='灯光将照向'+mark.label+' · 选择才会转灯';}else {scene?.clearGuide();q('.odd-preview').textContent=mark.label+' · 查看不会触发移动';}
 }
 function closeDialog(){if(dialog.open)dialog.close();opener?.focus({preventScroll:true});opener=null;}
 function openDialog(html:string){opener=document.activeElement as HTMLElement;dialog.innerHTML=html;dialog.showModal();dialog.querySelector<HTMLButtonElement>('button')?.focus();}
 function demo(a:Ability){const thumb=scene?.thumbnail('item_'+a);openDialog(`<p class="odd-kicker">小演示 · ${names[a]}</p><div class="odd-demo"><img src="${thumb}" alt="${names[a]}的模型"></div><p>${rules[a]}</p>${demonstration(a,scene?.thumbnail('actor_a')??'')}${button('skipDemo','跳过演示')}${button('doneDemo','知道了')}`);dialog.dataset.ability=a;}
 function nextDemo(){const a=layout(state()).abilities.find(a=>!save.seen.includes(a));if(a)demo(a);}
 async function load(){const current=++epoch;loaded=false;host.dataset.ready='false';intention.finish();scene?.destroy();scene=undefined;host.replaceChildren();picking=null;selected='';expandedLandmarks=false;q<HTMLButtonElement>('[data-cmd=landmarks]').textContent='查看全部站位';q('.odd-preview').textContent='脚印是人物终点；方框是搬运落点；人形是释放空位。';try{scene=new OddityScene(host);host.append(leaders,labels);render();await scene.load(state());if(dead||epoch!==current)return;loaded=true;host.dataset.ready='true';render();nextDemo();}catch(e){if(dead||epoch!==current)return;notice='房间模型没有载入，请检查本地文件后刷新。';warning=String(e);render();}}
 function ability(a:Ability){if(intention.active)return;picking=null;selected=a;more=false;if(a==='lamp'){selectEntity('lamp');return;}if(a==='photo'&&item(state(),'photo').holder===state().active){startPicking({kind:state().photo?'release':'capture',who:state().active,target:state().photo??undefined});return;}if(a==='ring'){startPicking({kind:'ring-target',who:state().active,tool:'ring'});return;}scene?.select(a);render();}
 function command(id:string){if(id==='landmarks'){expandedLandmarks=!expandedLandmarks;q<HTMLButtonElement>('[data-cmd=landmarks]').textContent=expandedLandmarks?'只看关键地标':'查看全部站位';renderMarks();return;}if(id.startsWith('view')){scene?.view(Number(id.slice(4)));positionLabels();return;}if(id==='resume'){paused=false;audio.resume();notice='继续调查；刚才未完成的行动已取消。';render();return;}void audio.unlock();
  if(id==='cancel'){cancelIntent();return;}
  if(id==='undo'){if(intention.active){cancelIntent('已撤回整个行动。');return;}picking=null;selected='';scene?.select('');scene?.clearGuide();const h=save.levels[save.current].history;if(h.length){scene?.cancel();audio.stop();const controlled=state().active;const restored=h.pop()!;if(!actor(restored,controlled).inside)restored.active=controlled;save.levels[save.current].state=restored;notice='回到行动前，走近与操作一起撤回。';persist();}render();return;}
  if(id==='reset'){cancelIntent('准备重新布置本关。');openDialog(`<h2>重新布置本关？</h2><p>只重置本关现场、撤回和提示，保留其他关和声音偏好。</p>${button('close','继续玩')}${button('confirmReset','确定重置本关')}`);return;}
  if(id==='confirmReset'){save.levels[save.current]={state:initial(save.current),history:[],hints:0};selected='';picking=null;scene?.cancel();scene?.select('');audio.stop();notice='本关回到最初现场。';closeDialog();persist();render();return;}
  if(id==='close'){closeDialog();return;}
  if(id==='hint'){const current=save.levels[save.current];current.hints=Math.min(3,current.hints+1);persist();openDialog(`<h2>提示 · ${['观察','规则','下一步'][current.hints-1]}</h2><p>${hints[save.current-1][current.hints-1]}</p>${button('close','回到调查')}`);return;}
  if(id==='skipDemo'||id==='doneDemo'){save.seen.push(dialog.dataset.ability!);persist();closeDialog();nextDemo();return;}
  if(id==='next')id='level'+(save.current+1);
  if(id.startsWith('level')){const n=Number(id.slice(5));if(n>save.unlocked||n===save.current)return;cancelIntent();save.current=n;save.levels[n]??={state:initial(n),history:[],hints:0};audio.stop();persist();notice='先看清实物和地标，再行动。';void load();return;}
  if(id.startsWith('actor')){changeActor(id.slice(5) as ActorId);return;}
  if(id.startsWith('ability')){ability(id.slice(7) as Ability);return;}
  if(id.startsWith('landmark:')){const mark=currentMarks.find(m=>m.id===id.slice(9));if(mark)choose(mark);return;}
  if(id==='more'){more=!more;renderCommands();return;}
  if(id==='toggleMusic'||id==='toggleSfx'){if(id==='toggleMusic')save.music=!save.music;else save.sfx=!save.sfx;audio.music=save.music;audio.sfx=save.sfx;audio.sync();persist();showSound(false);return;}
  if(!paused&&!intention.active)callbacks.get(id)?.();
 }
 function showSound(open=true){const html=`<h2>声音</h2>${button('toggleMusic',save.music?'音乐：开':'音乐：关')}${button('toggleSfx',save.sfx?'音效：开':'音效：关')}${button('close','回到调查')}`;if(open)openDialog(html);else{const id=(document.activeElement as HTMLElement)?.dataset.cmd;dialog.innerHTML=html;dialog.querySelector<HTMLElement>(`[data-cmd="${id}"]`)?.focus();}}
 const click=(e:MouseEvent)=>{if((e.target as Element).closest('.odd-home')){cancelIntent('已离开现场。');return;}const el=(e.target as Element).closest<HTMLButtonElement>('button');if(!el||!root.contains(el))return;if(canceledPointer&&e.detail!==0){e.preventDefault();canceledPointer=false;return;}if(el.dataset.top==='sound'){void audio.unlock();showSound();return;}if(el.dataset.cmd)command(el.dataset.cmd);};root.addEventListener('click',click,{signal});
 const key=(e:KeyboardEvent)=>{if(dialog.open||ignoreGameKey(e,root))return;if(e.key.toLowerCase()==='z'){e.preventDefault();command('undo');}else if(e.key.toLowerCase()==='q'){e.preventDefault();const next=state().actors.find(a=>a.id!==state().active&&a.id!=='npc'&&!a.inside);if(next)changeActor(next.id);}else if(e.key==='Escape'){e.preventDefault();cancelIntent();}};root.addEventListener('keydown',key,{signal});
 dialog.addEventListener('cancel',e=>{e.preventDefault();if(dialog.querySelector('[data-cmd=skipDemo]'))command('skipDemo');else closeDialog();},{signal});
 const focus=(e:FocusEvent)=>{const b=(e.target as Element).closest<HTMLElement>('[data-landmark]');if(!b)return;const mark=currentMarks.find(m=>m.id===b.dataset.landmark);if(mark){previewMark(mark);for(const el of labels.querySelectorAll('button'))el.setAttribute('aria-pressed',String(el===b));}};labels.addEventListener('focusin',focus,{signal});commands.addEventListener('focusin',e=>{const id=(e.target as HTMLElement).dataset.cmd;if(id)previews.get(id)?.();},{signal});commands.addEventListener('pointerover',e=>{if(e.pointerType==='touch')return;const id=(e.target as Element).closest<HTMLElement>('[data-cmd]')?.dataset.cmd;if(id)previews.get(id)?.();},{signal});
 labels.addEventListener('pointerover',e=>{if(e.pointerType==='touch')return;const b=(e.target as Element).closest<HTMLElement>('[data-landmark]');const mark=currentMarks.find(m=>m.id===b?.dataset.landmark);if(mark)previewMark(mark);},{signal});
 root.addEventListener('pointerdown',e=>{canceledPointer=false;pointer=e.isPrimary&&e.button===0?{x:e.clientX,y:e.clientY,id:e.pointerId,target:e.target}:null;},{capture:true,signal});
 root.addEventListener('pointermove',e=>{if(pointer&&Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>8){pointer=null;canceledPointer=true;}},{capture:true,signal});
 host.addEventListener('pointerup',e=>{if((e.target as Element).closest('button'))return;const start=pointer;pointer=null;if(!start||start.id!==e.pointerId||canceledPointer)return;const pick=scene?.pick(e.clientX,e.clientY);const mark=pick?.target?pickEntity(pick.target):pick?.node?currentMarks.find(m=>m.node===pick.node):pick?.wall!==undefined?currentMarks.find(m=>m.direction===pick.wall):undefined;if(mark){choose(mark);const button=labels.querySelector<HTMLElement>(`[data-landmark="${mark.id}"]`);button?.focus({preventScroll:true});}},{signal});
 host.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||pointer||(e.target as Element).closest('button'))return;const pick=scene?.pick(e.clientX,e.clientY),mark=currentMarks.find(m=>pick?.target?m.entity===pick.target:pick?.node?m.node===pick.node:pick?.wall!==undefined?m.direction===pick.wall:false);if(mark)previewMark(mark);},{signal});
 function pickEntity(id:string):Landmark|undefined{return currentMarks.find(m=>m.entity===id)??(state().items.some(o=>o.id===id)?{id:'item:'+id,kind:'item',entity:id,label:entityName(state(),id),icon:'',p:position(state(),id)}:undefined);}
 const unbind=bindInputLifecycle(root,event=>{pointer=null;canceledPointer=true;if(event?.type==='pointercancel')return;if(!dead&&loaded){cancelIntent('刚才失去焦点，未完成的行动已取消。');paused=true;audio.pause();render();}});
 const actionHome=q('.odd-controls');const actorButtons=q('.odd-actors');host.before(actorButtons);function dockActions(){const mobile=matchMedia('(max-width:850px)').matches;const status=q('.odd-status'),intent=q('.odd-intent');if(mobile){if(commands.parentElement!==host.parentElement)host.after(status,intent,commands);}else if(commands.parentElement!==actionHome)actionHome.prepend(status,intent,commands);}
 dockActions();const resize=new ResizeObserver(()=>{dockActions();scene?.resize();positionLabels();});resize.observe(host);let last=performance.now();
 function frame(now:number){const dt=Math.min(.05,(now-last)/1000);last=now;scene?.frame(state(),dt,paused||document.hidden||dialog.open);intention.advance(!!scene?.busy,paused,dialog.open,document.hidden,step);positionLabels();}lifetime.animate(frame);void load();
 lifetime.own(unbind);lifetime.own(()=>resize.disconnect());lifetime.own(()=>groups.forEach(g=>g.destroy()));
 return {destroy(){if(dead)return;dead=true;epoch++;const before=intention.cancel();if(before){persist();}lifetime.destroy();audio.destroy();scene?.destroy();}};
}
