import type {MountGameContext} from '../../packages/game-core';
import {bindInputLifecycle,ignoreGameKey,rovingGroup,preserveRegionFocus} from '../../packages/ui/input';
import {LEVELS,initial,apply,actor,layout,item,clone,freshSave,validSave,type Save,type Action,type ActorId,type Ability} from './model';
import {OddityScene} from './scene';
import {OddityAudio} from './audio';
import {demonstration} from './demo';
import './styles.css';
const names:Record<Ability,string>={ring:'扳指',lamp:'台灯',photo:'照片',camera:'相机',key:'钥匙'};
const rules:Record<Ability,string>={ring:'眼睛看得到，扳指才够得着。玻璃透视，墙会挡住；路也要够宽。',lamp:'灯一直照着墙的一小块，那一块才能穿过。转开灯，通道就关闭。',photo:'拿照片的人碰到同伴，才可收进一人。外面的人拿起照片，在身旁空地放出同伴。奇物留在外面。',camera:'只把预存照片里的普通物件恢复原样。还是原来那件，不会多出一件，也不会让所有事情倒退。',key:'拿钥匙走到完整门旁，选一个已知的安全地方；还要亲自穿过门。'};
const hints=[['先观察窗内的灯和墙，再看看档案盒被什么挡住。','扳指可以隔着玻璃转动关节；台灯照到的墙面才会出现通道。','在观察窗前用扳指把灯转向通道墙；进去绕过L形隔板，带盒子沿光区返回。'],['门坏了，外面的走廊也断了。相机记住了哪些东西？','相机只恢复门；钥匙需要完整锁孔，能把门接到已知安全地点。','先预览并恢复门，走到门前用钥匙连接小院，再走过门。'],['投递口很窄。室内有人能接住东西，两处开关却相隔很远。','照片能收一人；扳指能搬照片。照片要由外面的人实际拿着，才能收放。','收纳同伴，把照片送到托盘，请接应员拿起并释放。让两人分别保持开关；门会保持打开，再让全员出门。']];
const button=(id:string,label:string,extra='')=>`<button type="button" data-cmd="${id}" ${extra}>${label}</button>`;
export function mountOddity(context:MountGameContext){
 const root=context.container;root.className='oddity-mount';let save:Save=freshSave(),warning='';try{const raw=context.storage.get<unknown>('v1',null);if(raw===null&&localStorage.getItem('family-games/oddity-puzzles/v1')!==null)warning='旧记录无法读取，已打开新的现场。其他游戏记录保留。';if(raw!==null){if(validSave(raw))save=raw;else warning='旧记录无法读取，已打开新的现场。其他游戏记录保留。';}}catch{warning='无法读取本机记录，本次可以继续玩。';}
 let scene:OddityScene|undefined,dead=false,loadEpoch=0,loaded=false,paused=false,mode='walk',target='',notice='选一处落脚点，或看看两张能力卡。',opener:HTMLElement|null=null;const audio=new OddityAudio();audio.music=save.music;audio.sfx=save.sfx;
 root.innerHTML=`<main class="oddity" aria-label="奇物事务所"><header class="odd-header"><a tabindex="0" href="?world=my-game-world" class="odd-home">← 游戏大厅</a><div><p class="odd-kicker">ODDITY OFFICE · 0.1</p><h1>奇物事务所</h1></div><button type="button" data-top="sound">声音</button></header><nav class="odd-levels" aria-label="三个案件"></nav><section class="odd-goal"><span class="odd-seal" aria-hidden="true">奇</span><div><h2></h2><p></p></div></section><div class="odd-play"><section class="odd-stage-wrap" aria-label="微缩房间"><div class="odd-stage" data-ready="false"></div><div class="odd-views" aria-label="观察角度">${button('view0','主视角')}${button('view1','另一侧')}${button('view2','俯看')}</div><p class="odd-caption">地面圆点是落脚处 · 顶板淡出，房间仍封闭</p><div class="odd-cards" aria-label="本关两种能力"></div></section><section class="odd-controls" aria-label="调查操作"><div class="odd-actors" aria-label="切换调查员"></div><p class="odd-status" role="status" aria-live="polite"></p><p class="odd-save" role="alert"></p><div class="odd-tabs" aria-label="操作区域">${button('walk','走动')}${button('objects','拿放物件')}${button('npc','请接应员帮忙')}</div><div class="odd-commands" aria-label="可选动作"></div><div class="odd-tools">${button('hint','提示')}${button('undo','撤回一步 · Z')}${button('reset','重置本关')}${button('resume','继续调查','hidden')}</div><p class="odd-help">Tab 换区域 · 方向键选项 · Enter 确认<br>Esc 返回 · Z 撤回 · Q 换调查员</p><div class="odd-complete" hidden></div></section></div><dialog class="odd-dialog" aria-label="调查说明"></dialog></main>`;
 const q=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;const host=q('.odd-stage'),commands=q('.odd-commands'),cards=q('.odd-cards'),dialog=q<HTMLDialogElement>('dialog');const groups=[rovingGroup(q('.odd-levels'),{items:'button'}),rovingGroup(cards,{items:'button'}),rovingGroup(commands,{items:'button'}),rovingGroup(q('.odd-actors'),{items:'button'})];
 const state=()=>save.levels[save.current].state;
 function persist(){try{context.storage.set('v1',save);const check=context.storage.get<unknown>('v1',null);if(JSON.stringify(check)!==JSON.stringify(save))throw Error('write');if(warning.startsWith('本机记录没有保存成功'))warning='';}catch{warning='本机记录没有保存成功。可以继续玩，请暂时不要关闭页面。';}q('.odd-save').textContent=warning;}
 function snapshotUI(){root.dataset.level=String(save.current);root.dataset.active=state().active;root.dataset.won=String(state().won);root.dataset.state=JSON.stringify(state());root.dataset.history=String(save.levels[save.current].history.length);}
 function render(){const s=state(),l=layout(s);q('.odd-goal h2').textContent=`${s.level.toString().padStart(2,'0')} / ${l.title}`;q('.odd-goal p').textContent=l.goal;q('.odd-status').textContent=notice;q('.odd-save').textContent=warning;
  preserveRegionFocus(q('.odd-levels'),()=>{q('.odd-levels').innerHTML=LEVELS.map(l=>button('level'+l.id,l.title,`${l.id>save.unlocked?'disabled':''} aria-current="${l.id===save.current?'step':'false'}"`)).join('');},e=>e.dataset.cmd??null,id=>root.querySelector(`[data-cmd="${id}"]`));
  preserveRegionFocus(q('.odd-actors'),()=>{q('.odd-actors').innerHTML=s.actors.filter(a=>a.id!=='npc').map(a=>button('actor'+a.id,a.label+(a.inside?' · 照片中':a.id===s.active?' · 当前':''),`${a.inside?'disabled':''} aria-pressed="${a.id===s.active}"`)).join('');},e=>e.dataset.cmd??null,id=>root.querySelector(`[data-cmd="${id}"]`));
  q<HTMLButtonElement>('[data-cmd=npc]').hidden=s.level!==3;q<HTMLButtonElement>('[data-cmd=resume]').hidden=!paused;
  preserveRegionFocus(cards,()=>{cards.innerHTML=l.abilities.map(a=>{const o=item(s,a),loc=o.fixed?'房间里的固定灯座':o.holder?actor(s,o.holder).label+'持有':'已放在场景中';const thumb=scene?.thumbnail(a==='photo'&&s.photo?'actor_'+s.photo:'item_'+a);const content=a==='photo'&&s.photo?' · 内有'+actor(s,s.photo).label:'';return `<button type="button" class="odd-card" data-cmd="ability${a}" aria-pressed="${mode===a}">${thumb?`<img alt="" src="${thumb}">`:''}<span><strong>${names[a]}</strong><small>${loc}${content}</small></span></button>`;}).join('');},e=>e.dataset.cmd??null,id=>root.querySelector(`[data-cmd="${id}"]`));
  renderCommands();q<HTMLButtonElement>('[data-cmd=undo]').disabled=!save.levels[save.current].history.length;const complete=q('.odd-complete');complete.hidden=!s.won;complete.innerHTML=s.won?`<h3>大家平安到达了！</h3><p>${s.level===3?'三个案件都完成了，可以回大厅或再探索一次。':'这间房的目标完成了。'}</p>${s.level<3?button('next','下一个案件'):''}`:'';groups.forEach(g=>g.refresh());snapshotUI();
 }
 const actionMap=new Map<string,Action>();
 function renderCommands(){const s=state(),l=layout(s);actionMap.clear();let html='';const act=(label:string,a:Action)=>{const id='do'+actionMap.size;actionMap.set(id,a);return button(id,label);};const moves=(who?:ActorId)=>l.nodes.map(n=>act(n.label,{type:'move',node:n.id,actor:who})).join('');
  if(mode==='walk')html=`<h3>想走到哪里？</h3><div class="odd-options">${moves()}</div>${s.level===2?act('走过门',{type:'cross'}):''}`;
  else if(mode==='objects')html=`<h3>走近后，用手拿放</h3><div class="odd-options">${s.items.filter(o=>!o.fixed).map(o=>act('拿起'+o.label,{type:'take',item:o.id})+act('放下'+o.label,{type:'drop',item:o.id})).join('')}${s.level===1?button('manualLamp','手调台灯'):''}${s.level===3?s.actors.filter(a=>a.id!==s.active&&!a.inside&&a.id!=='npc').map(a=>s.items.filter(o=>o.holder===s.active).map(o=>act(`把${o.label}交给${a.label}`,{type:'give',item:o.id,to:a.id})).join('')).join(''):''}</div>`;
  else if(mode==='ring'){
   html='<h3>扳指 · 选一个目标</h3><div class="odd-options">'+[...s.items,...s.actors].map(o=>button('target'+o.id,'目标 · '+o.label,`aria-pressed="${target===o.id}"`)).join('')+'</div>';
   if(target==='lamp')html+='<h3>灯朝哪里？</h3>'+["房间后墙","通道墙","左侧墙"].map((t,i)=>act(t,{type:'ring',target:'lamp',direction:i})).join('');
   else if(target){html+='<h3>放在哪里？</h3><div class="odd-options">'+act('自己手边',{type:'ring',target,node:'hand'})+l.nodes.map(n=>act(n.id==='tray'?'接应托盘':n.label,{type:'ring',target,node:n.id})).join('')+'</div>';}
  }else if(mode==='lamp'||mode==='manualLamp')html='<h3>灯座固定在房间里</h3><p>走到灯旁可以用手转动；扳指也可以转关节。</p>'+['房间后墙','通道墙','左侧墙'].map((t,i)=>act(t,{type:'lamp',direction:i})).join('');
  else if(mode==='photo')html='<h3>照片 · 收一人，放一人</h3><div class="odd-options">'+act('拿起照片',{type:'take',item:'photo'})+act('放下照片',{type:'drop',item:'photo'})+s.actors.map(a=>act('收纳'+a.label,{type:'capture',target:a.id})).join('')+'</div><h3>在身旁空地释放</h3><div class="odd-options">'+l.nodes.map(n=>act(n.label,{type:'release',node:n.id})).join('')+'</div>';
  else if(mode==='camera')html='<h3>相机 · 预存局部照片</h3><p>记录：原门板、门铰链、锁孔。<br>没有记录：断开的走廊、人物、奇物。</p>'+button('preview','查看记录范围');
  else if(mode==='key')html='<h3>钥匙 · 选择已知地点</h3><p>走到完整门旁才能连接。</p>'+act('连接安全小院',{type:'portal'})+act('走过门',{type:'cross'});
  else if(mode==='npc')html='<h3>请接应员做一件事</h3><div class="odd-options">'+act('拿起照片',{type:'take',item:'photo',actor:'npc'})+act('放下照片',{type:'drop',item:'photo',actor:'npc'})+act('释放到托盘旁空地',{type:'release',node:'release',actor:'npc'})+act('保持左开关',{type:'hold',switch:'left',actor:'npc'})+act('保持右开关',{type:'hold',switch:'right',actor:'npc'})+'</div><h3>请他走到哪里？</h3><div class="odd-options">'+moves('npc')+'</div>';
  if(s.level===3&&mode==='walk')html+='<h3>站在开关旁</h3>'+act('保持左开关',{type:'hold',switch:'left'})+act('保持右开关',{type:'hold',switch:'right'});
  if(l.abilities.includes(mode as Ability))html+=button('demo'+mode,'看看能力演示');
  preserveRegionFocus(commands,()=>{commands.innerHTML=html;},e=>e.dataset.cmd??null,id=>commands.querySelector(`[data-cmd="${id}"]`),()=>commands.querySelector('button'));groups[2].refresh();
 }
 function perform(a:Action){if(!loaded)return;if(paused){notice='刚才暂停了。点“继续调查”后再行动。';render();return;}if(scene?.busy){notice='正在移动。可以撤回或重置，也可以等它走完。';render();return;}const before=state(),r=apply(before,a);if(r.error){notice=r.error;render();return;}save.levels[save.current].history.push(clone(before));save.levels[save.current].state=r.state;if(r.state.won)save.unlocked=Math.max(save.unlocked,Math.min(3,save.current+1));persist();scene?.start(r.motions);audio.cue(r.sound??'place');notice=r.state.won?'目标完成了。':a.type==='hold'?(r.state.latched?'门锁解开，门会保持开启。':'正在保持开关；走开就会松手。'):a.type==='restore'?'原来的门恢复完整；断开的走廊没有改变。':a.type==='capture'?'同伴进入照片，奇物留在外面。':a.type==='portal'?'门已连接小院。还要走过门才会到达。':'好了。接着观察，选择下一步。';render();}
 function closeDialog(){if(dialog.open)dialog.close();scene?.showPreview(false);opener?.focus({preventScroll:true});opener=null;}
 function openDialog(html:string){opener=document.activeElement as HTMLElement;dialog.innerHTML=html;dialog.showModal();dialog.querySelector<HTMLButtonElement>('button')?.focus();}
 function demo(a:Ability){const thumb=scene?.thumbnail('item_'+a);openDialog(`<p class="odd-kicker">小演示 · ${names[a]}</p><div class="odd-demo" data-demo="${a}"><img src="${thumb}" alt="${names[a]}的三维模型"><span aria-hidden="true">${a==='ring'?'◌ → ◌':a==='lamp'?'光 → ▯':a==='photo'?'人 → ▣ → 人':a==='camera'?'原件 ↶ 原样':'门 → 小院'}</span></div><p>${rules[a]}</p>${demonstration(a,scene?.thumbnail('actor_a')??'')}${button('skipDemo','跳过演示')}${button('doneDemo','知道了')}`);dialog.dataset.ability=a;}
 function nextDemo(){const a=layout(state()).abilities.find(a=>!save.seen.includes(a));if(a)demo(a);}
 async function load(){const epoch=++loadEpoch;loaded=false;host.dataset.ready='false';scene?.destroy();host.innerHTML='';mode='walk';target='';scene=new OddityScene(host);render();try{await scene.load(state());if(dead||epoch!==loadEpoch)return;loaded=true;host.dataset.ready='true';render();nextDemo();}catch(e){if(dead||epoch!==loadEpoch)return;notice='房间模型没有载入。请检查本地文件后刷新。';warning=String(e);render();}}
 function command(id:string){if(id.startsWith('view')){scene?.view(Number(id.slice(4)));return;}if(id==='resume'){paused=false;audio.resume();notice='继续调查。';render();return;}void audio.unlock();
  if(id==='undo'){const h=save.levels[save.current].history;if(h.length){scene?.cancel();audio.stop();save.levels[save.current].state=h.pop()!;notice='回到上一步，所有人物和物件都还原了。';persist();render();}return;}
  if(id==='reset'){scene?.cancel();audio.stop();openDialog(`<h2>重新布置本关？</h2><p>只重置这一关的现场、撤回和提示。其他关、已解锁入口和声音偏好保留。</p>${button('close','继续玩')}${button('confirmReset','确定重置本关')}`);return;}
  if(id==='confirmReset'){save.levels[save.current]={state:initial(save.current),history:[],hints:0};scene?.cancel();audio.stop();mode='walk';target='';notice='本关回到最初的现场。';closeDialog();persist();render();return;}
  if(id==='close'){closeDialog();return;}
  if(id==='hint'){const current=save.levels[save.current];current.hints=Math.min(3,current.hints+1);persist();openDialog(`<h2>提示 · ${['观察','规则','下一步'][current.hints-1]}</h2><p>${hints[save.current-1][current.hints-1]}</p>${button('close','回到调查')}`);return;}
  if(id==='skipDemo'||id==='doneDemo'){save.seen.push(dialog.dataset.ability!);persist();closeDialog();nextDemo();return;}
  if(id.startsWith('demo')){demo(id.slice(4) as Ability);return;}
  if(id==='preview'){scene?.showPreview(true);openDialog(`<h2>记录范围：这扇门</h2><p>门板、门铰链、锁孔恢复到完整时。走廊、人物、背包和奇物都不回退。恢复的是原门，不会复制。</p>${button('close','先不恢复')}${button('restore','恢复这扇门')}`);return;}
  if(id==='restore'){closeDialog();perform({type:'restore'});return;}
  if(id==='next')id='level'+(save.current+1);
  if(id.startsWith('level')){const n=Number(id.slice(5));if(n>save.unlocked||n===save.current)return;save.current=n;save.levels[n]??={state:initial(n),history:[],hints:0};audio.stop();persist();notice='观察这个房间，再试试两种能力。';void load();return;}
  if(id.startsWith('actor')){perform({type:'switch',actor:id.slice(5) as ActorId});return;}
  if(id.startsWith('target')){target=id.slice(6);scene?.select(target);renderCommands();return;}
  if(id.startsWith('ability')){mode=id.slice(7);target='';scene?.select('');render();return;}
  if(['walk','objects','npc','manualLamp'].includes(id)){mode=id;target='';scene?.select('');render();return;}
  if(id==='toggleMusic'||id==='toggleSfx'){if(id==='toggleMusic')save.music=!save.music;else save.sfx=!save.sfx;audio.music=save.music;audio.sfx=save.sfx;audio.sync();persist();showSound(false);return;}
  const action=actionMap.get(id);if(action)perform(action);
 }
 function showSound(open=true){const html=`<h2>声音</h2>${button('toggleMusic',save.music?'音乐：开':'音乐：关')}${button('toggleSfx',save.sfx?'音效：开':'音效：关')}${button('close','回到调查')}`;if(open)openDialog(html);else{const id=(document.activeElement as HTMLElement)?.dataset.cmd;dialog.innerHTML=html;dialog.querySelector<HTMLElement>(`[data-cmd="${id}"]`)?.focus();}}
 const click=(e:MouseEvent)=>{const el=(e.target as Element).closest<HTMLButtonElement>('button');if(!el||!root.contains(el))return;if(el.dataset.top==='sound'){void audio.unlock();showSound();return;}if(el.dataset.cmd)command(el.dataset.cmd);};root.addEventListener('click',click);
 const key=(e:KeyboardEvent)=>{if(dialog.open)return;if(ignoreGameKey(e,root))return;if(e.key.toLowerCase()==='z'){e.preventDefault();command('undo');}else if(e.key.toLowerCase()==='q'&&save.current===3){e.preventDefault();const next=state().actors.find(a=>a.id!==state().active&&a.id!=='npc'&&!a.inside);if(next)perform({type:'switch',actor:next.id});}else if(e.key==='Escape'){e.preventDefault();mode='walk';target='';scene?.select('');render();}};root.addEventListener('keydown',key);
 dialog.addEventListener('cancel',e=>{e.preventDefault();if(dialog.querySelector('[data-cmd=skipDemo]'))command('skipDemo');else closeDialog();});
 let pointer:{x:number;y:number}|null=null;host.addEventListener('pointerdown',e=>{pointer=e.isPrimary&&e.button===0?{x:e.clientX,y:e.clientY}:null;});host.addEventListener('pointerup',e=>{if(!pointer||Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>8)return;pointer=null;const pick=scene?.pick(e.clientX,e.clientY);if(pick?.node){if(mode==='ring'&&target)perform({type:'ring',target,node:pick.node});else perform({type:'move',node:pick.node});}else if(pick?.target){target=pick.target;mode=layout(state()).abilities.includes('ring')?'ring':'objects';render();}});
 const unbind=bindInputLifecycle(root,event=>{pointer=null;if(event?.type==='pointercancel')return;if(!dead&&loaded){paused=true;audio.pause();render();}});const resize=new ResizeObserver(()=>scene?.resize());resize.observe(host);let last=performance.now(),raf=0;function frame(now:number){const dt=Math.min(.05,(now-last)/1000);last=now;scene?.frame(state(),dt,paused||document.hidden||dialog.open);raf=requestAnimationFrame(frame);}raf=requestAnimationFrame(frame);void load();
 return {destroy(){dead=true;loadEpoch++;cancelAnimationFrame(raf);unbind();resize.disconnect();groups.forEach(g=>g.destroy());root.removeEventListener('click',click);root.removeEventListener('keydown',key);audio.destroy();scene?.destroy();}};
}
