import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {actor,feet,layout,position,type State,type Vec,type Motion} from './model';
const v=(p:Vec)=>new T.Vector3(...p);
export class OddityScene {
 readonly renderer:T.WebGLRenderer;readonly scene=new T.Scene();readonly camera=new T.OrthographicCamera();
 asset?:T.Group;private dead=false;private elapsed=0;private duration=0;private motions:Motion[]=[];private preset=0;private size={w:1,h:1};private targets:T.Mesh[]=[];private ray=new T.Raycaster();private beam?:T.Mesh;private gate?:T.Mesh;private preview?:T.Box3Helper;private portraits=new Map<string,T.Texture>();private portrait?:T.Mesh;private selected?:T.BoxHelper;private previousLamp=0;private previousDoor=0;private portal?:T.Mesh;private portalTexture?:T.WebGLRenderTarget;
 constructor(readonly host:HTMLElement){
  this.renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(pointer: coarse)').matches?1.5:2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.3;host.append(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-hidden','true');
  this.scene.add(new T.HemisphereLight(0xfff0d5,0x6d898a,2.7));const sun=new T.DirectionalLight(0xffebcb,3);sun.position.set(-6,15,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-9;sun.shadow.camera.right=9;sun.shadow.camera.top=9;sun.shadow.camera.bottom=-9;sun.shadow.normalBias=.045;this.scene.add(sun);
 }
 async load(s:State){const loaded=await new GLTFLoader().loadAsync(`./assets/oddity-puzzles/room-${s.level}.glb`);if(this.dead){this.disposeTree(loaded.scene);return;}this.asset=loaded.scene;this.scene.add(this.asset);
  this.asset.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true;const cut=o.parent?.userData.cutaway;if(cut){const m=(o.material as T.MeshStandardMaterial).clone();m.transparent=true;m.opacity=o.parent?.name==='wall_ceiling'?.025:.10;m.depthWrite=false;o.material=m;o.castShadow=false;o.userData.pickThrough=true;}for(const m of Array.isArray(o.material)?o.material:[o.material]){m.forceSinglePass=true;if(m.opacity<.5)o.castShadow=false;}}});
  for(const n of layout(s).nodes){const marker=new T.Mesh(new T.CylinderGeometry(.19,.19,.035,24),new T.MeshStandardMaterial({color:0xe2cf9e,roughness:.9}));marker.position.copy(v(n.p)).y=.04;marker.name='nav_'+n.id;marker.userData.node=n.id;this.scene.add(marker);this.targets.push(marker);}
  const wall=this.asset.getObjectByName('wall_door-solid');if(wall)wall.visible=false;const lock=this.asset.getObjectByName('wall_locked-door');if(lock)lock.visible=false;
  if(s.level===1){this.beam=new T.Mesh(new T.ConeGeometry(.70,3.3,32,1,true),new T.MeshBasicMaterial({color:0xffdf82,transparent:true,opacity:.14,depthWrite:false,side:T.DoubleSide}));this.scene.add(this.beam);this.gate=new T.Mesh(new T.PlaneGeometry(1.36,2.35),new T.MeshBasicMaterial({color:0xffdd83,transparent:true,opacity:.22,side:T.DoubleSide,depthWrite:false}));this.gate.position.set(0,1.18,1);this.scene.add(this.gate);const edge=new T.LineSegments(new T.EdgesGeometry(new T.PlaneGeometry(1.38,2.38)),new T.LineBasicMaterial({color:0xffedaf}));this.gate.add(edge);}
  if(s.level===2){this.preview=new T.Box3Helper(new T.Box3(new T.Vector3(-.86,0,-1.7),new T.Vector3(.86,2.7,-1.25)),0xe9b954);this.preview.visible=false;this.scene.add(this.preview);
   const yard=this.asset.getObjectByName('destination_courtyard');if(yard){const view=new T.Scene();view.background=new T.Color(0xe4ecd7);view.add(yard.clone(true));view.add(new T.HemisphereLight(0xffffff,0x79917c,3));const light=new T.DirectionalLight(0xffecc7,3);light.position.set(-4,7,4);view.add(light);const camera=new T.OrthographicCamera(-2.25,2.25,3.0,-.15,.1,30);camera.position.set(0,3,0);camera.lookAt(0,.8,-4.7);this.portalTexture=new T.WebGLRenderTarget(512,512);this.renderer.setRenderTarget(this.portalTexture);this.renderer.render(view,camera);this.renderer.setRenderTarget(null);this.portal=new T.Mesh(new T.PlaneGeometry(1.47,2.45),new T.MeshBasicMaterial({map:this.portalTexture.texture,side:T.DoubleSide}));this.portal.position.set(0,1.25,-1.35);this.scene.add(this.portal);}}

  this.resize();this.frame(s,0,false);
  for(const a of s.actors){const data=this.thumbnail('actor_'+a.id);const tex=new T.TextureLoader().load(data);tex.colorSpace=T.SRGBColorSpace;this.portraits.set(a.id,tex);}
  if(s.level===3){this.portrait=new T.Mesh(new T.PlaneGeometry(.36,.23),new T.MeshBasicMaterial({side:T.DoubleSide}));this.portrait.rotation.x=-Math.PI/2;this.portrait.position.y=.031;this.asset.getObjectByName('item_photo')?.add(this.portrait);}
 }
 resize(){this.size={w:Math.max(1,this.host.clientWidth),h:Math.max(1,this.host.clientHeight)};this.renderer.setSize(this.size.w,this.size.h);const aspect=this.size.w/this.size.h,h=Math.max(7.15,7.7/aspect);Object.assign(this.camera,{left:-h*aspect,right:h*aspect,top:h,bottom:-h,near:.1,far:90});const pos=[[10,30,16],[-14,24,14],[0,28,5]][this.preset];this.camera.position.set(...pos as Vec);this.camera.lookAt(0,0,-.5);this.camera.updateProjectionMatrix();this.camera.updateMatrixWorld();}
 view(n:number){this.preset=n;this.resize();}
 showPreview(show:boolean){if(this.preview)this.preview.visible=show;}
 select(id:string){if(this.selected){this.scene.remove(this.selected);this.selected.geometry.dispose();(this.selected.material as T.Material).dispose();this.selected=undefined;}const object=this.asset?.getObjectByName('item_'+id)??this.asset?.getObjectByName('actor_'+id);if(object){this.selected=new T.BoxHelper(object,0x527a80);this.scene.add(this.selected);}}
 start(motions:Motion[]){this.previousLamp=this.asset?.getObjectByName('pivot_lamp')?.rotation.z??0;this.previousDoor=this.asset?.getObjectByName('hinge_door')?.rotation.y??0;this.motions=motions;this.elapsed=0;this.duration=motions.length?Math.max(.4,...motions.map(m=>m.path.length>1?m.path.slice(1).reduce((sum,p,i)=>sum+v(p).distanceTo(v(m.path[i])),0)/4: .6)):0;}
 cancel(){this.motions=[];this.duration=0;this.elapsed=0;}
 get busy(){return this.elapsed<this.duration;}
 private path(m:Motion,t:number){if(!m.path.length)return null;const lengths=m.path.slice(1).map((p,i)=>distance3(p,m.path[i]));let travel=lengths.reduce((a,b)=>a+b,0)*t;for(let i=0;i<lengths.length;i++){if(travel<=lengths[i]||i===lengths.length-1)return v(m.path[i]).lerp(v(m.path[i+1]),lengths[i]?Math.min(1,travel/lengths[i]):1);travel-=lengths[i];}return v(m.path[0]);}
 frame(s:State,dt:number,paused:boolean){if(!this.asset)return;const was=this.busy;if(!paused)this.elapsed=Math.min(this.duration,this.elapsed+dt);const progress=this.duration?this.elapsed/this.duration:1;
  for(const a of s.actors){const root=this.asset.getObjectByName('actor_'+a.id)!;const motion=this.motions.find(m=>m.id===a.id);root.position.copy(v(feet(s,a.id)));root.scale.setScalar(1);root.visible=!a.inside;let moving=false;
   if(motion&&progress<1){const p=this.path(motion,progress);if(p){if(motion.kind==='capture'||motion.kind==='release'){p.y-=.85;root.scale.setScalar(motion.kind==='capture'?Math.max(.06,1-progress):Math.max(.06,progress));root.visible=true;}else if(motion.kind==='carry')p.y-=.85;root.position.copy(p);moving=true;const next=this.path(motion,Math.min(1,progress+.02));if(next&&motion.kind==='walk')root.rotation.y=Math.atan2(-(next.x-p.x),-(next.z-p.z));if(motion.kind==='portal'&&progress>.35&&progress<.7)root.scale.setScalar(.04);}}
   for(const side of ['l','r']){const leg=this.asset.getObjectByName('leg_'+a.id+'_'+side);const arm=this.asset.getObjectByName('arm_'+a.id+'_'+side);const phase=this.elapsed*12+(side==='l'?0:Math.PI);if(leg)leg.rotation.x=moving?Math.sin(phase)*.35:0;if(arm)arm.rotation.x=a.holding?-.9:this.busy&&this.motions.some(m=>s.items.some(o=>o.id===m.id&&o.holder===a.id))?-.65:moving?Math.sin(phase+Math.PI)*.25:0;}
  }
  for(const o of s.items){const root=this.asset.getObjectByName('item_'+o.id);if(!root)continue;root.position.copy(v(position(s,o.id)));if(o.holder){const ar=this.asset.getObjectByName('actor_'+o.holder)!;ar.updateMatrixWorld(true);const hand=this.asset.getObjectByName('hand_'+o.holder);if(hand)hand.getWorldPosition(root.position);else root.position.copy(ar.position).add(new T.Vector3(.30,1.02,-.17));if(o.id==='ring')root.position.y+=.13;}
   const m=this.motions.find(m=>m.id===o.id);if(m&&progress<1&&m.path.length){const p=this.path(m,progress);if(p)root.position.copy(p);}root.rotation.y=o.id==='photo'?0:0;
  }
  const lamp=this.asset.getObjectByName('pivot_lamp');if(lamp){const target=s.lamp===1?-.75:s.lamp===2?.8:0;lamp.rotation.z=this.motions.some(m=>m.id==='lamp')?T.MathUtils.lerp(this.previousLamp,target,progress):target;}
  const lightWall=this.asset.getObjectByName('wall_light-wall');if(lightWall)lightWall.visible=s.lamp!==1;
  if(this.beam){const from=new T.Vector3(-3,1.25,-.7),to=s.lamp===1?new T.Vector3(0,1.2,1):s.lamp===2?new T.Vector3(-4.8,1.2,-2):new T.Vector3(-3,1.2,-3.7);this.beam.position.copy(from).lerp(to,.5);this.beam.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),from.clone().sub(to).normalize());this.beam.scale.y=from.distanceTo(to)/3.3;}
  if(this.gate)this.gate.visible=s.lamp===1;
  const intact=this.asset.getObjectByName('door_intact'),broken=this.asset.getObjectByName('door_broken'),hinge=this.asset.getObjectByName('hinge_door');if(intact)intact.visible=s.level===3||s.doorRestored;if(broken)broken.visible=s.level===2&&!s.doorRestored;if(hinge){const angle=s.latched?-Math.PI*.48:s.portal?-Math.PI*.45:0;hinge.rotation.y=this.motions.some(m=>m.id==='door'&&m.kind==='turn')?T.MathUtils.lerp(this.previousDoor,angle,progress):angle;}if(intact)intact.scale.y=this.motions.some(m=>m.kind==='restore')?Math.max(.025,progress):1;
  for(const id of ['left','right']){const btn=this.asset.getObjectByName('pivot_'+id);if(btn)btn.position.y=s.actors.some(a=>a.holding===id)?-.055:0;}
  if(this.portrait){this.portrait.visible=!!s.photo;(this.portrait.material as T.MeshBasicMaterial).map=s.photo?this.portraits.get(s.photo)!:null;(this.portrait.material as T.MeshBasicMaterial).needsUpdate=true;}
  const yard=this.asset.getObjectByName('destination_courtyard');if(yard)yard.visible=s.portal;if(this.portal)this.portal.visible=s.portal;
  this.asset.updateMatrixWorld(true);this.selected?.update();this.renderer.render(this.scene,this.camera);this.host.dataset.motion=this.busy?'moving':'still';this.host.dataset.animation=JSON.stringify({progress:this.busy?progress:1,paused,actors:s.actors.map(a=>({id:a.id,p:this.asset!.getObjectByName('actor_'+a.id)!.position.toArray()}))});this.host.dataset.metrics=JSON.stringify({triangles:this.renderer.info.render.triangles,calls:this.renderer.info.render.calls,dpr:this.renderer.getPixelRatio()});if(was&&!this.busy)this.motions=[];
 }
 pick(x:number,y:number):{node?:string;target?:string}|null {const r=this.host.getBoundingClientRect();this.ray.setFromCamera(new T.Vector2((x-r.left)/r.width*2-1,1-(y-r.top)/r.height*2),this.camera);const meshes:T.Object3D[]=[];this.scene.traverseVisible(o=>{if(o instanceof T.Mesh&&!o.userData.pickThrough&&o!==this.beam&&o!==this.gate&&o!==this.portrait&&(o.material as T.Material).opacity>=.3)meshes.push(o);});const hit=this.ray.intersectObjects(meshes,false)[0];let obj:T.Object3D|null=hit?.object??null;while(obj){if(obj.userData.node)return {node:obj.userData.node};if(obj.name.startsWith('item_'))return {target:obj.name.slice(5)};if(obj.name.startsWith('actor_'))return {target:obj.name.slice(6)};obj=obj.parent;}return null;}
 thumbnail(name:string){return `./assets/oddity-puzzles/thumb-${name}.png`;}
 private disposeTree(root:T.Object3D){root.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){for(const value of Object.values(m))if(value instanceof T.Texture)value.dispose();m.dispose();}}});}
 destroy(){this.dead=true;this.cancel();this.disposeTree(this.scene);this.portraits.forEach(t=>t.dispose());this.portalTexture?.dispose();this.renderer.dispose();this.renderer.forceContextLoss();this.renderer.domElement.remove();}
}
function distance3(a:Vec,b:Vec){return Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2]);}
