import { PRODUCT_VERSION } from '../../../packages/presentation/settings';
import { presentationControls } from '../../../packages/presentation/controls';
import { CORES, RECIPES } from "../content";
import { MAP } from "../model";
import { rulesFor } from '../tactics';
import type { DefenseContext } from '../context';
export function mountDefenseTemplate(ctx: DefenseContext): void {
  ctx.root.className = "td-mount";
  ctx.root.innerHTML = `<main class="td-game" aria-labelledby="td-title" data-testid="hanzi-tower-defense">
    <header class="td-header"><div class="td-brand"><span class="td-seal" aria-hidden="true">守</span><div><p data-td-map-title>${rulesFor(ctx.state).title} · ${rulesFor(ctx.state).description}</p><h1 id="td-title">字阵守城 <span class="product-version">v${PRODUCT_VERSION}</span></h1></div><button type="button" data-td-tactics>战术短局</button></div>
      <nav class="td-controls" aria-label="守城操作"><button type="button" data-td-home>返回</button><button type="button" data-td-settings>设置</button><button type="button" data-td-new>新游戏</button><button type="button" data-td-continue>继续游戏</button></nav>
    </header>
    <button type="button" class="td-resume" data-td-resume hidden></button><button type="button" class="td-asset-retry" data-td-art-retry hidden>部分图像未载入，仍可操作 · 重试图像</button><div class="product-guide" data-td-guide ${ctx.visual.guideSeen?'hidden':''}><p>点一枚字核，再点空塔位。两枚可搭配的字核，先看去向，再组合。</p><button type="button" data-td-guide-close>知道了</button></div><div class="td-ribbon" role="region" aria-label="战况与暂停速度"><span data-td-wave></span><span class="td-gate-health">城门 <strong data-td-health>16</strong><span class="td-health-track" aria-hidden="true"><i data-td-health-fill></i></span></span><span data-td-enemies></span><div class="td-live-controls"><button type="button" data-td-speed aria-pressed="false" aria-label="战斗速度1倍，切换为2倍">速度 1×</button><button type="button" data-td-pause class="td-pause" aria-pressed="false">暂停</button></div></div>
    <div class="td-layout"><section class="td-battle-column" aria-label="守城战场">
      <section class="td-challenge-rule" data-td-challenge-rule hidden aria-label="这局的新规则"><b data-td-challenge-title></b><p data-td-challenge-copy></p><div class="td-challenge-controls"><span data-td-deployed-count></span><button type="button" data-td-change-variation hidden>换个变化</button></div></section>
      <div class="td-board" data-td-board><div class="td-canvas" data-td-canvas aria-hidden="true"></div>
        <svg class="td-ranges" data-td-ranges viewBox="0 0 ${MAP.width} ${MAP.height}" preserveAspectRatio="none" aria-hidden="true"></svg>
        <div class="td-gate" data-td-gate aria-hidden="true"><img src="./assets/v1.0/tower/gate.webp" alt=""><span>城</span></div><div class="td-slots" role="group" aria-label="塔位区，方向键选择，Tab 离开">${ctx.SLOTS.map((slot, index) => `<button type="button" class="td-slot" data-slot="${index}" style="left:${slot.x / MAP.width * 100}%;top:${slot.y / MAP.height * 100}%" aria-label="塔位${index + 1} ${slot.name}，空位"><img class="td-tower-art" alt="" hidden><span class="td-slot-glyph">＋</span><small>${index + 1}</small></button>`).join("")}</div>
        <span class="td-road-entry" aria-hidden="true">来路 →</span><div class="td-drops" data-td-drops aria-hidden="true"></div><div class="td-synthesis" data-td-synthesis aria-hidden="true" hidden></div>
      </div>
      <div class="td-range-tools"><span data-td-range-caption>指向或点选字塔，查看攻击范围</span><button type="button" data-td-inspect aria-pressed="false">只看射程</button><button type="button" data-td-all-ranges aria-pressed="false">显示全部射程</button></div>
      <button type="button" class="td-english-notice" data-td-english-notice hidden></button>
      <section class="td-challenge-preview" data-td-challenge-preview hidden aria-label="来路与敌人预告"><h2>先看看谁来</h2><div data-td-challenge-foes></div></section>
      <section class="td-challenge-preparation" data-td-challenge-preparation hidden aria-label="短局准备"><div class="td-section-head" data-td-pack-head><h2>带哪包材料？</h2><span data-td-pack-status></span></div><div class="td-pack-list" role="group" aria-label="材料包，方向键选择，Tab 离开" data-td-packs></div><div class="td-challenge-goals" data-td-challenge-goals hidden><h2>行囊小目标</h2><div role="group" aria-label="行囊目标，方向键选择，Tab 离开" data-td-goals></div><p data-td-goal-status></p></div><p data-td-supply-copy></p></section>
      <details class="td-tactics-brief" data-td-tactics-brief hidden><summary>本短局规则、三波来路与奖励</summary><p data-td-tactics-rules></p><ol data-td-tactics-waves></ol></details>
      <div class="td-wave-action"><p data-td-wave-hint></p><button type="button" class="td-primary" data-td-next>开始这一波</button></div>
      <button type="button" data-td-retry hidden>重整本波</button><section class="td-tactics-summary" data-td-tactics-summary hidden aria-label="最近两次战况"></section>
      <p class="td-feedback" role="status" aria-live="polite" data-td-feedback>${ctx.state.scenarioId?"固定材料已在栏里。先选材料，再点空塔位，也可以先合成。":"火塔已就位。点一枚材料，再点空塔位。也可以先暂停。"}</p>
      <p class="td-boss-status" data-td-boss-status hidden></p><div class="td-enemy-key" aria-label="怪物特点"><span><i class="td-monster-dot td-monster-dot--swarm"></i>团团怪 · 成群</span><span><i class="td-monster-dot td-monster-dot--swift"></i>疾风怪 · 快速</span><span><i class="td-monster-dot td-monster-dot--stone"></i>石甲怪 · 耐打</span></div>
    </section>
    <aside class="td-workbench" aria-label="部署与组合">
      <section class="td-inventory"><div class="td-section-head"><h2>字核材料</h2><span>掉落自动收好</span></div><div class="td-bag-counts" data-td-bag-counts hidden aria-label="背包基础材料"></div><p class="td-bag-goal" data-td-bag-goal hidden></p><div class="td-bag" role="group" aria-label="材料区，方向键选择，Tab 离开" data-td-bag></div><p class="td-bag-empty" data-td-bag-empty hidden>材料都在塔上。点塔也能组合。</p></section>
      <section class="td-english" aria-label="英文共鸣装备"><div class="td-section-head"><h2>共鸣词核</h2><span>完整英文 · 装入同义词塔</span></div><div role="group" aria-label="英文区，方向键选择，Tab 离开" data-td-english-bag></div><p class="td-english-empty" data-td-english-empty>战利品会带来英文词核。拾得后，点英文和字塔，预览再装备。</p>
        <div class="td-equipment-detail" data-td-equipment-detail hidden><p data-td-equipment-copy></p><div class="td-equipment-actions"><button type="button" class="td-primary" data-td-equip hidden>确认装备</button><button type="button" data-td-unequip hidden>卸下到背包</button><button type="button" data-td-confirm-recycle hidden>确认回收并返还英文</button><button type="button" data-td-cancel-equipment>取消共鸣选择</button></div></div>
      </section>
      <section class="td-composer" aria-label="合字与组词"><div class="td-section-head"><h2>组合台</h2><button type="button" class="td-text-button" data-td-clear>取消选择</button></div><div class="td-selection" data-td-selection></div><div class="td-recipe-preview" data-td-preview></div><div class="td-partners" data-td-partners></div><div class="td-fusion-target" data-td-target></div><p class="td-pack-consequence" data-td-pack-consequence hidden></p><div class="td-compose-actions"><button type="button" class="td-primary" data-td-fuse disabled>选两枚字核</button></div>
      <div class="td-item-actions"><button type="button" data-td-stow hidden>收回材料栏</button><button type="button" data-td-recycle hidden>回收修城</button></div></section>
      <details class="td-recipes"><summary>看看能怎样组合</summary><div class="td-recipe-list">${RECIPES.map(r => `<button type="button" data-recipe="${r.id}"><span>${r.inputs.map(k => CORES[k].glyph).join(" ＋ ")} <b>→ ${CORES[r.result].glyph}</b></span><small>${r.structure === "word" ? "组词 · 保留词序" : r.structure === "top-bottom" ? "合字 · 上下" : r.structure === "pyramid" ? "合字 · 上木下林" : "合字 · 左右"}</small></button>`).join("")}</div></details>
      <details class="td-help"><summary>操作小提示</summary><p>点材料或塔上的字，再点空位部署。选两枚字核，先看结构和去向，再确认组合；材料先选谁都可以。点亮的字核能搭配，选满两枚后点另一枚可换搭档。</p><p>英文核是装备，每枚只强化一座同义中文词塔。先点英文再点塔、先点塔再点英文，或把英文拖到塔上，都先预览再确认。材料栏里的完整中文词核也能装备，再部署。还没合出对应词塔，可以先保留英文核。</p><p>战中可以首次装备；卸下、转移和回收带附件的字核，等这一波结束再做。暂停仍在战中。移动或收回字塔，英文会跟随。</p><p>指向或聚焦字塔只查看攻击范围；范围圈表示能选择攻击目标的距离，命中后的爆炸或减速扩散另算。选一枚字核，指向空位可先看覆盖，触屏直接点空位即可部署。</p><p>键盘 Tab 跨区，材料／塔位／英文区内用方向键、Home／End 快选，Enter 或 Space 确认；P 暂停，Esc 取消选择。聚焦塔位即可独立查看射程，触屏可切换“只看射程”。鼠标可拖字核到空位部署，拖到字塔则先预览组合；触屏点两枚字核，再确认即可。</p><p>顶部“速度”可切换 1×／2×，默认 1×。加速会一起加快怪物、攻击和呼援倒计时；暂停时切换速度仍不推进战斗。切图、重置、再守一局或刷新后回到 1×，速度只用于本页。</p><p>刷新回到这一波开始前，已完成波次保留。未完成波次的中英文掉落、装备和材料消耗一起重来。多余材料可回收修补本局城门。</p><p>法术是游戏想象，不是字源。“氵”叫三点水，是非成字部件。</p></details>
      <p class="td-save-note" data-td-save-note></p>
    </aside></div>
    <dialog class="td-dialog" data-td-settings-dialog aria-label="声音与显示设置"><h2>声音与显示</h2><button type="button" data-td-mute aria-pressed="false">静音</button><button type="button" data-td-motion aria-pressed="false">减少动态</button>${presentationControls(ctx.visual)}<details><summary>进度管理</summary><button type="button" data-td-restart>重置进度</button></details><button type="button" data-td-settings-close>返回战场</button></dialog>
    <dialog class="td-dialog" data-td-restart-dialog aria-labelledby="td-restart-title"><h2 id="td-restart-title">重置这张地图的进度？</h2><p><span data-td-reset-copy>这张地图将从第一波重新布阵，发现的配方也会重置。其他地图和旧存档原文保留。</span></p><div><button type="button" data-td-cancel-restart>继续这一局</button><button type="button" class="td-primary" data-td-confirm-restart>重新开始</button></div></dialog>
    <dialog class="td-dialog" data-td-map-dialog aria-labelledby="td-map-dialog-title"><h2 id="td-map-dialog-title">选择地图</h2><p data-td-map-note>每张地图独立继续。未结束的波次会回到波前检查点，材料一起回滚。</p><div class="td-map-list" data-td-map-list></div><button type="button" data-td-map-cancel>返回战场</button></dialog>
    <dialog class="td-dialog td-result" data-td-result aria-labelledby="td-result-title"><span class="td-result-seal" aria-hidden="true">关</span><h2 id="td-result-title"></h2><p data-td-result-copy></p><section class="td-result-objectives" data-td-result-objectives hidden aria-label="守城和行囊结果"></section><div><button type="button" data-td-result-retry hidden>重整本波</button><button type="button" class="td-primary" data-td-replay>再守一局</button><button type="button" data-td-result-change hidden>换个变化</button><button type="button" data-td-result-home>回游戏世界</button></div><p class="td-result-foot">发现的配方已经留下。换条组合路线再试试。</p></dialog>
  </main>`;
}
