import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

interface SourcePair {
  readonly outer: string;
  readonly inner: string;
  readonly result: string;
  readonly pinyin: string;
  readonly words: readonly string[];
}

interface SourceMode {
  readonly outerOptions: readonly string[];
  readonly innerOptions: readonly string[];
  readonly validPairs: readonly SourcePair[];
}

interface SourceSet {
  readonly id: string;
  readonly label: string;
  readonly char: SourceMode;
  readonly word: SourceMode;
}

interface ExistingFreeze {
  readonly sourceHeadSha: string;
  readonly extractedAt: string;
}

const TOOL_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(TOOL_DIR, "../..");
const SOURCE_PATH = "packages/data/learningGames.ts";
const LIBRARY_DIR = resolve(ROOT, "games/hanzi-radical-battle/v2/wheel-workshop/library");
const SOURCE_OUTPUT = resolve(LIBRARY_DIR, "legacy-wheel-source.ts");
const FREEZE_OUTPUT = resolve(LIBRARY_DIR, "legacy-wheel-source-freeze.json");
const CHECK = process.argv.includes("--check");

function git(...args: string[]): string {
  return execFileSync("git", args, { cwd: ROOT, encoding: "utf8" }).trim();
}

function stableStringify(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  if (value && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).sort(([left], [right]) => left.localeCompare(right));
    return `{${entries.map(([key, entry]) => `${JSON.stringify(key)}:${stableStringify(entry)}`).join(",")}}`;
  }
  return JSON.stringify(value);
}

function sha256(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

async function loadHistoricalSets(headSha: string): Promise<readonly SourceSet[]> {
  const source = git("show", `${headSha}:${SOURCE_PATH}`);
  const compiled = ts.transpileModule(source, {
    compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 },
    fileName: SOURCE_PATH,
    reportDiagnostics: true,
  });
  const diagnostics = compiled.diagnostics ?? [];
  if (diagnostics.some((diagnostic) => diagnostic.category === ts.DiagnosticCategory.Error)) {
    throw new Error(`Unable to transpile historical wheel source: ${diagnostics.map((diagnostic) => diagnostic.messageText).join("; ")}`);
  }
  const moduleUrl = `data:text/javascript;base64,${Buffer.from(compiled.outputText).toString("base64")}`;
  const loaded = await import(moduleUrl) as { readonly hanziWheelSets?: readonly SourceSet[] };
  if (!loaded.hanziWheelSets || !Array.isArray(loaded.hanziWheelSets)) throw new Error("Historical source does not export hanziWheelSets");
  return loaded.hanziWheelSets;
}

function withStableIds(sets: readonly SourceSet[]) {
  return sets.map((set) => ({
    id: set.id,
    label: set.label,
    char: {
      outerOptions: [...set.char.outerOptions],
      innerOptions: [...set.char.innerOptions],
      validPairs: set.char.validPairs.map((pair, index) => ({
        legacyId: `${set.id}.char.${String(index).padStart(3, "0")}`,
        outer: pair.outer,
        inner: pair.inner,
        result: pair.result,
        pinyin: pair.pinyin,
        words: [...pair.words],
      })),
    },
    word: {
      outerOptions: [...set.word.outerOptions],
      innerOptions: [...set.word.innerOptions],
      validPairs: set.word.validPairs.map((pair, index) => ({
        legacyId: `${set.id}.word.${String(index).padStart(3, "0")}`,
        outer: pair.outer,
        inner: pair.inner,
        result: pair.result,
        pinyin: pair.pinyin,
        words: [...pair.words],
      })),
    },
  }));
}

function renderSource(sets: ReturnType<typeof withStableIds>, sourceHash: string, sourceHeadSha: string, sourceGitBlobSha: string): string {
  return `// Generated by tools/hanzi-v2-wheel-workshop/extract-legacy-wheel.ts.\n// Preserve byte-significant data and ordering; corrections belong in the canonical audit layer.\nimport type { LegacyWheelSet } from "./legacy-wheel-types";\n\nexport const LEGACY_WHEEL_SOURCE_HEAD_SHA = ${JSON.stringify(sourceHeadSha)} as const;\nexport const LEGACY_WHEEL_SOURCE_GIT_BLOB_SHA = ${JSON.stringify(sourceGitBlobSha)} as const;\nexport const LEGACY_WHEEL_SOURCE_STABLE_JSON_SHA256 = ${JSON.stringify(sourceHash)} as const;\n\nconst LEGACY_WHEEL_SOURCE_DATA = ${JSON.stringify(sets, null, 2)} as const satisfies readonly LegacyWheelSet[];\n\nexport const LEGACY_WHEEL_SOURCE: readonly LegacyWheelSet[] = LEGACY_WHEEL_SOURCE_DATA;\n`;
}

async function main(): Promise<void> {
  const existing = existsSync(FREEZE_OUTPUT) ? JSON.parse(readFileSync(FREEZE_OUTPUT, "utf8")) as ExistingFreeze : null;
  const headSha = CHECK && existing ? existing.sourceHeadSha : git("rev-parse", "HEAD");
  const sets = await loadHistoricalSets(headSha);
  const setIds = sets.map((set) => set.id);
  if (setIds.join("|") !== "p1|p2|p3|p4|p5|p6|j1|j2|j3") throw new Error(`Unexpected source set order: ${setIds.join("|")}`);
  const sourceStableJson = stableStringify(sets);
  const sourceHash = sha256(sourceStableJson);
  const generatedSets = withStableIds(sets);
  const countsBySetAndMode = Object.fromEntries(sets.map((set) => [set.id, { char: set.char.validPairs.length, word: set.word.validPairs.length }]));
  const totalCharRecords = sets.reduce((sum, set) => sum + set.char.validPairs.length, 0);
  const totalWordRecords = sets.reduce((sum, set) => sum + set.word.validPairs.length, 0);
  const freeze = {
    sourcePath: SOURCE_PATH,
    sourceGitBlobSha: git("rev-parse", `${headSha}:${SOURCE_PATH}`),
    sourceHeadSha: headSha,
    setIds,
    setLabels: sets.map((set) => set.label),
    countsBySetAndMode,
    totalCharRecords,
    totalWordRecords,
    totalRecords: totalCharRecords + totalWordRecords,
    stableJsonSha256: sourceHash,
    fieldInventory: [
      "set.id",
      "set.label",
      "set.char.outerOptions[]",
      "set.char.innerOptions[]",
      "set.char.validPairs[].outer",
      "set.char.validPairs[].inner",
      "set.char.validPairs[].result",
      "set.char.validPairs[].pinyin",
      "set.char.validPairs[].words[]",
      "set.word.outerOptions[]",
      "set.word.innerOptions[]",
      "set.word.validPairs[].outer",
      "set.word.validPairs[].inner",
      "set.word.validPairs[].result",
      "set.word.validPairs[].pinyin",
      "set.word.validPairs[].words[]",
    ],
    extractedAt: existing?.extractedAt ?? new Date().toISOString(),
  };
  const expectedSource = renderSource(generatedSets, sourceHash, freeze.sourceHeadSha, freeze.sourceGitBlobSha);
  const expectedFreeze = `${JSON.stringify(freeze, null, 2)}\n`;

  if (CHECK) {
    const actualSource = readFileSync(SOURCE_OUTPUT, "utf8");
    const actualFreeze = readFileSync(FREEZE_OUTPUT, "utf8");
    if (actualSource !== expectedSource || actualFreeze !== expectedFreeze) throw new Error("Legacy wheel source freeze is stale or no longer byte-faithful");
    process.stdout.write(`${JSON.stringify({ result: "PASS", sourceHeadSha: headSha, sourceGitBlobSha: freeze.sourceGitBlobSha, stableJsonSha256: sourceHash, totalCharRecords, totalWordRecords, totalRecords: totalCharRecords + totalWordRecords })}\n`);
    return;
  }

  writeFileSync(SOURCE_OUTPUT, expectedSource, "utf8");
  writeFileSync(FREEZE_OUTPUT, expectedFreeze, "utf8");
  process.stdout.write(`${JSON.stringify({ result: "GENERATED", sourceHeadSha: headSha, sourceGitBlobSha: freeze.sourceGitBlobSha, stableJsonSha256: sourceHash, totalCharRecords, totalWordRecords, totalRecords: totalCharRecords + totalWordRecords })}\n`);
}

await main();
