import { expect, test } from '@playwright/test';

test('home entry, word lookup, uppercase/lowercase stroke steps and return work', async ({ page }, info) => {
  const activate = async (selector: string): Promise<void> => {
    const target = page.locator(selector);
    if (info.project.name.includes('touch')) await target.tap(); else await target.click();
  };
  const errors: string[] = [];
  const external: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (new URL(request.url()).origin !== 'http://127.0.0.1:5175') external.push(request.url()); });
  await page.goto('?world=my-game-world');
  await activate('[data-world-english-link]');
  await expect(page).toHaveURL(/play=english-study/);
  await expect(page.locator('[data-testid=english-study]')).toHaveAttribute('data-word-count', '10547');
  await expect(page.locator('[data-testid=english-study]')).toHaveAttribute('data-letter-count', '52');
  await page.locator('#es-input').fill('cat dog cat');
  await activate('[data-es-search] button');
  await expect(page.locator('[data-es-results] button')).toHaveCount(3);
  if (info.project.name.includes('touch')) await page.locator('[data-es-results] button').first().tap(); else await page.locator('[data-es-results] button').first().click();
  await expect(page.locator('[data-es-word-dialog]')).toBeVisible();
  await expect(page.locator('[data-es-zh]')).toHaveText('猫');
  await activate('[data-es-speak]');
  await expect(page.locator('[data-es-speech-status]')).toContainText('系统');
  await page.locator('[data-es-favorite]').click();
  await expect(page.locator('[data-es-favorite]')).toHaveAttribute('aria-pressed', 'true');
  if (info.project.name.includes('touch')) await page.locator('[data-es-word-letters] button').first().tap(); else await page.locator('[data-es-word-letters] button').first().click();
  await expect(page.locator('[data-es-letter-dialog]')).toBeVisible();
  await expect(page.locator('[data-es-stroke-status]')).toContainText('第 1 / 1 笔');
  await activate('[data-es-upper]');
  await expect(page.locator('[data-es-stroke-status]')).toContainText('C：第 1 / 1 笔');
  await activate('[data-es-lower]');
  await activate('[data-es-stroke-all]');
  await expect(page.locator('[data-es-stroke-status]')).toContainText('完整字母');
  await page.locator('[data-es-letter-close]').click();
  await expect(page.locator('[data-es-word-dialog]')).toBeVisible();
  await page.locator('[data-es-word-close]').click();
  await expect(page.locator('[data-es-favorites]')).toContainText('cat');
  await page.locator('#es-input').fill('computer');
  await page.locator('[data-es-search] button').click();
  await page.locator('[data-es-results] button').first().click();
  await expect(page.locator('[data-es-zh]')).toContainText('电脑');
  await expect(page.locator('[data-es-definition]')).toContainText('ECDICT');
  await page.locator('[data-es-word-close]').click();
  await page.locator('[data-es-return]').click();
  await expect(page.locator('[data-world-english-link]')).toBeFocused();
  expect(external).toEqual([]);
  expect(errors).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
});

test('unknown words stay local, alphabet navigation works by keyboard and dialogs restore focus', async ({ page }) => {
  await page.goto('?play=english-study');
  await page.locator('#es-input').fill('unicorn');
  await page.locator('#es-input').press('Enter');
  const result = page.locator('[data-es-results] button').first();
  await expect(result).toBeFocused();
  await result.press('Enter');
  await expect(page.locator('[data-es-zh]')).toContainText('没有收录');
  await expect(page.locator('[data-es-speak]')).toBeDisabled();
  await expect(page.locator('[data-es-favorite]')).toBeHidden();
  await page.locator('[data-es-word-dialog]').press('Escape');
  await expect(result).toBeFocused();
  const letters = page.locator('[data-es-alphabet] button');
  await letters.first().focus();
  await letters.first().press('ArrowRight');
  await expect(letters.nth(1)).toBeFocused();
  await letters.nth(1).press('Enter');
  await expect(page.locator('#es-letter-title')).toContainText('b');
  await page.locator('[data-es-stroke-next]').click();
  await expect(page.locator('[data-es-stroke-status]')).toContainText('第 2 / 2 笔');
  await page.locator('[data-es-letter-dialog]').press('Escape');
  await expect(letters.nth(1)).toBeFocused();
  expect(await page.evaluate(() => localStorage.getItem('family-games/english-study/v1'))).toBeNull();
  await page.locator('#es-input').fill('I');
  await page.locator('#es-input').press('Enter');
  await page.locator('[data-es-results] button').first().press('Enter');
  await expect(page.locator('#es-word-title')).toHaveText('I');
  await expect(page.locator('[data-es-word-letters] button')).toHaveText('I');
});
