export const WHEEL_ISSUE_CODES = [
  "CIRCULAR_DECOMPOSITION",
  "RESULT_USED_AS_COMPONENT",
  "NON_GLYPH_COMPONENT_LABEL",
  "WRONG_COMPONENT_FORM",
  "WRONG_COMPONENT_ORDER",
  "WRONG_STRUCTURE",
  "UNKNOWN_STRUCTURE",
  "PINYIN_MISMATCH",
  "FIXED_CONTEXT_POLYPHONE",
  "WORD_FRAGMENT",
  "NON_STANDALONE_LEXEME",
  "MEANING_MISMATCH",
  "GRADE_ALIGNMENT_UNVERIFIED",
  "AMBIGUOUS_HAND",
  "MISSING_SOURCE",
  "FONT_RENDER_RISK",
  "DUPLICATE_RECORD",
] as const;

export type WheelIssueCode = (typeof WHEEL_ISSUE_CODES)[number];
