import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {disposeToy,fitCamera,toyThumbnail} from './toy-view';
import {FROZEN_IDS,frozenGroup,type FrozenPiece,type FrozenState,type FrozenMotion} from './frozen-model';
const v=(p:number[])=>new T.Vector3(p[0],p[2],-p[1]);
export class FrozenScene{
 readonly scene=new T.Scene();readonly camera=new T.OrthographicCamera();readonly renderer:T.WebGLRenderer;readonly reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 asset?:T.Group;pieces=new Map<FrozenPiece,T.Object3D>();homes=new Map<T.Object3D,T.Vector3>();private ray=new T.Raycaster();private dead=false;private width=1;private height=1;private center=new T.Vector3(0,1.4,0);private half=9;angle=.2;pitch=.85;zoom=1;view='all';
 private mixer?:T.AnimationMixer;private actions=new Map<string,T.AnimationAction>();private current=new Set<string>();private snow:T.Points;private trail:T.Line;private trailPoints:T.Vector3[]=[];private lastSkate=0;private landing=new Map<FrozenPiece,number>();private lastCast:string|null=null;private heading=0;private elsaTravel=0;private spark=new T.Mesh(new T.IcosahedronGeometry(.09,0),new T.MeshBasicMaterial({color:0xb4efff}));private destination=new T.Mesh(new T.RingGeometry(.56,.65,32),new T.MeshBasicMaterial({color:0xd9932e,side:T.DoubleSide}));
 constructor(readonly host:HTMLElement){
  this.renderer=new T.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.04;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFShadowMap;host.append(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-hidden','true');
  this.scene.add(new T.HemisphereLight(0xddefff,0xa07850,3));const sun=new T.DirectionalLight(0xfff1dc,3);sun.position.set(-8,16,9);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12,far:60});sun.shadow.normalBias=.035;this.scene.add(sun);const fill=new T.DirectionalLight(0xc5c6ff,1.8);fill.position.set(8,8,-8);this.scene.add(fill);
  const positions=new Float32Array(120*3);this.snow=new T.Points(new T.BufferGeometry().setAttribute('position',new T.BufferAttribute(positions,3)),new T.PointsMaterial({color:0xffffff,size:.055,transparent:true,opacity:.85,depthWrite:false}));this.scene.add(this.snow);this.snow.visible=false;
  this.trail=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:0xe2fbff}));this.scene.add(this.trail,this.spark,this.destination);this.spark.visible=false;this.destination.rotation.x=-Math.PI/2;this.destination.visible=false;
 }
 async load(){const g=await new GLTFLoader().loadAsync('./assets/world-in-a-box/frozen/frozen-elsa-playground.glb');if(this.dead){disposeToy(g.scene);return;}this.asset=g.scene;this.scene.add(g.scene);this.mixer=new T.AnimationMixer(g.scene);for(const clip of g.animations)this.actions.set(clip.name,this.mixer.clipAction(clip));
  g.scene.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true;}this.homes.set(o,o.position.clone());});for(const id of FROZEN_IDS)this.pieces.set(id,this.node('piece_'+id)!);this.resize();this.go('all');
 }
 node(name:string){return this.asset?.getObjectByName(name);}
 resize(){this.width=this.host.clientWidth;this.height=this.host.clientHeight;this.renderer.setSize(this.width,this.height);this.cameraUpdate();}
 cameraUpdate(){fitCamera(this.camera,this.center,this.half,this.width/this.height,this.angle,this.pitch,this.zoom);this.host.dataset.camera=JSON.stringify({view:this.view,angle:this.angle,pitch:this.pitch,zoom:this.zoom});}
 go(view:string){this.view=view;this.node('camera_'+view)?.getWorldPosition(this.center);this.half=view==='all'?8.9:view==='palace'?4.2:5.2;this.angle=.18;this.pitch=view==='palace'?.65:.87;this.zoom=1;this.cameraUpdate();}
 turn(d:number){this.angle+=d;this.cameraUpdate();}tilt(d:number){this.pitch=T.MathUtils.clamp(this.pitch+d,.3,1.4);this.cameraUpdate();}zoomBy(d:number){this.zoom=T.MathUtils.clamp(this.zoom+d,.7,2.1);this.cameraUpdate();}
 land(id:FrozenPiece){this.landing.set(id,0);}
 reset(){this.landing.clear();this.trailPoints=[];this.lastSkate=0;this.lastCast=null;this.heading=0;this.elsaTravel=0;this.mixer?.stopAllAction();this.current.clear();for(const [o,p] of this.homes)o.position.copy(p);this.node('elsa')?.rotation.set(0,0,0);this.go('all');}
 private meshes(){const out:T.Object3D[]=[];this.asset?.traverseVisible(o=>{let p:T.Object3D|null=o,decor=false;while(p){if(p.userData.decorative)decor=true;p=p.parent;}if(o instanceof T.Mesh&&!decor)out.push(o);});return out;}
 pick(x:number,y:number):string|null{const r=this.host.getBoundingClientRect();this.ray.setFromCamera(new T.Vector2((x-r.x)/r.width*2-1,1-(y-r.y)/r.height*2),this.camera);let o:T.Object3D|null=this.ray.intersectObjects(this.meshes(),false)[0]?.object??null;while(o){if(o.name.startsWith('slot_'))return o.name.slice(5);if(o.name.startsWith('piece_'))return o.name.slice(6);if(o.name.startsWith('touch_'))return o.name.slice(6);if(o.name==='elsa')return 'magic_snow';o=o.parent;}return null;}
 target(id:string){const node=this.node(id.startsWith('magic_')?'touch_'+id:'anchor_'+id);if(!node)return{x:0,y:0,visible:false};const p=node.getWorldPosition(new T.Vector3()),ndc=p.clone().project(this.camera);this.ray.setFromCamera(new T.Vector2(ndc.x,ndc.y),this.camera);const hit=this.ray.intersectObjects(this.meshes(),false)[0];let owns=false;for(let o:T.Object3D|null=hit?.object??null;o;o=o.parent)if(o.name==='slot_'+id||o.name==='piece_'+id||o.name==='touch_'+id||id==='magic_snow'&&o.name==='elsa')owns=true;return{x:(ndc.x+1)*this.width/2,y:(1-ndc.y)*this.height/2,visible:Math.abs(ndc.x)<.85&&Math.abs(ndc.y)<.82&&(!hit||owns||hit.distance>=this.ray.ray.origin.distanceTo(p)-.08)};}
 reveal(id:FrozenPiece,usable:()=>boolean){this.go(['lake','town','lake','palace'][frozenGroup(id)]);this.node('anchor_'+id)?.getWorldPosition(this.center);this.half=3.6;for(const pitch of [.9,1.25,.55])for(const angle of [.18,1.7,3.3,4.8]){this.pitch=pitch;this.angle=angle;this.cameraUpdate();this.asset?.updateMatrixWorld(true);if(this.target(id).visible&&usable())return true;}return false;}
 thumbnail(id:FrozenPiece,angle=.2){return toyThumbnail(this.renderer,this.pieces.get(id),{w:this.width,h:this.height},angle);}
 private animation(names:string[],dt:number){const wanted=new Set<string>();for(const [name,a] of this.actions)if(names.some(n=>name.includes(n))){wanted.add(name);if(!this.current.has(name))a.reset().fadeIn(.15).play();}for(const name of this.current)if(!wanted.has(name))this.actions.get(name)?.fadeOut(.15);this.current=wanted;this.mixer?.update(dt);}
 private route(m:FrozenMotion,t:number){
  const points=this.node('frozen_routes')!.userData[m.ride.route] as number[][];
  // Explicit bridge parameter intervals agree with the safety reducer.
  const times=m.ride.route==='palace'?[0,.22,.32,.38,.73,.84,1]:points.map((_,i)=>i/(points.length-1));let i=times.findIndex((end,j)=>j>0&&t<=end);if(i<1)i=times.length-1;const f=T.MathUtils.clamp((t-times[i-1])/(times[i]-times[i-1]),0,1);return v(points[i-1]).lerp(v(points[i]),f);
 }
 private ahead(m:FrozenMotion,distance:number){const points=(this.node('frozen_routes')!.userData[m.ride.route] as number[][]).map(v),times=m.ride.route==='palace'?[0,.22,.32,.38,.73,.84,1]:points.map((_,i)=>i/(points.length-1)),dir=m.ride.direction;let p=this.route(m,m.ride.t),i=dir>0?times.findIndex(t=>t>m.ride.t):times.reduce((found,t,j)=>t<m.ride.t?j:found,-1);if(i<0&&dir>0)i=points.length;while(i>=0&&i<points.length){const delta=points[i].clone().sub(p),length=delta.length();if(length>=distance)return p.addScaledVector(delta,distance/Math.max(length,.00001));distance-=length;p=points[i].clone();i+=dir;}const tangent=dir>0?points.at(-1)!.clone().sub(points.at(-2)!):points[0].clone().sub(points[1]);return p.addScaledVector(tangent.normalize(),distance);}

 frame(s:FrozenState,m:FrozenMotion,dt:number){if(!this.asset)return;
  const names:string[]=[];if(m.cast)names.push('elsa_cast');if(m.wave>0||m.snow>0&&s.placed.includes('olaf'))names.push('olaf_wave');if(m.ride.running)names.push('sven_walk');if(m.ride.t===1&&m.ride.anna&&this.elsaTravel===1)names.push('anna_wave','elsa_wave');
  this.elsaTravel=m.elsaTrip;if(this.elsaTravel>0&&this.elsaTravel<1&&!m.cast)names.push('elsa_walk');this.animation(names,this.reduced?0:dt);
  for(const id of FROZEN_IDS){const p=this.pieces.get(id)!;p.visible=s.placed.includes(id);this.node('slot_'+id)!.visible=!p.visible;p.position.copy(this.homes.get(p)!);p.rotation.set(0,0,0);if(this.landing.has(id)){const t=this.landing.get(id)!+dt;this.landing.set(id,t);p.position.y+=this.reduced?0:Math.max(0,1-t/.32)*.35;if(t>=.32)this.landing.delete(id);}}
  for(let i=0;i<12;i++){const seg=this.node('bridge_segment_'+i)!;const a=T.MathUtils.clamp(m.bridgeAmount*12-i,0,1);seg.visible=a>0;seg.scale.set(1,Math.max(.01,a),1);}
  const rink=this.node('magic_rink')!;rink.visible=m.rinkAmount>0;rink.scale.set(1,1,Math.max(.01,m.rinkAmount));rink.position.z=this.homes.get(rink)!.z+1.75*(1-m.rinkAmount);
  const elsa=this.node('elsa')!,home=this.homes.get(elsa)!,previousElsa=elsa.position.clone();elsa.position.copy(home);
  if(this.elsaTravel>0){const points=[home,v([1,-4.5,.17]),v([4.4,-2,.17]),v([3,.8,.43]),v([3,.95,.43]),v([3,3.35,1.53]),v([2,3.5,1.53]),v([.7,3.2,1.53])];const n=this.elsaTravel*(points.length-1),i=Math.min(points.length-2,Math.floor(n));elsa.position.copy(points[i]).lerp(points[i+1],n-i);}
  let elsaAngle=elsa.rotation.y;if(m.cast){const target=this.node('touch_magic_'+m.cast)!.getWorldPosition(new T.Vector3());const d=target.sub(elsa.position);elsaAngle=Math.atan2(d.x,d.z);}else if(this.elsaTravel>0&&this.elsaTravel<1){const direction=elsa.position.clone().sub(previousElsa);if(Math.hypot(direction.x,direction.z)>.00001)elsaAngle=Math.atan2(direction.x,direction.z);if(!this.reduced)elsa.position.y+=Math.sin(this.elsaTravel*145)*.025;}
  const turn=Math.atan2(Math.sin(elsaAngle-elsa.rotation.y),Math.cos(elsaAngle-elsa.rotation.y));elsa.rotation.y+=Math.sign(turn)*Math.min(Math.abs(turn),dt*3.5);const cloak=this.node('elsa_body_cape');if(cloak)cloak.rotation.z=!this.reduced&&this.elsaTravel>0&&this.elsaTravel<1?Math.sin(this.elsaTravel*145)*.035:0;
  const r=m.ride,car=this.pieces.get('sleigh')!;this.destination.visible=s.placed.includes('sleigh')&&(r.running||r.t!==r.destination);this.destination.position.copy(this.route(m,r.destination)).add(new T.Vector3(0,.08,0));if(r.t>0||r.running||r.anna){const p=this.route(m,r.t),next=this.route(m,T.MathUtils.clamp(r.t+r.direction*.001,0,1));const tangent=next.sub(p);if(tangent.length()<.00001)tangent.copy(p).sub(this.route(m,T.MathUtils.clamp(r.t-r.direction*.001,0,1)));const desired=Math.atan2(tangent.x,tangent.z);const delta=Math.atan2(Math.sin(desired-this.heading),Math.cos(desired-this.heading));this.heading+=Math.sign(delta)*Math.min(Math.abs(delta),dt*3);const angle=this.heading;car.position.copy(p);car.rotation.y=angle;car.rotation.x=-Math.atan2(tangent.y,Math.hypot(tangent.x,tangent.z));
   const offset=(x:number,y:number,z:number)=>new T.Vector3(x,y,z).applyQuaternion(car.quaternion).add(p);
   const deer=this.pieces.get('sven')!;deer.position.copy(this.ahead(m,1.2));deer.rotation.y=angle;
   for(const id of ['kristoff','anna'] as const)if(s.placed.includes(id)&&(id==='kristoff'||r.anna)){const actor=this.pieces.get(id)!;actor.position.copy(offset(id==='anna'?.20:-.20,.30,id==='anna'?.18:-.20));actor.rotation.y=angle;for(const side of [-1,1]){const leg=this.node(id+'_leg_'+side);if(leg)leg.rotation.x=-1.3;}}
   if(m.follow){this.center.copy(p).add(new T.Vector3(0,1,0));this.half=4;this.cameraUpdate();}
  }
  for(const id of ['kristoff','anna'] as const){const seated=(r.t>0||r.running||r.anna)&&(id==='kristoff'||r.anna);const body=this.node(id+'_body');if(body)body.position.y=this.homes.get(body)!.y-(seated?.48:0);for(const suffix of ['dress','cape']){const garment=this.node(id+'_body_'+suffix);if(garment instanceof T.Mesh&&garment.morphTargetInfluences)garment.morphTargetInfluences[0]=seated?1:0;}if(!seated)for(const side of [-1,1]){const leg=this.node(id+'_leg_'+side);if(leg)leg.rotation.x=0;}}
  const olaf=this.pieces.get('olaf')!,sk=m.skate;
  if(sk.entry>0){const x=sk.pattern==='eight'?Math.sin(sk.t)*1.7:Math.cos(sk.t)*1.7,z=sk.pattern==='eight'?Math.sin(sk.t*2)*.65:Math.sin(sk.t)*1.1;const p=new T.Vector3(.35+x,.33,2+z);olaf.position.lerp(p,sk.entry);olaf.rotation.y=-sk.t;if(dt&&sk.t!==this.lastSkate){this.trailPoints.push(olaf.position.clone());if(this.trailPoints.length>220)this.trailPoints.shift();this.lastSkate=sk.t;}}
  else this.trailPoints=[];
  if(m.bridgeWalk>0){const start=this.homes.get(olaf)!,near=v([3,.65,.54]),far=v([3,3.4,1.55]);if(m.bridgeWalk<.45)olaf.position.copy(start).lerp(near,m.bridgeWalk/.45);else olaf.position.copy(near).lerp(far,(m.bridgeWalk-.45)/.55);}
  this.trail.geometry.dispose();this.trail.geometry=new T.BufferGeometry().setFromPoints(this.trailPoints);this.trail.visible=sk.entry>0;
  const head=this.node('olaf_head');if(head&&m.wave>0&&!this.reduced)head.position.y=this.homes.get(head)!.y+Math.sin((3-m.wave)*Math.PI)*.14;
  for(const side of [-1,1])this.node('gate_leaf_'+side)!.rotation.y=m.door?side*1.1:0;
  this.node('chandelier_pivot')!.rotation.x=m.chandelier>0&&!this.reduced?Math.sin(m.chandelier*4)*.12*m.chandelier/4:0;
  this.snow.visible=m.snow>0;const a=this.snow.geometry.getAttribute('position') as T.BufferAttribute;
  for(let i=0;i<a.count;i++){const t=10-m.snow,phase=i*.73+t*(this.reduced?.04:.8);a.setXYZ(i,-1.6+Math.cos(phase)*(i%13)/8, .4+(i*.137+t*.4)%3,4+Math.sin(phase)*(i%11)/9);}a.needsUpdate=true;
  this.asset.updateMatrixWorld(true);this.spark.visible=!!m.cast;if(m.cast)this.node('elsa_hand')?.getWorldPosition(this.spark.position);this.renderer.render(this.scene,this.camera);
 }
 diagnostics(){return{calls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles,memory:this.renderer.info.memory,clips:[...this.actions.keys()],playing:[...this.current]};}
 destroy(){this.dead=true;this.mixer?.stopAllAction();disposeToy(this.scene);this.snow.geometry.dispose();(this.snow.material as T.Material).dispose();this.trail.geometry.dispose();(this.trail.material as T.Material).dispose();this.renderer.dispose();this.renderer.forceContextLoss();this.renderer.domElement.remove();}
}
