async driver=>{
 const browser=driver.context().browser(),ctx=await browser.newContext({viewport:{width:1280,height:960},hasTouch:true}),p=await ctx.newPage(),checks=[],errors=[];
 const check=(v,m)=>{if(!v)throw Error(m);checks.push(m);},press=s=>p.locator(s).click(),state=()=>p.locator('.dc-mount').evaluate(e=>({...e.dataset}));p.on('pageerror',e=>errors.push(String(e)));p.setDefaultTimeout(12000);
 await ctx.addInitScript(()=>{window.qa={created:0,lost:0,audioCreated:0,audioClosed:0,frames:0};const pending=new Set(),raf=window.requestAnimationFrame.bind(window),cancel=window.cancelAnimationFrame.bind(window);window.requestAnimationFrame=cb=>{const id=raf(t=>{pending.delete(id);qa.frames=pending.size;cb(t);});pending.add(id);qa.frames=pending.size;return id;};window.cancelAnimationFrame=id=>{pending.delete(id);qa.frames=pending.size;cancel(id);};const NativeAudio=window.AudioContext;window.AudioContext=new Proxy(NativeAudio,{construct(target,args){qa.audioCreated++;return Reflect.construct(target,args);}});const proto=HTMLCanvasElement.prototype,original=proto.getContext;const contexts=new WeakSet();proto.getContext=function(...args){const c=original.apply(this,args);if(c&&/webgl/.test(args[0])&&!contexts.has(c)){contexts.add(c);window.qa.created++;const ext=c.getExtension.bind(c);c.getExtension=function(name){const e=ext(name);if(name==='WEBGL_lose_context'&&e&&!e.qa){e.qa=true;const lose=e.loseContext.bind(e);e.loseContext=()=>{window.qa.lost++;lose();};}return e;};}return c;};const close=AudioContext.prototype.close;AudioContext.prototype.close=function(){window.qa.audioClosed++;return close.call(this);};});
 const ready=()=>p.locator('[data-ready=true]').waitFor();
 async function choose(group,id){await press(`[data-group=${group}]`);while(await p.locator('[data-action=prev]').isEnabled())await press('[data-action=prev]');if(!await p.locator(`[data-piece=${id}]`).isVisible())await press('[data-action=next]');await press(`[data-piece=${id}]`);await press('[data-action=hint]');}
 async function place(group,id){await choose(group,id);await press(`[data-slot=${id}]`);await p.waitForTimeout(350);}
 async function reset(){await press('[data-action=reset]');await press('[data-action=confirm-reset]');}
 try{
 await p.goto('http://127.0.0.1:5175/?play=world-in-a-box&scene=dresden-river-campus');await ready();
 await choose('river','paddle_steamer');let box=await p.locator('[data-slot=paddle_steamer]').boundingBox();
 await p.mouse.move(box.x+22,box.y+22);await p.mouse.down();await p.mouse.move(box.x+80,box.y+80,{steps:5});await p.mouse.up();check(!(await state()).placed,'moving off pressed target does not place');
 await p.locator('[data-slot=paddle_steamer]').scrollIntoViewIfNeeded();box=await p.locator('[data-slot=paddle_steamer]').boundingBox();const cdp=await ctx.newCDPSession(p);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+22,y:box.y+22,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});check(!(await state()).placed,'native touchCancel does not place');
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+22,y:box.y+22,id:1},{x:box.x+80,y:box.y+22,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});check(!(await state()).placed,'multi-touch does not place');
 await p.mouse.move(box.x+22,box.y+22);await p.mouse.down();await p.mouse.wheel(0,120);await p.waitForTimeout(250);await p.mouse.up();check(!(await state()).placed,'wheel cancels pressed target');
 await cdp.send('Emulation.setFocusEmulationEnabled',{enabled:false});await p.bringToFront();await p.locator('[data-slot=paddle_steamer]').scrollIntoViewIfNeeded();box=await p.locator('[data-slot=paddle_steamer]').boundingBox();await p.mouse.move(box.x+22,box.y+22);await p.mouse.down();const other=await ctx.newPage();await other.goto('about:blank');await other.bringToFront();await p.waitForTimeout(200);await p.bringToFront();await p.mouse.up();await other.close();check(!(await state()).placed,'real window focus loss cancels gesture');await cdp.detach();
 await p.locator('[data-slot=paddle_steamer]').dblclick();check((await state()).placed==='paddle_steamer','double click places one logical piece');await press('[data-action=undo]');await p.waitForTimeout(450);check(!(await state()).placed,'undo during landing prevents resurrection');
 await choose('river','paddle_steamer');box=await p.locator('[data-slot=paddle_steamer]').boundingBox();await p.keyboard.press('Escape');const source=await p.locator('[data-piece=paddle_steamer]').boundingBox();await p.mouse.move(source.x+source.width/2,source.y+source.height/2);await p.mouse.down();await p.mouse.move(source.x-20,source.y+source.height/2,{steps:3});box=await p.locator('[data-slot=paddle_steamer]').boundingBox();await p.mouse.move(box.x+22,box.y+22,{steps:18});await p.mouse.up();check((await state()).placed==='paddle_steamer','drag supplement uses same placement operation');await p.waitForTimeout(350);
 await press('[data-action=boat-start]');await p.waitForTimeout(400);await press('[data-action=undo]');check(!(await state()).placed,'removing moving boat cancels motion');await p.waitForTimeout(350);check((await state()).boatRunning==='false','removed boat remains stopped');
 await place('river','paddle_steamer');await place('river','river_pier');await press('[data-action=boat-dock]');await p.waitForFunction(()=>document.querySelector('.dc-mount').dataset.boatRunning==='false'&&Math.abs(+document.querySelector('.wb-canvas').dataset.boat.split(',')[0]-5.8)<.0001);await press('[data-action=undo]');check(!(await state()).placed.includes('river_pier'),'remove occupied pier');await p.waitForTimeout(500);check(Math.abs(+(await p.locator('.wb-canvas').getAttribute('data-boat')).split(',')[0]+6.6)<.001,'boat returns to safe waiting water');
 await place('campus','slub_skylight');await place('campus','slub_surface');await press('[data-action=section]');await press('[data-action=undo]');await p.waitForFunction(()=>document.querySelector('.wb-canvas').dataset.section==='0');check((await state()).section==='false'&&(await state()).placed.includes('slub_skylight'),'undo during section safely closes and retains skylight');await place('campus','slub_surface');
 for(let i=0;i<6;i++)await press('[data-action=section]');await p.waitForFunction(()=>document.querySelector('.dc-mount').dataset.section==='false');check((await state()).section==='false','rapid reversible section operation');
 await place('river','yellow_tram');await press('.dc-destinations [data-destination=campus]');await press('[data-action=tram-start]');await p.waitForTimeout(300);
 const focus=await ctx.newCDPSession(p);await focus.send('Emulation.setFocusEmulationEnabled',{enabled:false});const bg=await ctx.newPage();await bg.goto('about:blank');await bg.bringToFront();await p.waitForTimeout(600);await p.bringToFront();await bg.close();await p.waitForTimeout(100);check((await state()).tramRunning==='false','background/focus loss pauses traffic');const position=await p.locator('.wb-canvas').getAttribute('data-tram');await p.waitForTimeout(300);check(position===await p.locator('.wb-canvas').getAttribute('data-tram'),'return has no large dt jump');await focus.detach();
 const citySave=await p.evaluate(()=>localStorage.getItem('family-games/world-in-a-box/dresden-river-campus-v2'));
 for(let i=0;i<6;i++){await press('[data-action=boxes]');await press('[data-box=window-breeze]');await ready();await press('[data-action=boxes]');await press('[data-box=dresden-river-campus]');await ready();}
 check(await p.locator('canvas').count()===1,'six switches leave one canvas');check(await p.evaluate(()=>qa.created-qa.lost)===1,'six switches release every obsolete GPU context');check(await p.evaluate(()=>localStorage.getItem('family-games/world-in-a-box/dresden-river-campus-v2'))===citySave,'switching does not mutate city save');check(await p.evaluate(()=>qa.frames===1),'six switches leave exactly one application RAF');check(await p.evaluate(()=>qa.audioCreated>0&&qa.audioCreated-qa.audioClosed<=1),'six switches leave at most one live audio context');
 // Delay the old scene response and switch before it finishes; late GLB must not attach.
 await ctx.route('**/window-breeze.glb',async route=>{await p.waitForTimeout(900);await route.continue().catch(()=>{});});await press('[data-action=boxes]');await press('[data-box=window-breeze]');await p.locator('[data-action=boxes]').waitFor();await press('[data-action=boxes]');await press('[data-box=dresden-river-campus]');await ready();await p.waitForTimeout(1100);check(await p.locator('canvas').count()===1&&await p.evaluate(()=>qa.created-qa.lost)===1,'late old GLB cannot attach to new scene');
 await p.goto('http://127.0.0.1:5175/?play=world-in-a-box&scene=unknown');await ready();check(await p.locator('#wb-title').innerText()==='窗边有风','unknown scene clearly falls back');check(await p.locator('.wb-subtitle').first().innerText().then(t=>t.includes('没有收录')),'fallback message visible');
 check(!errors.length,'no uncaught browser errors');return{result:'PASS',checks,errors};
 }catch(e){await p.screenshot({path:'tmp/tasks/world-box-step02/edges-failure.png',fullPage:true});return{result:'AUTO_REVISE',checks,error:String(e),errors};}finally{await ctx.close();}
}
