async driver=>{
 const browser=driver.context().browser(),checks=[],rows=[];const assert=(v,msg)=>{if(!v)throw Error(msg);checks.push(msg);};
 async function context(fault=false){const c=await browser.newContext({viewport:{width:1200,height:900}});await c.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:5175/')?r.continue():r.abort());if(fault)await c.addInitScript(()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.includes('frozen-elsa-playground'))throw new DOMException('isolated synthetic storage fault','QuotaExceededError');return set.call(this,k,v);};});return c;}
 const c=await context(),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const press=s=>p.locator(s).click(),ready=()=>p.locator('[data-ready=true]').waitFor();
 async function frozen(){await press('[data-action=boxes]');await press('[data-box=frozen-elsa-playground]');await ready();}
 try{
 await p.goto('http://127.0.0.1:5175/Game-Codex/?play=world-in-a-box');await ready();for(let i=0;i<3&&!await p.locator('[data-piece=book]').isVisible();i++)await press('[data-action=next]');await press('[data-piece=book]');await press('[data-action=hint]');await press('[data-slot=book]');const legacy=await p.evaluate(()=>localStorage.getItem('family-games/world-in-a-box/v1'));
 const prior=await p.evaluate(()=>performance.getEntriesByType('resource').filter(x=>x.name.includes('/frozen')).map(x=>x.name));assert(!prior.length,'window entry does not load frozen model/audio');
 await frozen();assert(p.url().includes('/Game-Codex/'),'subpath retained');await press('[data-magic=bridge]');await press('[data-action=reset]');await press('[data-action=confirm-reset]');await p.waitForTimeout(3300);assert(await p.locator('.frozen-mount').getAttribute('data-bridge')==='off','reset during casting cancels late bridge growth');assert(await p.evaluate(()=>localStorage.getItem('family-games/world-in-a-box/v1'))===legacy,'old first-box bytes preserved');
 await press('[data-action=help]');await press('[data-group="0"]');await press('[data-piece=olaf]');await press('[data-slot=olaf]');await press('[data-view=all]');await press('[data-magic=bridge]');await p.waitForFunction(()=>document.querySelector('.frozen-mount').dataset.bridge==='ready');await press('[data-action=friends]');await press('[data-action=olaf-play]');await press('[data-action=bridge-walk]');await p.waitForTimeout(2500);await press('[data-view=all]');await press('[data-magic=bridge]');await p.waitForFunction(()=>document.querySelector('.frozen-mount').dataset.bridge==='off');assert(true,'representative Olaf bridge crossing safely returns before clear');
 await press('[data-action=undo]');assert(await p.locator('.frozen-mount').getAttribute('data-progress')==='0','undo removes only manually placed Olaf');
 await press('[data-view=lake]');await press('[data-magic=snow]');await p.waitForTimeout(300);await p.locator('.wb-stage').screenshot({path:'tmp/tasks/world-box-step04/cast-a.png'});await p.waitForTimeout(800);await p.locator('.wb-stage').screenshot({path:'tmp/tasks/world-box-step04/cast-b.png'});
 await press('[data-action=reset]');const before=await p.locator('.wb-canvas').screenshot();await p.waitForTimeout(250);const after=await p.locator('.wb-canvas').screenshot();assert(before.equals(after),'modal pauses real rendered GLB animation');await p.keyboard.press('Escape');
 await p.goto('http://127.0.0.1:5175/?play=world-in-a-box&scene=unknown-frozen');await ready();assert((await p.title()).includes('窗边有风'),'unknown scene fallback title');
 assert(errors.length===0,'edge flows no uncaught error');rows.push({case:'subpath-old-save-reset-bridge-animation',checks:[...checks]});
 }finally{await c.close();}
 const f=await context(true),fp=await f.newPage();try{await fp.goto('http://127.0.0.1:5175/?play=world-in-a-box&scene=frozen-elsa-playground');await fp.locator('[data-ready=true]').waitFor();await fp.locator('[data-action=reset]').click();await fp.locator('[data-action=confirm-reset]').click();assert((await fp.locator('[data-message]').textContent()).includes('暂时无法保存'),'storage fault accurately reported without blocking play');}finally{await f.close();}
 const delayed=await context(),dp=await delayed.newPage();try{await delayed.route('**/frozen-elsa-playground.glb',async r=>{await new Promise(resolve=>setTimeout(resolve,1700));await r.continue().catch(()=>{});});await dp.goto('http://127.0.0.1:5175/?play=world-in-a-box&scene=frozen-elsa-playground');await dp.locator('[data-action=boxes]').click();await dp.locator('[data-box=window-breeze]').click();await dp.locator('[data-ready=true]').waitFor();await dp.waitForTimeout(1900);assert((await dp.title()).includes('窗边有风')&&await dp.locator('.frozen-mount').count()===0,'late GLB cannot revive disposed scene');}finally{await delayed.close();}
 return{result:'PASS_MACHINE',checks,rows,scope:'synthetic isolated storage/load faults; true input; no family saves'};
}
