async driver=>{
 const {writeFile}=await import('node:fs/promises'),ctx=await driver.context().browser().newContext({viewport:{width:1024,height:900}}),p=await ctx.newPage(),checks=[];
 const assert=(v,msg)=>{if(!v)throw Error(msg);checks.push(msg);};
 await ctx.addInitScript(()=>{window.soundProbe={active:0,max:0,records:[]};const start=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...a){soundProbe.active++;soundProbe.max=Math.max(soundProbe.max,soundProbe.active);this.addEventListener('ended',()=>soundProbe.active--,{once:true});return start.apply(this,a);};const connect=AudioNode.prototype.connect;AudioNode.prototype.connect=function(target,...a){const result=connect.call(this,target,...a);if(target instanceof AudioDestinationNode){const analyser=this.context.createAnalyser();connect.call(this,analyser);soundProbe.analyser=analyser;const out=this.context.createMediaStreamDestination();connect.call(this,out);const canvas=document.querySelector('.wb-canvas canvas');const tracks=[...out.stream.getTracks(),...(canvas?canvas.captureStream(15).getVideoTracks():[])];const recorder=new MediaRecorder(new MediaStream(tracks)),chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);recorder.start();soundProbe.records.push({recorder,chunks});}return result;};});
 await ctx.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:5175/')?r.continue():r.abort());
 const press=s=>p.locator(s).click(),ready=()=>p.locator('[data-ready=true]').waitFor();
 const audio=()=>p.locator('.wb-mount').evaluate(e=>e.dataset.diagnostics?JSON.parse(e.dataset.diagnostics).audio:JSON.parse(e.dataset.audio));
 const loaded=()=>p.waitForFunction(()=>{const e=document.querySelector('.wb-mount'),a=e.dataset.diagnostics?JSON.parse(e.dataset.diagnostics).audio:JSON.parse(e.dataset.audio);return!a.pending&&a.loops.some(x=>x.key==='music');});
 async function channels(music,sfx,ambient){await press('[data-sound-settings]');for(const [k,v] of Object.entries({music,sfx,ambient}))await p.locator('[data-channel='+k+']').press(v?'End':'Home');await press('[data-sound-close]');}
 const rms=()=>p.evaluate(async()=>{let peak=0,rms=0;for(let i=0;i<15;i++){const a=soundProbe.analyser,d=new Float32Array(a.fftSize);a.getFloatTimeDomainData(d);peak=Math.max(peak,...d.map(Math.abs));rms+=Math.sqrt(d.reduce((sum,x)=>sum+x*x,0)/d.length);await new Promise(r=>setTimeout(r,40));}return{peak,rms:rms/15};});
 try{
 await p.goto('http://127.0.0.1:5175/?play=world-in-a-box&scene=frozen-elsa-playground');await ready();await press('[data-action=help]');await loaded();
 await channels(true,false,false);const music=await rms();assert(music.rms>.001,'music alone has actual output');assert((await audio()).loops.every(x=>x.key==='music'),'music isolated');
 await channels(false,false,true);const ambient=await rms();assert(ambient.rms>.0001,'snow air ambient alone');assert((await audio()).loops.every(x=>x.name==='frozen-air'),'no river environment');
 await channels(false,true,false);await press('[data-magic=bridge]');await p.waitForFunction(()=>document.querySelector('.frozen-mount').dataset.bridge==='ready');await press('[data-magic=snow]');const effects=await rms();assert(effects.rms>.0001,'effects alone output');
 await channels(true,true,true);await press('[data-action=mute]');await p.waitForFunction(()=>{const d=new Float32Array(soundProbe.analyser.fftSize);soundProbe.analyser.getFloatTimeDomainData(d);return soundProbe.active===0&&d.every(v=>Math.abs(v)<.0001);},null,{timeout:750});const muted=await rms();assert(muted.peak<.0001,'master mute stops PCM');await press('[data-action=mute]');await loaded();
 const source=(await audio()).loops.find(x=>x.key==='music');await press('[data-action=reset]');await press('[data-action=confirm-reset]');await p.waitForFunction(()=>document.querySelector('.frozen-mount').dataset.progress==='0');assert((await audio()).loops.find(x=>x.key==='music').started===source.started,'reset preserves same music source phase');assert((await audio()).loops.every(x=>['music','environment'].includes(x.key)),'reset clears object voices');
 const recording=await p.evaluate(async()=>{const r=soundProbe.records[0];await new Promise(done=>{r.recorder.onstop=done;r.recorder.stop();});return new Promise(done=>{const f=new FileReader();f.onload=()=>done(f.result.split(',')[1]);f.readAsDataURL(new Blob(r.chunks,{type:'video/webm'}));});});await writeFile('tmp/tasks/world-box-step04/frozen-operation.webm',Buffer.from(recording,'base64'));
 for(let round=0;round<5;round++)for(const scene of ['window-breeze','dresden-river-campus','frozen-elsa-playground']){await press('[data-action=boxes]');await press('[data-box='+scene+']');await ready();await loaded();}
 await p.waitForFunction(()=>soundProbe.active===2);assert(true,'five three-box rounds retain exactly two stable sources');const trend=await p.evaluate(()=>({active:soundProbe.active,max:soundProbe.max}));await press('[data-action=exit]');await p.waitForFunction(()=>soundProbe.active===0);assert(true,'exit stops all sources');
 return{result:'PASS_MACHINE',checks,music,ambient,effects,muted,trend,recording:'Canvas 15fps plus actual Web Audio output branch; no microphone/speaker capture; outside-canvas controls not recorded',listening:'NOT_TESTED'};
 }catch(e){return{result:'AUTO_REVISE',checks,error:String(e),audio:await audio().catch(()=>null)};}finally{await ctx.close();}
}
