async driver=>{
 const rows=[],profiles=[['keyboard',1366,900,false],['mouse',1440,900,false],['360',360,800,true],['390',390,844,true],['landscape360',800,360,true],['landscape390',844,390,true],['tablet768',768,1024,true],['tablet1024',1024,768,true]];
 for(const [name,w,h,touch] of profiles){if(driver.qaProfiles&&!driver.qaProfiles.includes(name))continue;const ctx=await driver.context().browser().newContext({viewport:{width:w,height:h},hasTouch:touch}),p=await ctx.newPage(),errors=[],checks=[],forbidden=[];p.setDefaultTimeout(9000);p.on('pageerror',e=>errors.push(e.message));
 const assert=(v,msg)=>{if(!v)throw Error(msg);checks.push(msg);};const state=()=>p.locator('.frozen-mount').evaluate(e=>({...e.dataset}));
 async function keyTo(selector){for(let i=0;i<130;i++){if(await p.evaluate(s=>document.activeElement?.matches(s),selector))return;const region=await p.evaluate(s=>{const target=document.querySelector(s),active=document.activeElement;for(const r of ['.fr-groups','.wb-pieces','.wb-targets']){if(target?.closest(r)&&target.closest(r)===active?.closest(r))return true;}return false;},selector);const backwards=!region&&await p.evaluate(s=>{const target=document.querySelector(s),active=document.activeElement;return active!==document.body&&!!target&&!!(active.compareDocumentPosition(target)&Node.DOCUMENT_POSITION_PRECEDING);},selector);await p.keyboard.press(region?'ArrowRight':backwards?'Shift+Tab':'Tab');}throw Error('Keyboard cannot reach '+selector);}
 const press=async selector=>{if(name==='keyboard'){await keyTo(selector);await p.keyboard.press('Enter');}else if(touch)await p.locator(selector).tap();else await p.locator(selector).click();};
 const action=a=>press('[data-action="'+a+'"]');
 const ready=()=>p.locator('[data-ready=true]').waitFor();
 const magic=async kind=>{await press('[data-magic='+kind+']');await p.waitForFunction(k=>{const d=document.querySelector('.frozen-mount').dataset;return k==='snow'?d.snow==='true':d[k]==='ready';},kind);};
 const groups=[['anna','olaf','kristoff','sven'],['arendelle_castle','town_houses','town_lanterns'],['snow_pines','sleigh','forest_lantern'],['palace_steps','palace_column_left','palace_column_right','palace_gate','palace_spire','palace_chandelier']];
 async function assembleAll(){await action('help');for(const gi of [3,0,2,1]){await press('[data-group="'+gi+'"]');const ids=groups[gi];for(let i=0;i<ids.length;i++){if(i&&i%3===0)await action('next');await press('[data-piece='+ids[i]+']');await press('[data-slot='+ids[i]+']');}}assert((await state()).progress==='16','16 manual pieces complete without extra goals');}
 try{
 await ctx.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:5175/')||r.request().url().startsWith('data:')?r.continue():(forbidden.push(r.request().url()),r.abort()));
 await p.goto('http://127.0.0.1:5175/?hub=classic');
 if(name==='keyboard'){await press('[data-game-id="world-in-a-box"] button');await ready();await action('boxes');await press('[data-box=frozen-elsa-playground]');}else await p.goto('http://127.0.0.1:5175/?play=world-in-a-box&scene=frozen-elsa-playground');await ready();
 const load=await p.evaluate(()=>({ms:performance.now(),resources:performance.getEntriesByType('resource').filter(x=>x.name.includes('/frozen')).map(x=>({url:x.name.split('/').pop(),bytes:x.transferSize,duration:x.duration}))}));
 await magic('snow');await press('[data-magic=snow]');await magic('bridge');await magic('rink');assert((await state()).progress==='0','all three spells at zero pieces');
 await assembleAll();await press('[data-view=all]');const completeScene=JSON.parse((await state()).diagnostics).scene;const completeFrames=await p.evaluate(()=>new Promise(resolve=>{const times=[];let last=performance.now();function frame(now){times.push(now-last);last=now;if(times.length<60)requestAnimationFrame(frame);else{times.sort((a,b)=>a-b);resolve({p50:times[30],p95:times[57],max:times[59],samples:60});}}requestAnimationFrame(frame);}));await p.locator('.wb-stage').screenshot({path:'tmp/tasks/world-box-step04/matrix-'+name+'.png'});
 await action('friends');await action('olaf-play');await action('circle');await p.waitForTimeout(450);await action('eight');await p.waitForTimeout(450);await action('skate-stop');await press('[data-view=all]');await press('[data-magic=rink]');await p.waitForFunction(()=>document.querySelector('.frozen-mount').dataset.rink==='off');assert(true,'circle, eight, safe rink clearing via real input');
 await action('sleigh-play');await action('anna');await action('lake-ride');await p.waitForFunction(()=>JSON.parse(document.querySelector('.frozen-mount').dataset.ride).t>.06);await action('ride-pause');const parked=(await state()).ride;await p.waitForTimeout(200);assert((await state()).ride===parked,'pause freezes trip');await action('ride-return');await p.waitForFunction(()=>JSON.parse(document.querySelector('.frozen-mount').dataset.ride).t===0);
 await action('palace-ride');await p.waitForFunction(()=>JSON.parse(document.querySelector('.frozen-mount').dataset.ride).t>.3);await action('ride-pause');await press('[data-view=all]');await press('[data-magic=bridge]');await p.waitForFunction(()=>document.querySelector('.frozen-mount').dataset.bridge==='off');assert(!JSON.parse((await state()).ride).running,'sleigh evacuated before bridge retraction');
 await action('palace');await action('door');await action('chandelier');await action('reset');assert(await p.evaluate(()=>document.activeElement.matches('[data-action=cancel-reset]')),'reset default is continue');await p.keyboard.press('Escape');assert((await state()).progress==='16','reset cancel keeps assembly');
 await press('[data-sound-settings]');await p.keyboard.press('Escape');await action('mute');await action('mute');
 await action('reset');await action('confirm-reset');await p.waitForFunction(()=>document.querySelector('.frozen-mount').dataset.progress==='0');assert((await state()).bridge==='off'&&(await state()).rink==='off','reset clears spell facts');assert(await p.locator('[data-action=undo]').isDisabled(),'reset clears undo');await p.reload();await ready();assert((await state()).progress==='0','reset readback persists');
 const geometry=[];const magicButtons=p.locator('[data-magic]:visible');for(let i=0;i<await magicButtons.count();i++){const b=magicButtons.nth(i);await b.scrollIntoViewIfNeeded();geometry.push(await b.evaluate(b=>{const r=b.getBoundingClientRect();return{text:b.textContent,w:r.width,h:r.height,hit:[[.25,.25],[.75,.25],[.5,.5],[.25,.75],[.75,.75]].every(([x,y])=>document.elementFromPoint(r.x+r.width*x,r.y+r.height*y)===b)};}));}assert(geometry.length===3&&geometry.every(x=>x.w>=44&&x.h>=44&&x.hit),'magic target dimensions');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no horizontal overflow');
 const frameTimes=await p.evaluate(()=>new Promise(resolve=>{const times=[];let last=performance.now();function frame(now){times.push(now-last);last=now;if(times.length<60)requestAnimationFrame(frame);else{times.sort((a,b)=>a-b);resolve({p50:times[30],p95:times[57],max:times[59],samples:60});}}requestAnimationFrame(frame);}));const diagnostics=JSON.parse((await state()).diagnostics);assert(errors.length===0,'no page errors');assert(forbidden.length===0,'zero external requests');await action('boxes');await press('[data-box=window-breeze]');await ready();await action('exit');await p.waitForURL(url=>!url.searchParams.has('play'));assert(!p.url().includes('play=world-in-a-box'),'return route works');rows.push({name,checks,load,geometry,frameTimes,completeScene,completeFrames,diagnostics,errors});
 }catch(e){await p.screenshot({path:'tmp/tasks/world-box-step04/failure-'+name+'.png',fullPage:true});return{result:'AUTO_REVISE',name,error:String(e),checks,rows,errors,dom:await p.locator('body').innerText()};}finally{await ctx.close();}
 }
 return{result:'PASS_MACHINE',scope:'new scene real input matrix only',rows};
}
