// Real Web Audio graph probe + recordings. Does not change source gains or playback.
async driver=>{
 const {writeFile}=await import('node:fs/promises'),browser=driver.context().browser(),ctx=await browser.newContext({viewport:{width:1366,height:950}}),p=await ctx.newPage(),checks=[];
 const assert=(v,m)=>{if(!v)throw Error(m);checks.push(m);};
 await ctx.addInitScript(()=>{
  window.audioQA={created:0,closed:0,active:0,maxActive:0,starts:0,records:[]};
  const start=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...args){audioQA.starts++;audioQA.active++;audioQA.maxActive=Math.max(audioQA.maxActive,audioQA.active);this.addEventListener('ended',()=>audioQA.active--,{once:true});return start.apply(this,args);};
  const Native=AudioContext;window.AudioContext=new Proxy(Native,{construct(t,a){audioQA.created++;return Reflect.construct(t,a);}});const close=Native.prototype.close;Native.prototype.close=function(){audioQA.closed++;return close.call(this);};
  const connect=AudioNode.prototype.connect;AudioNode.prototype.connect=function(target,...args){const result=connect.call(this,target,...args);if(target instanceof AudioDestinationNode){const analyser=this.context.createAnalyser();analyser.fftSize=4096;connect.call(this,analyser);window.audioQA.analyser=analyser;const stream=this.context.createMediaStreamDestination();connect.call(this,stream);const recorder=new MediaRecorder(stream.stream,{mimeType:'audio/webm;codecs=opus'}),chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);const item={recorder,chunks};audioQA.records.push(item);recorder.start();}return result;};
 });
 await ctx.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:5175/')?r.continue():r.abort());
 const press=s=>p.locator(s).click(),ready=()=>p.locator('[data-ready=true]').waitFor(),state=()=>p.locator('.wb-mount').evaluate(e=>({...e.dataset}));
 const audio=async()=>JSON.parse((await state()).audio);
 async function waitAudio(){await p.waitForFunction(()=>{const a=JSON.parse(document.querySelector('.wb-mount').dataset.audio);return a.pending===0&&a.loops.some(l=>l.key==='music');});}
 async function channels(music,sfx,ambient){await press('[data-sound-settings]');for(const [key,value] of Object.entries({music,sfx,ambient})){await p.locator(`[data-channel=${key}]`).press(value?'End':'Home');}await press('[data-sound-close]');}
 async function rms(ms=650){return p.evaluate(ms=>new Promise(resolve=>{let peak=0,rms=0,n=0;const start=performance.now();function read(){const a=audioQA.analyser,d=new Float32Array(a.fftSize);a.getFloatTimeDomainData(d);peak=Math.max(peak,...d.map(Math.abs));rms+=Math.sqrt(d.reduce((s,v)=>s+v*v,0)/d.length);n++;if(performance.now()-start<ms)setTimeout(read,25);else resolve({peak,rms:rms/n});}read();}),ms);}
 async function place(id,group){if(group)await press(`[data-group=${group}]`);while(await p.locator('[data-action=prev]').isEnabled())await press('[data-action=prev]');for(let i=0;i<3&&!await p.locator(`[data-piece=${id}]`).isVisible();i++)await press('[data-action=next]');await press(`[data-piece=${id}]`);await press('[data-action=hint]');await press(`[data-slot=${id}]`);}
 async function capture(name){const data=await p.evaluate(async()=>{const item=audioQA.records.at(-1);await new Promise(resolve=>{item.recorder.onstop=resolve;item.recorder.stop();});return new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.readAsDataURL(new Blob(item.chunks,{type:'audio/webm'}));});});await writeFile(`docs/world-in-a-box/step03-evidence/${name}.webm`,Buffer.from(data,'base64'));}
 const metrics={};
 try{
 await p.goto('http://127.0.0.1:5175/?play=world-in-a-box');await ready();await press('[data-action=help]');await waitAudio();
 await channels(true,false,false);metrics.music=await rms();assert(metrics.music.rms>.001,'music channel produces actual PCM');assert((await audio()).loops.every(l=>l.key==='music'),'music-only excludes environment and object loops');
 await channels(false,false,true);metrics.ambient=await rms();assert(metrics.ambient.rms>.0001,'environment channel produces actual PCM');assert(!(await audio()).loops.some(l=>l.key==='music'),'zero music removes music source');
 await channels(false,true,false);await place('shutter_left');await p.waitForFunction(()=>document.querySelector('.wb-canvas').dataset.motion==='still');await press('[data-slot=shutter_left]');await place('wind_chime');metrics.wind=await rms();assert(metrics.wind.rms>.0001,'sound-effects-only wind has actual PCM');await press('[data-action=view]');await press('[data-slot=shutter_left]');await p.waitForFunction(()=>document.querySelector('.wb-canvas').dataset.motion==='still');metrics.closed=await rms();assert(!(await audio()).loops.some(l=>l.key==='wind'),'closing shutters removes wind loop without global mute');assert(metrics.closed.peak<.0001,'only-SFX closed window becomes silent');
 await channels(true,true,true);await press('[data-slot=shutter_left]');await press('[data-action=reset]');const music=(await audio()).loops.find(l=>l.key==='music');await press('[data-action=confirm-reset]');assert((await audio()).loops.find(l=>l.key==='music').started===music.started,'reset retains same music source and phase');assert((await audio()).loops.every(l=>['music','environment'].includes(l.key)),'reset removes all old object loops');
 await press('[data-action=mute]');await p.waitForFunction(()=>JSON.parse(document.querySelector('.wb-mount').dataset.audio).loops.length===0);await p.waitForFunction(()=>{const a=audioQA.analyser,d=new Float32Array(a.fftSize);a.getFloatTimeDomainData(d);return audioQA.active===0&&d.every(v=>Math.abs(v)<.0001);},null,{timeout:750});metrics.mute=await rms();assert(metrics.mute.peak<.0001,'master mute silences real PCM');await press('[data-action=mute]');await waitAudio();await capture('window-runtime-audio');
 await press('[data-action=boxes]');await press('[data-box=dresden-river-campus]');await ready();await waitAudio();assert(true,'switch fades into new music without a second unlock click');await place('paddle_steamer','river');await place('river_pier','river');await waitAudio();
 await press('[data-action=boat-start]');await p.waitForFunction(()=>JSON.parse(document.querySelector('.wb-mount').dataset.audio).loops.some(l=>l.key==='boat'));const events=(await audio()).events.filter(e=>e.name==='boat-start').length;await press('[data-action=boat-pause]');await p.waitForFunction(()=>!JSON.parse(document.querySelector('.wb-mount').dataset.audio).loops.some(l=>l.key==='boat'));await press('[data-action=boat-start]');assert((await audio()).events.filter(e=>e.name==='boat-start').length===events,'resume does not repeat departure horn');
 await press('[data-action=boat-dock]');await p.waitForFunction(()=>document.querySelector('.wb-mount').dataset.boatRunning==='false',null,{timeout:12000});assert(!(await audio()).loops.some(l=>l.key==='boat'),'completed lateral mooring stops drive sound');assert((await audio()).events.some(e=>e.name==='boat-contact'),'mooring emits one contact event');metrics.cityMix=await rms();assert(metrics.cityMix.peak<.95,'actual mix remains below clipping');await capture('boat-depart-travel-moor-audio');
 for(let i=0;i<5;i++){await press('[data-action=boxes]');await press('[data-box=window-breeze]');await ready();await press('[data-action=help]');await waitAudio();await press('[data-action=reset]');await press('[data-action=confirm-reset]');await press('[data-action=boxes]');await press('[data-box=dresden-river-campus]');await ready();await press('[data-action=help]');await waitAudio();await press('[data-action=reset]');await press('[data-action=confirm-reset]');}
 await p.waitForFunction(()=>audioQA.active===2);const resources=await p.evaluate(()=>({created:audioQA.created,closed:audioQA.closed,active:audioQA.active,starts:audioQA.starts,maxActive:audioQA.maxActive}));assert(resources.created-resources.closed===1&&resources.active===2,'five round trips and repeated resets leave one context and only music/environment sources');await press('[data-action=exit]');await p.waitForFunction(()=>audioQA.active===0&&audioQA.created===audioQA.closed);assert(true,'exit stops every source and closes last context');
 return{result:'PASS_MACHINE',checks,metrics,resources,recording:'Web Audio output branch captured as Opus/WebM; actual runtime PCM, no microphone or system speaker capture',listening:'NOT_TESTED: no perceptual listening capability'};
 }catch(error){return{result:'AUTO_REVISE',checks,metrics,error:String(error),state:await state().catch(()=>null)};}finally{await ctx.close();}
}
