import type { SourceRecord } from "./types";

export const COMPLETE_SOURCE_RECORDS = [
  {
    id: "repo-chapter-one-v2",
    sourceKind: "repository",
    title: "汉字魔法战 V2 Chapter One canonical manifest",
    version: "content-2",
    location: "games/hanzi-radical-battle/v2/chapter-one/characters.ts",
    supports: ["legacy character identity", "fixed reading", "ordered component placement", "child-facing meaning", "legacy revision"],
    limitation: "Supports the shipped V2 product record, not an etymology claim.",
  },
  {
    id: "repo-wheel-audit",
    sourceKind: "repository",
    title: "Frozen wheel source and derived audit",
    version: "raw-sha256-0e47b5d434cff65c9af1a65fad1dcd5a4f6432bf218223213083a43a54af64ac",
    location: "games/hanzi-radical-battle/v2/wheel-workshop/library",
    supports: ["legacy provenance", "candidate reading", "candidate familiar word", "derived structure audit", "alignmentStatus legacy-label-only"],
    limitation: "Historical raw records remain immutable; playable claims come from reviewed derived records.",
  },
  {
    id: "unicode-unihan-17",
    sourceKind: "unicode",
    title: "Unicode 17.0.0 Unihan",
    version: "17.0.0 / zip F7A48B2B545ACFAA77B2D607AE28747404CE02BAEFEE16396C5D2D7A8EF34B5E",
    location: "https://www.unicode.org/Public/17.0.0/ucd/Unihan.zip",
    supports: ["canonical code point", "Mandarin reading cross-check"],
    limitation: "Does not define child-facing meanings or a single pedagogical decomposition.",
  },
  {
    id: "moe-modern-components",
    sourceKind: "language-standard",
    title: "现代常用字部件及部件名称规范",
    version: "GF 0014-2009",
    location: "https://www.moe.gov.cn/jyb_xwfb/gzdt_gzdt/moe_1485/tnull_45766.html",
    supports: ["component naming", "component distinction", "application-oriented decomposition"],
    limitation: "A component standard is not by itself a word-meaning or etymology source.",
  },
  {
    id: "makemeahanzi-bddc96d",
    sourceKind: "structure-crosscheck",
    title: "Make Me a Hanzi dictionary snapshot",
    version: "bddc96d41bef78427ed0e034e9f7e31d71fd1b92 / dictionary sha256 744bb05d5b0742e9ee35c37791f94d56a173349b3367569e7ca11e510364d203",
    location: "https://github.com/skishore/makemeahanzi/tree/bddc96d41bef78427ed0e034e9f7e31d71fd1b92",
    supports: ["IDS root structure", "first-level component cross-check", "candidate reading cross-check"],
    limitation: "Used only as a frozen cross-check; graphics are not copied and it is not a runtime dependency.",
  },
  {
    id: "cns11643-shape-crosscheck",
    sourceKind: "structure-crosscheck",
    title: "CNS11643 全字库",
    version: "accessed for disputed shape variants",
    location: "https://www.cns11643.gov.tw/",
    supports: ["component shape and IDS variant adjudication"],
    limitation: "Not used as a simplified-character grade alignment source.",
  },
  {
    id: "moe-curriculum-2022",
    sourceKind: "language-standard",
    title: "义务教育课程方案和课程标准（2022年版）",
    version: "2022",
    location: "https://www.moe.gov.cn/srcsite/A26/s8001/202204/t20220420_619921.html",
    supports: ["broad literacy-stage framing"],
    limitation: "Does not support per-character p1-p6 or j1-j3 claims; wheel bands remain legacy-label-only.",
  },
  {
    id: "moe-dictionary-words",
    sourceKind: "dictionary",
    title: "教育部国语辞典简编本与重编国语辞典修订本",
    version: "2021",
    location: "https://dict.concised.moe.edu.tw/",
    supports: ["fixed word order", "fixed Mandarin reading", "ordinary word meaning and context"],
    limitation: "Traditional-form dictionary entries are cross-checks; the game retains its reviewed simplified-character manifest.",
  },
  {
    id: "repo-word-audit-v3",
    sourceKind: "repository",
    title: "V3 complete-edition derived word audit",
    version: "word-audit-1",
    location: "games/hanzi-radical-battle/complete/content-graph/words.ts",
    supports: ["two-core-character constraint", "reverse-order disposition", "child-facing short meaning", "world context"],
    limitation: "Derived product records remain bounded by their cited dictionary and repository sources.",
  },
] as const satisfies readonly SourceRecord[];

export type CompleteSourceId = typeof COMPLETE_SOURCE_RECORDS[number]["id"];
