import {chromium} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const output=process.env.ODDITY_OUTPUT||'docs/oddity-puzzles/evidence';await mkdir(output,{recursive:true});
const origin=process.env.ODDITY_ORIGIN||'http://127.0.0.1:5175';
const browser=await chromium.launch({channel:'chrome',headless:true});const results=[];
const profiles=[['desktop-keyboard',1440,1000,'keyboard'],['desktop-mouse',1440,1000,'mouse'],['desktop-touch',1280,900,'touch'],['phone-390',390,844,'touch'],['tablet-768',768,1024,'touch'],['tablet-1024',1024,768,'keyboard'],['tablet-portrait',1024,1366,'mouse'],['tablet-landscape',1366,1024,'touch']].filter(p=>!process.env.ODDITY_PROFILES||process.env.ODDITY_PROFILES.split(',').includes(p[0]));
try{for(const [name,width,height,input] of profiles){const ctx=await browser.newContext({viewport:{width,height},hasTouch:true,isMobile:input==='touch'&&width<1100,deviceScaleFactor:input==='touch'?2:1}),p=await ctx.newPage();const errors=[],external=[],metrics=[];p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await ctx.route('**/*',r=>{if(!r.request().url().startsWith(origin+'/')&&!r.request().url().startsWith('data:')){external.push(r.request().url());return r.abort();}return r.continue();});
 const cmd=id=>p.locator(`[data-cmd="${id}"]`);const inCommands=label=>p.locator('.odd-commands').getByRole('button',{name:label,exact:true});
 async function hit(loc){await loc.waitFor({state:'visible'});if(input==='keyboard'){
   for(let steps=0;steps<90;steps++){
    if(await loc.evaluate(e=>e===document.activeElement)){await p.keyboard.press('Enter');return;}
    const same=await loc.evaluate(e=>{const region=e.closest('.odd-levels,.odd-commands,.odd-cards,.odd-actors');return !!region&&region.contains(document.activeElement);});
    if(same){await p.keyboard.press('Home');const count=await loc.evaluate(e=>e.closest('.odd-levels,.odd-commands,.odd-cards,.odd-actors').querySelectorAll('button:not(:disabled)').length);for(let i=0;i<count;i++){if(await loc.evaluate(e=>e===document.activeElement)){await p.keyboard.press('Enter');return;}await p.keyboard.press('ArrowRight');}}
    const forward=await loc.evaluate(e=>document.activeElement===document.body||!!(document.activeElement.compareDocumentPosition(e)&Node.DOCUMENT_POSITION_FOLLOWING));await p.keyboard.press(forward?'Tab':'Shift+Tab');
   }throw Error('Keyboard cannot reach '+await loc.textContent());
  }else if(input==='touch'){await loc.scrollIntoViewIfNeeded();await loc.tap();}else await loc.click();
 }
 async function settled(){await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await p.locator('.odd-stage[data-motion=still]').waitFor();}
 async function action(label){const before=await p.locator('.oddity-mount').getAttribute('data-history');await hit(inCommands(label));await settled();const status=await p.locator('.odd-status').textContent();const after=await p.locator('.oddity-mount').getAttribute('data-history');assert.notEqual(after,before,'action rejected: '+label+' '+status);}
 const state=async()=>JSON.parse(await p.locator('.oddity-mount').getAttribute('data-state'));
 async function mode(id){await hit(cmd(id));}
 async function tutorials(){while(await cmd('skipDemo').isVisible())await hit(cmd('skipDemo'));}
 async function snap(label){await settled();const m=JSON.parse(await p.locator('.odd-stage').getAttribute('data-metrics'));metrics.push({level:label,...m});assert(m.triangles<=100000,`${label}: triangle budget ${m.triangles}`);assert(m.calls<=100,`${label}: draw budget ${m.calls}`);if(name==='desktop-mouse'&&['l1','l2-portal','l3-open'].includes(label)||name==='phone-390'&&label==='l3')await p.screenshot({path:`${output}/${name}-${label}.png`,fullPage:true});}
 try{
  await p.goto(origin+'/');await hit(p.locator('[data-world-oddity-link]'));await p.locator('[data-ready=true]').waitFor();await tutorials();await snap('l1');
  await mode('hint');await hit(cmd('close'));await mode('hint');assert.match(await p.locator('dialog').textContent(),/规则/);await hit(cmd('close'));await mode('hint');assert.match(await p.locator('dialog').textContent(),/下一步/);await hit(cmd('close'));
  await action('观察窗前');await mode('abilityring');await mode('targetbox');await hit(inCommands('自己手边'));assert.match(await p.locator('.odd-status').textContent(),/挡/);await mode('targetlamp');await action('通道墙');await mode('walk');await action('档案架旁');await mode('objects');await action('拿起档案盒');assert.equal((await state()).won,false);await mode('undo');assert.equal((await state()).items.find(o=>o.id==='box').holder,null);await action('拿起档案盒');await mode('walk');await action('走廊出口');assert.equal((await state()).won,true);await snap('l1-complete');
  await mode('next');await p.locator('.oddity-mount[data-level="2"] [data-ready=true]').waitFor();await tutorials();await snap('l2');await mode('abilitykey');await hit(inCommands('连接安全小院'));assert.match(await p.locator('.odd-status').textContent(),/门坏/);await mode('abilitycamera');await hit(cmd('preview'));assert.match(await p.locator('dialog').textContent(),/走廊、人物/);await hit(cmd('restore'));await settled();await mode('walk');await action('门前');await mode('abilitykey');await action('连接安全小院');assert.equal((await state()).won,false);await snap('l2-portal');await action('走过门');assert.equal((await state()).won,true);
  await mode('next');await p.locator('.oddity-mount[data-level="3"] [data-ready=true]').waitFor();await tutorials();await snap('l3');
  // Empty photo goes inside first; every recovery step uses ordinary player controls.
  await mode('abilityring');await mode('targetphoto');await action('接应托盘');await mode('npc');await action('拿起照片');await hit(inCommands('释放到托盘旁空地'));assert.match(await p.locator('.odd-status').textContent(),/空/);await action('放下照片');await mode('abilityring');await mode('targetphoto');await action('自己手边');
  await mode('abilityphoto');await action('收纳橙衣调查员');assert.equal((await state()).photo,'b');await mode('abilityring');await mode('targetphoto');await action('接应托盘');await snap('l3-photo');await mode('npc');await action('拿起照片');await action('释放到托盘旁空地');await mode('actorb');await mode('walk');await action('左开关旁');await action('保持左开关');assert.equal((await state()).latched,false);await mode('npc');await action('右开关旁');await action('保持右开关');assert.equal((await state()).latched,true);await snap('l3-open');await action('室外出口');await mode('walk');await action('室外出口');await mode('actora');await action('室外出口');assert.equal((await state()).won,true);await snap('l3-complete');
  const saved=await p.evaluate(()=>localStorage.getItem('family-games/oddity-puzzles/v1'));await p.reload();await p.locator('[data-ready=true]').waitFor();assert.equal((await state()).won,true);assert.equal(await p.evaluate(()=>localStorage.getItem('family-games/oddity-puzzles/v1')),saved);
  await mode('reset');await hit(cmd('close'));assert.equal((await state()).won,true);await mode('reset');await hit(cmd('confirmReset'));assert.equal((await state()).won,false);assert.equal((await state()).photo,null);await mode('level1');await p.locator('.oddity-mount[data-level="1"] [data-ready=true]').waitFor();assert.equal((await state()).won,true);
  await hit(p.locator('.odd-home'));await p.locator('[data-world-oddity-link]').waitFor();assert.equal(errors.length,0,errors.join('\n'));assert.equal(external.length,0,external.join('\n'));
  results.push({name,input,viewport:{width,height},result:'PASS',threeRooms:true,fromHome:true,hints:3,undo:true,scopedReset:true,saveReload:true,emptyPhotoRecovery:true,errors,external,metrics});console.log(name+' PASS');
 }catch(e){await p.screenshot({path:`${output}/${name}-failure.png`,fullPage:true});await writeFile(`${output}/${name}-failure.txt`,String(e)+'\n'+await p.locator('body').innerText());throw e;}finally{await ctx.close();}
}}finally{await browser.close();await writeFile(`${output}/browser-results.json`,JSON.stringify({profiles:results},null,2)+'\n');}
