import {chromium} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const out=process.env.ODDITY_OUTPUT||'docs/oddity-puzzles/evidence';await mkdir(out,{recursive:true});const origin=process.env.ODDITY_ORIGIN||'http://127.0.0.1:5175';const browser=await chromium.launch({channel:'chrome',headless:process.env.ODDITY_HEADED!=='1'});const rows=[];
try{
 const c=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true}),p=await c.newPage();const focusSession=await c.newCDPSession(p);if(process.env.ODDITY_HEADED==='1')await focusSession.send('Emulation.setFocusEmulationEnabled',{enabled:false});const errors=[],requests=[];p.on('pageerror',e=>errors.push(String(e)));p.on('request',r=>requests.push(r.url()));await c.route('**/*',r=>r.request().url().startsWith(origin+'/')?r.continue():r.abort());
 await c.addInitScript(()=>{window.oddityAnalysers=[];const connect=AudioNode.prototype.connect;AudioNode.prototype.connect=function(target,...args){const result=connect.call(this,target,...args);if(target instanceof AudioDestinationNode){const analyser=this.context.createAnalyser();analyser.fftSize=1024;connect.call(this,analyser);window.oddityAnalysers.push(analyser);}return result;};});
 const cmd=id=>p.locator(`[data-cmd="${id}"]`),hit=id=>cmd(id).click(),btn=name=>p.locator('.odd-commands').getByRole('button',{name,exact:true});const state=async()=>JSON.parse(await p.locator('.oddity-mount').getAttribute('data-state'));
 const still=async()=>{await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await p.locator('[data-motion=still]').waitFor();};
 await p.goto(origin+'/');assert(!requests.some(u=>u.endsWith('.glb')),'home eagerly loads GLB');await p.locator('[data-world-oddity-link]').click();await p.locator('[data-ready=true]').waitFor();await hit('skipDemo');await hit('skipDemo');await still();
 // Semantic baseline accepted by visual inspection; unchanged capture after reload, no snapshot updating.
 if(process.env.ODDITY_HEADED!=='1'){async function stableCapture(path){await p.locator('.odd-cards img').evaluateAll(images=>Promise.all(images.map(i=>i.decode())));let last=await p.screenshot(),same=0;for(let i=0;i<30;i++){await p.waitForTimeout(150);const next=await p.screenshot();same=last.equals(next)?same+1:0;last=next;if(same===3){await writeFile(path,next);return next;}}throw Error('visual did not settle');}const baseline=await stableCapture(out+'/baseline.png');await p.reload();await p.locator('[data-ready=true]').waitFor();await still();assert(baseline.equals(await stableCapture(out+'/readback.png')),'initial visual not deterministic on reload');rows.push({check:'same-source no-update visual readback',result:'PASS'});if(process.env.ODDITY_BASELINE_ONLY==='1'){await writeFile(out+'/visual-results.json',JSON.stringify({rows},null,2)+'\n');await browser.close();process.exit(0);}}
 // Native Space exactly once, scoped hotkey undo, real pointer/touch mixed operation.
 await btn('观察窗前').tap();await p.locator('[data-motion=moving]').waitFor();await p.keyboard.press('z');await still();assert.equal((await state()).actors[0].node,'exit');
 await btn('观察窗前').click();await p.locator('[data-motion=moving]').waitFor();await hit('reset');await hit('confirmReset');await still();await p.waitForTimeout(1100);assert.equal((await state()).actors[0].node,'exit');assert.equal(await p.locator('.oddity-mount').getAttribute('data-history'),'0');rows.push({check:'mixed input and animation-interrupt undo/reset',result:'PASS'});
 // Real tab focus loss, observe render progress (not merely already-committed logical state).
 await btn('观察窗前').click();await p.locator('[data-motion=moving]').waitFor();const other=await c.newPage();await other.goto('about:blank');await other.bringToFront();await cmd('resume').waitFor({state:'visible'});const before=await p.locator('.odd-stage').getAttribute('data-animation');await p.waitForTimeout(500);assert.equal(await p.locator('.odd-stage').getAttribute('data-animation'),before,'background animation advanced');await p.bringToFront();await hit('resume');await still();assert.equal((await state()).actors[0].node,'window');await other.close();rows.push({check:'real tab blur pauses pose/audio, explicit resume',result:'PASS'});
 // Layout/hit target checks across all requested sizes and CSS reflow at 200%.
 for(const [width,height] of [[1440,1000],[390,844],[768,1024],[1024,768],[1024,1366],[1366,1024]]){
  await p.setViewportSize({width,height});await still();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'horizontal overflow');
  for(const selector of ['.odd-cards button','.odd-tabs button','.odd-options button','.odd-tools button']){for(const b of await p.locator(selector).all()){if(!await b.isVisible())continue;await b.scrollIntoViewIfNeeded();const result=await b.evaluate(e=>{const r=e.getBoundingClientRect();const points=[[.5,.5],[.2,.2],[.8,.8]].map(([x,y])=>e.contains(document.elementFromPoint(r.x+r.width*x,r.y+r.height*y)));return {w:r.width,h:r.height,points};});assert(result.w>=44&&result.h>=44,JSON.stringify(result));assert(result.points.every(Boolean),'covered button '+await b.textContent());}}
  rows.push({check:'responsive target geometry',viewport:{width,height},result:'PASS'});
 }
 await p.setViewportSize({width:1440,height:1000});await p.evaluate(()=>{document.documentElement.style.zoom='2';});await still();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'200% reflow overflow');await hit('hint');await p.keyboard.press('Escape');await hit('reset');await hit('close');assert.equal(await cmd('reset').evaluate(e=>e===document.activeElement),true,'Escape/opener focus');await p.evaluate(()=>{document.documentElement.style.zoom='';});rows.push({check:'200 percent CSS reflow with real controls',result:'PASS',boundary:'CSS 200% layout zoom, not OS magnifier'});
 // Sound mixer values via real menu; observer only reads PCM.
 async function amplitude(){return await p.evaluate(()=>Math.max(0,...window.oddityAnalysers.map(a=>{const f=new Float32Array(a.fftSize);a.getFloatTimeDomainData(f);return Math.sqrt(f.reduce((sum,v)=>sum+v*v,0)/f.length);})));}
 await p.locator('[data-top=sound]').click();await p.waitForFunction(()=>window.oddityAnalysers.some(a=>{const f=new Float32Array(a.fftSize);a.getFloatTimeDomainData(f);return f.some(v=>Math.abs(v)>.00001);}));const audible=await amplitude();await hit('toggleMusic');await hit('toggleSfx');await hit('close');await p.waitForTimeout(250);const silent=await amplitude();assert(silent<.00001,'muted PCM');await p.locator('[data-top=sound]').click();await hit('toggleSfx');await hit('close');await hit('reset');await hit('confirmReset');await btn('观察窗前').click();await p.waitForTimeout(80);const cue=await amplitude();assert(cue>.00001,'local action cue missing');await still();rows.push({check:'actual local PCM music and independently enabled effect',audible,silent,cue,result:'PASS'});
 const oddityRaw=await p.evaluate(()=>localStorage.getItem('family-games/oddity-puzzles/v1'));
 await p.locator('.odd-home').click();await p.locator('[data-world-box-link]').click();await p.locator('[data-ready=true]').waitFor();await p.locator('[data-piece=shutter_left]').click();await p.locator('[data-action=hint]').click();await p.locator('[data-slot=shutter_left]').click();const oldKey=await p.evaluate(()=>localStorage.getItem('family-games/world-in-a-box/v1'));assert(oldKey);await p.reload();await p.locator('[data-ready=true]').waitFor();assert.equal(await p.evaluate(()=>localStorage.getItem('family-games/world-in-a-box/v1')),oldKey);assert.equal(await p.evaluate(()=>localStorage.getItem('family-games/oddity-puzzles/v1')),oddityRaw);
 // Both old boxes mount; no old save is cleared by a new-game reset.
 await p.goto(origin+'/?play=world-in-a-box&scene=dresden-river-campus');await p.locator('[data-ready=true]').waitFor();await p.goto(origin+'/?play=oddity-puzzles');await p.locator('[data-ready=true]').waitFor();await hit('reset');await hit('confirmReset');assert.equal(await p.evaluate(()=>localStorage.getItem('family-games/world-in-a-box/v1')),oldKey);await p.locator('.odd-home').click();rows.push({check:'World Box default and Dresden entry/reload plus isolated save/reset',result:'PASS'});
 assert(!errors.length,errors.join('\n'));assert(!requests.some(u=>!u.startsWith(origin+'/')));rows.push({check:'console and same-origin-only resources',errors,external:[],result:'PASS'});await c.close();
 // Fault injection is isolated from input E2E and never used to advance a puzzle.
 for(const fault of ['quota','corrupt']){const c=await browser.newContext(),p=await c.newPage();if(fault==='quota')await c.addInitScript(()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith('family-games/oddity-puzzles/'))throw new DOMException('Quota','QuotaExceededError');return set.call(this,k,v);};});else await c.addInitScript(()=>{localStorage.setItem('family-games/oddity-puzzles/v1','{"version":1,"levels":null}');});await p.goto(origin+'/?play=oddity-puzzles');await p.locator('[data-ready=true]').waitFor();await p.locator('[data-cmd=skipDemo]').click();await p.locator('[data-cmd=skipDemo]').click();assert.match(await p.locator('.odd-save').textContent(),fault==='quota'?/没有保存成功/:/无法读取/);rows.push({check:'isolated '+fault+' feedback',result:'PASS'});await c.close();}
}finally{await browser.close();await writeFile(out+'/lifecycle-results.json',JSON.stringify({rows},null,2)+'\n');}
