import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {mkdir,writeFile,readFile} from 'node:fs/promises';
const out=process.env.ODDITY_OUTPUT||'tmp/tasks/oddity-v020/lifecycle',origin=process.env.ODDITY_ORIGIN||'http://127.0.0.1:5180';await mkdir(out,{recursive:true});const rows=[];
const browser=await chromium.launch({channel:'chrome',headless:false});
try{
 const c=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true}),p=await c.newPage();const focus=await c.newCDPSession(p);await focus.send('Emulation.setFocusEmulationEnabled',{enabled:false});p.setDefaultTimeout(10000);const errors=[];p.on('pageerror',e=>errors.push(String(e)));
 await c.addInitScript(()=>{window.oddityAnalysers=[];const connect=AudioNode.prototype.connect;AudioNode.prototype.connect=function(target,...args){const result=connect.call(this,target,...args);if(target instanceof AudioDestinationNode){const a=this.context.createAnalyser();a.fftSize=1024;connect.call(this,a);window.oddityAnalysers.push(a);}return result;};});
 const cmd=id=>p.locator(`[data-cmd="${id}"]`),mark=id=>p.locator(`[data-landmark="${id}"]`),act=label=>p.locator('.odd-commands').getByRole('button',{name:label,exact:true});const state=async()=>JSON.parse(await p.locator('.oddity-mount').getAttribute('data-state'));const still=async()=>{await p.waitForFunction(()=>document.querySelector('.oddity-mount').dataset.intent!=='running',null,{timeout:30000});await p.locator('[data-motion=still]').waitFor();};
 await p.goto(origin+'/');await p.locator('[data-world-oddity-link]').click();await p.locator('[data-ready=true]').waitFor();while(await cmd('skipDemo').isVisible())await cmd('skipDemo').click();
 // Real pointer down + Escape cancels that very release, rather than moving under it.
 const target=await mark('node:window').boundingBox();await p.mouse.move(target.x+target.width/2,target.y+target.height/2);await p.mouse.down();await p.keyboard.press('Escape');await p.mouse.up();await still();assert.equal((await state()).actors[0].node,'exit');
 await mark('node:window').tap();await p.locator('[data-motion=moving]').waitFor();await p.keyboard.press('z');await still();assert.equal((await state()).actors[0].node,'exit');rows.push({check:'touch movement, keyboard undo, canceled pointer does not fall through',result:'PASS'});
 // Route preview is observation only. Coordinates come from rendered landmark anchors, not layout.json.
 const original=await state();await mark('node:window').hover();assert.deepEqual(await state(),original);assert.match(await p.locator('.odd-preview').textContent(),/人物脚印/);await p.locator('.odd-stage-wrap').screenshot({path:out+'/route-before.png'});
 await mark('node:window').click();await still();const lamp=await mark('item:lamp').evaluate(b=>{const r=b.closest('.odd-stage').getBoundingClientRect();return {x:r.x+Number(b.dataset.anchorX),y:r.y+Number(b.dataset.anchorY)};});await p.mouse.click(lamp.x,lamp.y);assert.equal(await p.locator('.oddity-mount').getAttribute('data-intent'),'lamp-wall');await mark('wall:1').click();await still();
 await mark('node:lamp').click();await still();await mark('item:lamp').click();assert(await act('调查员：用扳指转灯').isVisible());assert(await act('调查员：用手转灯').isVisible());const toolState=await state();await act('调查员：用手转灯').click();assert.match(await p.locator('.odd-intent').textContent(),/用手/);await p.keyboard.press('Escape');assert.deepEqual(await state(),toolState);await cmd('undo').click();await still();
 await mark('item:box').click();await act('调查员：走近并拿起档案盒').hover();await p.locator('.odd-stage-wrap').screenshot({path:out+'/interaction-before.png'});const before=await state(),history=await p.locator('.oddity-mount').getAttribute('data-history');await act('调查员：走近并拿起档案盒').click();await p.locator('[data-motion=moving]').waitFor();await p.keyboard.press('Escape');await still();assert.deepEqual(await state(),before);assert.equal(await p.locator('.oddity-mount').getAttribute('data-history'),history);
 // An actual second tab causes blur; resume never completes the canceled take callback.
 await mark('item:box').click();await act('调查员：走近并拿起档案盒').click();await p.locator('[data-motion=moving]').waitFor();const other=await c.newPage();await other.goto('about:blank');await other.bringToFront();await cmd('resume').waitFor({state:'visible'});await p.bringToFront();await cmd('resume').click();await still();assert.deepEqual(await state(),before);assert.equal((await state()).items.find(i=>i.id==='box').holder,null);await other.close();rows.push({check:'real model click, route/interaction previews, composite Escape and real-tab blur rollback',result:'PASS'});
 await mark('item:box').click();await act('调查员：走近并拿起档案盒').click();await p.locator('[data-motion=moving]').waitFor();await cmd('reset').click();await cmd('confirmReset').click();await still();await p.waitForTimeout(800);assert.equal((await state()).lamp,0);assert.equal((await state()).items.find(i=>i.id==='box').holder,null);assert.equal(await p.locator('.oddity-mount').getAttribute('data-history'),'0');
 // Frame/label geometry and true hit areas under all three camera presets.
 const geometry=[];
 for(const [width,height]of [[390,844],[768,1024],[1024,768],[1024,1366],[1366,1024],[1440,1000]]){
  await p.setViewportSize({width,height});for(let view=0;view<3;view++){await cmd('view'+view).click();await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
   const bs=await p.locator('.odd-landmark').evaluateAll(bs=>bs.map(b=>{const r=b.getBoundingClientRect(),stage=b.closest('.odd-stage').getBoundingClientRect();return {id:b.dataset.landmark,x:r.x-stage.x,y:r.y-stage.y,w:r.width,h:r.height,sw:stage.width,sh:stage.height,anchor:[+b.dataset.anchorX,+b.dataset.anchorY]};}));
   for(let i=0;i<bs.length;i++){const a=bs[i];assert(a.h>=48&&a.w>=44);assert(a.anchor[0]>=0&&a.anchor[0]<=a.sw&&a.anchor[1]>=0&&a.anchor[1]<=a.sh,'anchor out of view');for(let j=i+1;j<bs.length;j++){const b=bs[j];assert(!(a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y),'overlap');}}
   for(const b of await p.locator('.odd-landmark').all()){await b.scrollIntoViewIfNeeded();const hits=await b.evaluate(e=>{const r=e.getBoundingClientRect();return [[.5,.5],[.25,.25],[.75,.75]].every(([x,y])=>e.contains(document.elementFromPoint(r.x+r.width*x,r.y+r.height*y)));});assert(hits,'label covered');}
   geometry.push({width,height,view,labels:bs});if(width===390||width===1440)await p.locator('.odd-stage-wrap').screenshot({path:`${out}/anchors-${width}-view${view}.png`});
  }
 }
 rows.push({check:'reset during composite animation and all-view anchor / 3-point hit geometry',result:'PASS',geometry});await p.setViewportSize({width:1440,height:1000});await cmd('view0').click();
 // Actual PCM, not just toggled button text.
 const amp=async()=>p.evaluate(()=>Math.max(0,...window.oddityAnalysers.map(a=>{const f=new Float32Array(a.fftSize);a.getFloatTimeDomainData(f);return Math.sqrt(f.reduce((s,v)=>s+v*v,0)/f.length);})));await p.locator('[data-top=sound]').click();await p.waitForFunction(()=>window.oddityAnalysers.some(a=>{const f=new Float32Array(a.fftSize);a.getFloatTimeDomainData(f);return f.some(v=>Math.abs(v)>.00001);}));const audible=await amp();await cmd('toggleMusic').click();await cmd('toggleSfx').click();await cmd('close').click();await p.waitForTimeout(200);const silent=await amp();assert(silent<.00001);await p.locator('[data-top=sound]').click();await cmd('toggleSfx').click();await cmd('close').click();await mark('node:window').click();await p.waitForTimeout(70);const effect=await amp();assert(effect>.00001);await p.keyboard.press('Escape');await p.waitForTimeout(150);assert((await amp())<.00001);rows.push({check:'music and effects produce local PCM, cancel stops old audio',result:'PASS',audible,silent,effect});
 assert.deepEqual(errors,[]);await c.close();
 for(const fault of ['quota','corrupt']){const c=await browser.newContext(),p=await c.newPage();if(fault==='quota')await c.addInitScript(()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith('family-games/oddity-puzzles/'))throw new DOMException('Quota','QuotaExceededError');return set.call(this,k,v);};});else await c.addInitScript(()=>localStorage.setItem('family-games/oddity-puzzles/v1','{"version":1,"levels":null}'));await p.goto(origin+'/?play=oddity-puzzles');await p.locator('[data-ready=true]').waitFor();while(await p.locator('[data-cmd=skipDemo]').isVisible())await p.locator('[data-cmd=skipDemo]').click();assert.match(await p.locator('.odd-save').textContent(),fault==='quota'?/没有保存成功/:/无法读取/);rows.push({check:'isolated '+fault+' failure feedback',result:'PASS'});await c.close();}
 // Actual v0.1 save captured by playing the preserved package; importing is compatibility evidence only.
 const old=await browser.newContext(),oldPage=await old.newPage();await oldPage.goto('http://127.0.0.1:5177/?play=oddity-puzzles');await oldPage.locator('[data-ready=true]').waitFor();while(await oldPage.locator('[data-cmd=skipDemo]').isVisible())await oldPage.locator('[data-cmd=skipDemo]').click();await oldPage.locator('.odd-commands').getByRole('button',{name:'观察窗前',exact:true}).click();await oldPage.locator('[data-motion=still]').waitFor();const raw=await oldPage.evaluate(()=>localStorage.getItem('family-games/oddity-puzzles/v1'));await old.close();assert(raw);const compat=await browser.newContext();await compat.addInitScript(raw=>localStorage.setItem('family-games/oddity-puzzles/v1',raw),raw);const imported=await compat.newPage();await imported.goto(origin+'/?play=oddity-puzzles');await imported.locator('[data-ready=true]').waitFor();assert.equal(JSON.parse(await imported.locator('.oddity-mount').getAttribute('data-state')).actors[0].node,'window');assert.equal(await imported.evaluate(()=>localStorage.getItem('family-games/oddity-puzzles/v1')),raw);rows.push({check:'actual v0.1 serialized progress loads unchanged in v0.2',result:'PASS',boundary:'isolated storage compatibility fixture, not playthrough advancement'});await writeFile(out+'/v010-save.json',raw);await compat.close();
} catch(e){rows.push({check:'failure',result:'FAIL',error:String(e)});throw e;}finally{await browser.close();await writeFile(out+'/lifecycle-results.json',JSON.stringify({rows},null,2));}
