import type { EnglishWordRecord, GraphemeUnit } from "./types";

type UnitSpec = readonly [letters: string, phonemes: readonly string[], role?: GraphemeUnit["role"], childHint?: string];
type WordSpec = Omit<EnglishWordRecord, "id" | "displayWord" | "imageAssetId" | "pronunciationLocale" | "phonemeCount" | "graphemeUnits" | "stressPattern" | "sourceIds" | "revisionHash" | "distractorUnits"> & {
  readonly units: readonly UnitSpec[];
};

const SHARED_SOURCES = ["cmudict-7479086", "oewn-2025", "wordlight-project-authored-v2"] as const;
const DISTRACTOR_POOL = ["m", "p", "s", "t", "n", "b", "ch", "ck"] as const;

function revisionHash(value: unknown): string {
  let hash = 2166136261;
  for (const character of JSON.stringify(value)) {
    hash ^= character.codePointAt(0) ?? 0;
    hash = Math.imul(hash, 16777619);
  }
  return `fnv1a-${(hash >>> 0).toString(16).padStart(8, "0")}`;
}

function word(spec: WordSpec): EnglishWordRecord {
  const used = new Set(spec.units.map(([letters]) => letters));
  const distractorUnits = DISTRACTOR_POOL.filter((letters) => !used.has(letters)).slice(0, 2);
  const graphemeUnits = spec.units.map(([letters, phonemeIds, role = "regular", childHint], index) => ({
    id: `${spec.lemma}-${index + 1}`,
    letters,
    phonemeIds,
    role,
    ...(childHint ? { childHint } : {}),
  }));
  const base = {
    ...spec,
    id: `word-${spec.lemma}`,
    displayWord: spec.lemma,
    imageAssetId: spec.visualKind === "asset" ? `word-${spec.lemma}` : null,
    pronunciationLocale: "en-US" as const,
    phonemeCount: spec.arpabet.length,
    graphemeUnits,
    stressPattern: spec.arpabet.flatMap((phoneme) => phoneme.match(/[012]$/)?.map(Number) ?? []),
    sourceIds: SHARED_SOURCES,
    distractorUnits,
  };
  return { ...base, revisionHash: revisionHash(base) };
}

export const ENGLISH_V2_WORDS: readonly EnglishWordRecord[] = [
  word({ lemma: "cat", senseId: "oewn:02124272-n", partOfSpeech: "noun", themeId: "animals", childGlossZh: "猫", childDefinitionEn: "A small animal that can live with people.", imageBrief: "One friendly domestic ginger-and-cream cat sitting, full body.", visualKind: "asset", arpabet: ["K", "AE1", "T"], units: [["c", ["K"]], ["a", ["AE1"]], ["t", ["T"]]], decodingBand: "simple-regular", storyBand: "story-core", sentenceIds: ["sentence-cat-home"], riskFlags: [] }),
  word({ lemma: "dog", senseId: "oewn:02086723-n", partOfSpeech: "noun", themeId: "animals", childGlossZh: "狗", childDefinitionEn: "A tame animal that often lives with people.", imageBrief: "One friendly tan-and-cream domestic dog standing, full body.", visualKind: "asset", arpabet: ["D", "AO1", "G"], units: [["d", ["D"]], ["o", ["AO1"]], ["g", ["G"]]], decodingBand: "simple-regular", storyBand: "story-core", sentenceIds: ["sentence-dog-dig"], riskFlags: [] }),
  word({ lemma: "fish", senseId: "oewn:02514684-n", partOfSpeech: "noun", themeId: "animals", childGlossZh: "鱼", childDefinitionEn: "An animal that lives and swims in water.", imageBrief: "One living blue-green fish in side view.", visualKind: "asset", arpabet: ["F", "IH1", "SH"], units: [["f", ["F"]], ["i", ["IH1"]], ["sh", ["SH"], "common-pattern", "Keep s and h together: sh."]], decodingBand: "common-pattern", storyBand: "story-core", sentenceIds: ["sentence-fish-swim"], riskFlags: [] }),
  word({ lemma: "duck", senseId: "oewn:01848972-n", partOfSpeech: "noun", themeId: "animals", childGlossZh: "鸭子", childDefinitionEn: "A swimming bird with a broad bill and webbed feet.", imageBrief: "One yellow-brown duck standing beside a small water ripple.", visualKind: "asset", arpabet: ["D", "AH1", "K"], units: [["d", ["D"]], ["u", ["AH1"]], ["ck", ["K"], "common-pattern", "Keep c and k together at the end."]], decodingBand: "common-pattern", storyBand: "story-core", sentenceIds: ["sentence-duck-splash"], riskFlags: [] }),
  word({ lemma: "frog", senseId: "oewn:01642406-n", partOfSpeech: "noun", themeId: "animals", childGlossZh: "青蛙", childDefinitionEn: "A small animal with long back legs for jumping.", imageBrief: "One bright green frog in a natural crouch, full body.", visualKind: "asset", arpabet: ["F", "R", "AA1", "G"], units: [["f", ["F"]], ["r", ["R"]], ["o", ["AA1"]], ["g", ["G"]]], decodingBand: "simple-regular", storyBand: "story-core", sentenceIds: ["sentence-frog-hop"], riskFlags: [] }),
  word({ lemma: "bee", senseId: "oewn:02209508-n", partOfSpeech: "noun", themeId: "animals", childGlossZh: "蜜蜂", childDefinitionEn: "A flying insect that gathers nectar from flowers.", imageBrief: "One anatomically readable honeybee hovering in side view.", visualKind: "asset", arpabet: ["B", "IY1"], units: [["b", ["B"]], ["ee", ["IY1"], "common-pattern", "Two e letters share one long sound."]], decodingBand: "common-pattern", storyBand: "story-core", sentenceIds: ["sentence-bee-flower"], riskFlags: [] }),

  word({ lemma: "pig", senseId: "oewn:02398058-n", partOfSpeech: "noun", themeId: "animals", childGlossZh: "猪", childDefinitionEn: "A domestic animal with a snout.", imageBrief: "One cheerful pink domestic pig standing, full body.", visualKind: "asset", arpabet: ["P", "IH1", "G"], units: [["p", ["P"]], ["i", ["IH1"]], ["g", ["G"]]], decodingBand: "simple-regular", storyBand: "optional", sentenceIds: [], riskFlags: [] }),
  word({ lemma: "cow", senseId: "oewn:02406106-n", partOfSpeech: "noun", themeId: "animals", childGlossZh: "母牛", childDefinitionEn: "An adult female animal of domestic cattle.", imageBrief: "One gentle black-and-white dairy cow standing, full body.", visualKind: "asset", arpabet: ["K", "AW1"], units: [["c", ["K"]], ["ow", ["AW1"], "common-pattern", "Keep o and w together: ow."]], decodingBand: "common-pattern", storyBand: "optional", sentenceIds: [], riskFlags: [] }),
  word({ lemma: "bear", senseId: "oewn:02134305-n", partOfSpeech: "noun", themeId: "animals", childGlossZh: "熊", childDefinitionEn: "A large furry animal with strong claws.", imageBrief: "One gentle brown bear standing on all fours.", visualKind: "asset", arpabet: ["B", "EH1", "R"], units: [["b", ["B"]], ["ear", ["EH1", "R"], "irregular-heart", "The letters ear make the sound heard in bear."]], decodingBand: "irregular-supported", storyBand: "optional", sentenceIds: [], riskFlags: ["IRREGULAR_ORTHOGRAPHY"] }),
  word({ lemma: "rabbit", senseId: "oewn:02326697-n", partOfSpeech: "noun", themeId: "animals", childGlossZh: "兔子", childDefinitionEn: "A small animal with long ears and a short tail.", imageBrief: "One small cream-and-brown rabbit sitting, full body.", visualKind: "asset", arpabet: ["R", "AE1", "B", "AH0", "T"], units: [["r", ["R"]], ["a", ["AE1"]], ["bb", ["B"], "common-pattern"], ["i", ["AH0"], "common-pattern"], ["t", ["T"]]], decodingBand: "optional-advanced", storyBand: "optional", sentenceIds: [], riskFlags: ["MULTISYLLABLE_OPTIONAL"] }),
  word({ lemma: "tiger", senseId: "oewn:02132256-n", partOfSpeech: "noun", themeId: "animals", childGlossZh: "老虎", childDefinitionEn: "A large striped wild cat from Asia.", imageBrief: "One orange tiger standing, full body, black stripes clear.", visualKind: "asset", arpabet: ["T", "AY1", "G", "ER0"], units: [["t", ["T"]], ["i", ["AY1"], "common-pattern"], ["g", ["G"]], ["er", ["ER0"], "common-pattern"]], decodingBand: "optional-advanced", storyBand: "optional", sentenceIds: [], riskFlags: ["MULTISYLLABLE_OPTIONAL"] }),
  word({ lemma: "horse", senseId: "oewn:02377103-n", partOfSpeech: "noun", themeId: "animals", childGlossZh: "马", childDefinitionEn: "A large animal people can ride.", imageBrief: "One gentle chestnut horse standing, full body.", visualKind: "asset", arpabet: ["HH", "AO1", "R", "S"], units: [["h", ["HH"]], ["or", ["AO1", "R"], "common-pattern"], ["s", ["S"]], ["e", [], "common-pattern", "The final e is quiet."]], decodingBand: "common-pattern", storyBand: "optional", sentenceIds: [], riskFlags: ["SILENT_E_PATTERN"] }),
  word({ lemma: "goat", senseId: "oewn:02419165-n", partOfSpeech: "noun", themeId: "animals", childGlossZh: "山羊", childDefinitionEn: "An agile animal related to sheep, often with horns.", imageBrief: "One cream-and-brown domestic goat standing, full body.", visualKind: "asset", arpabet: ["G", "OW1", "T"], units: [["g", ["G"]], ["oa", ["OW1"], "common-pattern", "Keep o and a together: oa."], ["t", ["T"]]], decodingBand: "common-pattern", storyBand: "optional", sentenceIds: [], riskFlags: ["NEW_SELECTED_OA_PATTERN"] }),

  word({ lemma: "dad", senseId: "oewn:10007601-n", partOfSpeech: "noun", themeId: "home", childGlossZh: "爸爸", childDefinitionEn: "A familiar word for a father.", imageBrief: "One fictional adult father figure kneeling in a welcoming pose.", visualKind: "asset", arpabet: ["D", "AE1", "D"], units: [["d", ["D"]], ["a", ["AE1"]], ["d", ["D"]]], decodingBand: "simple-regular", storyBand: "story-core", sentenceIds: ["sentence-dad-door"], riskFlags: ["FICTIONAL_INCLUSIVE_ART"] }),
  word({ lemma: "mom", senseId: "oewn:10297825-n", partOfSpeech: "noun", themeId: "home", childGlossZh: "妈妈", childDefinitionEn: "A familiar word for a mother.", imageBrief: "One fictional adult mother figure standing in a welcoming pose.", visualKind: "asset", arpabet: ["M", "AA1", "M"], units: [["m", ["M"]], ["o", ["AA1"]], ["m", ["M"]]], decodingBand: "simple-regular", storyBand: "story-core", sentenceIds: ["sentence-mom-hello"], riskFlags: ["FICTIONAL_INCLUSIVE_ART"] }),
  word({ lemma: "baby", senseId: "oewn:09846929-n", partOfSpeech: "noun", themeId: "home", childGlossZh: "婴儿", childDefinitionEn: "A very young child who cannot yet walk.", imageBrief: "One awake fictional baby sitting safely on a plain mat.", visualKind: "asset", arpabet: ["B", "EY1", "B", "IY0"], units: [["b", ["B"]], ["a", ["EY1"], "common-pattern"], ["b", ["B"]], ["y", ["IY0"], "common-pattern"]], decodingBand: "common-pattern", storyBand: "story-core", sentenceIds: ["sentence-baby-cozy"], riskFlags: ["FICTIONAL_INCLUSIVE_ART"] }),
  word({ lemma: "boy", senseId: "oewn:10305010-n", partOfSpeech: "noun", themeId: "home", childGlossZh: "男孩", childDefinitionEn: "A young male child.", imageBrief: "One fictional young boy standing and waving hello.", visualKind: "asset", arpabet: ["B", "OY1"], units: [["b", ["B"]], ["oy", ["OY1"], "common-pattern", "Keep o and y together: oy."]], decodingBand: "common-pattern", storyBand: "story-core", sentenceIds: ["sentence-boy-waves"], riskFlags: ["FICTIONAL_INCLUSIVE_ART"] }),
  word({ lemma: "girl", senseId: "oewn:10104064-n", partOfSpeech: "noun", themeId: "home", childGlossZh: "女孩", childDefinitionEn: "A young female child.", imageBrief: "One fictional young girl standing, full body.", visualKind: "asset", arpabet: ["G", "ER1", "L"], units: [["g", ["G"]], ["ir", ["ER1"], "common-pattern", "Keep i and r together: ir."], ["l", ["L"]]], decodingBand: "common-pattern", storyBand: "story-core", sentenceIds: ["sentence-girl-kite"], riskFlags: ["FICTIONAL_INCLUSIVE_ART"] }),
  word({ lemma: "friend", senseId: "oewn:10132360-n", partOfSpeech: "noun", themeId: "home", childGlossZh: "朋友", childDefinitionEn: "A person you know well, like, and trust.", imageBrief: "Two fictional young friends sharing an equal high-five.", visualKind: "asset", arpabet: ["F", "R", "EH1", "N", "D"], units: [["f", ["F"]], ["r", ["R"]], ["ie", ["EH1"], "irregular-heart", "The letters ie make the short e sound here."], ["n", ["N"]], ["d", ["D"]]], decodingBand: "irregular-supported", storyBand: "story-core", sentenceIds: ["sentence-friend-here"], riskFlags: ["IRREGULAR_ORTHOGRAPHY", "FICTIONAL_INCLUSIVE_ART"] }),

  word({ lemma: "teacher", senseId: "oewn:10713754-n", partOfSpeech: "noun", themeId: "home", childGlossZh: "老师", childDefinitionEn: "A person whose work is teaching.", imageBrief: "One fictional adult teacher beside a blank portable board.", visualKind: "asset", arpabet: ["T", "IY1", "CH", "ER0"], units: [["t", ["T"]], ["ea", ["IY1"], "common-pattern"], ["ch", ["CH"], "common-pattern"], ["er", ["ER0"], "common-pattern"]], decodingBand: "optional-advanced", storyBand: "optional", sentenceIds: [], riskFlags: ["MULTISYLLABLE_OPTIONAL", "FICTIONAL_INCLUSIVE_ART"] }),
  word({ lemma: "family", senseId: "oewn:07986853-n", partOfSpeech: "noun", themeId: "home", childGlossZh: "家庭；家人", childDefinitionEn: "Parents or caregivers and children as a group.", imageBrief: "One fictional inclusive family group of caregivers and children.", visualKind: "asset", arpabet: ["F", "AE1", "M", "AH0", "L", "IY0"], units: [["f", ["F"]], ["a", ["AE1"]], ["m", ["M"]], ["i", ["AH0"], "common-pattern"], ["l", ["L"]], ["y", ["IY0"], "common-pattern"]], decodingBand: "optional-advanced", storyBand: "optional", sentenceIds: [], riskFlags: ["MULTISYLLABLE_OPTIONAL", "FICTIONAL_INCLUSIVE_ART"] }),
  word({ lemma: "book", senseId: "oewn:02873453-n", partOfSpeech: "noun", themeId: "home", childGlossZh: "书", childDefinitionEn: "Bound pages that you can read or look through.", imageBrief: "One plain teal bound storybook with no writing.", visualKind: "asset", arpabet: ["B", "UH1", "K"], units: [["b", ["B"]], ["oo", ["UH1"], "common-pattern", "The letters oo share one sound in book."], ["k", ["K"]]], decodingBand: "common-pattern", storyBand: "optional", sentenceIds: [], riskFlags: ["NEW_SELECTED_OO_PATTERN"] }),

  word({ lemma: "apple", senseId: "oewn:07755101-n", partOfSpeech: "noun", themeId: "food", childGlossZh: "苹果", childDefinitionEn: "A round fruit with crisp flesh and thin skin.", imageBrief: "One fresh red-and-green whole apple with a leaf.", visualKind: "asset", arpabet: ["AE1", "P", "AH0", "L"], units: [["a", ["AE1"]], ["pp", ["P"], "common-pattern"], ["le", ["AH0", "L"], "common-pattern"]], decodingBand: "common-pattern", storyBand: "story-core", sentenceIds: ["sentence-apple-rolls"], riskFlags: [] }),
  word({ lemma: "egg", senseId: "oewn:07856780-n", partOfSpeech: "noun", themeId: "food", childGlossZh: "鸡蛋", childDefinitionEn: "An oval food laid by a hen.", imageBrief: "One plain brown hen egg resting in a teal egg cup.", visualKind: "asset", arpabet: ["EH1", "G"], units: [["e", ["EH1"]], ["gg", ["G"], "common-pattern"]], decodingBand: "simple-regular", storyBand: "story-core", sentenceIds: ["sentence-egg-warm"], riskFlags: [] }),
  word({ lemma: "milk", senseId: "oewn:07860018-n", partOfSpeech: "noun", themeId: "food", childGlossZh: "牛奶", childDefinitionEn: "A white drink that comes from mammals.", imageBrief: "Opaque white milk poured into one clear glass.", visualKind: "asset", arpabet: ["M", "IH1", "L", "K"], units: [["m", ["M"]], ["i", ["IH1"]], ["l", ["L"]], ["k", ["K"]]], decodingBand: "simple-regular", storyBand: "story-core", sentenceIds: ["sentence-milk-cup"], riskFlags: [] }),
  word({ lemma: "cake", senseId: "oewn:07644479-n", partOfSpeech: "noun", themeId: "food", childGlossZh: "蛋糕", childDefinitionEn: "A sweet baked food made with flour and eggs.", imageBrief: "One small round frosted sponge cake on one plate.", visualKind: "asset", arpabet: ["K", "EY1", "K"], units: [["c", ["K"]], ["a", ["EY1"], "common-pattern", "The quiet e helps a say its name."], ["k", ["K"]], ["e", [], "common-pattern", "This e is quiet, but it helps a."]], decodingBand: "common-pattern", storyBand: "story-core", sentenceIds: ["sentence-cake-ready"], riskFlags: ["SILENT_E_PATTERN"] }),
  word({ lemma: "water", senseId: "oewn:14869913-n", partOfSpeech: "noun", themeId: "food", childGlossZh: "水", childDefinitionEn: "A clear liquid that people, animals, and plants need.", imageBrief: "One clear tumbler filled with transparent water.", visualKind: "asset", arpabet: ["W", "AO1", "T", "ER0"], units: [["w", ["W"]], ["a", ["AO1"], "irregular-heart", "The a has the broad sound heard in water."], ["t", ["T"]], ["er", ["ER0"], "common-pattern"]], decodingBand: "irregular-supported", storyBand: "story-core", sentenceIds: ["sentence-water-pond"], riskFlags: ["IRREGULAR_ORTHOGRAPHY"] }),
  word({ lemma: "bread", senseId: "oewn:07695101-n", partOfSpeech: "noun", themeId: "food", childGlossZh: "面包", childDefinitionEn: "Baked food made from flour and water.", imageBrief: "One small golden-brown loaf of baked bread.", visualKind: "asset", arpabet: ["B", "R", "EH1", "D"], units: [["b", ["B"]], ["r", ["R"]], ["ea", ["EH1"], "irregular-heart", "The letters ea make the short e sound here."], ["d", ["D"]]], decodingBand: "irregular-supported", storyBand: "story-core", sentenceIds: ["sentence-bread-good"], riskFlags: ["IRREGULAR_ORTHOGRAPHY"] }),

  word({ lemma: "banana", senseId: "oewn:07769568-n", partOfSpeech: "noun", themeId: "food", childGlossZh: "香蕉", childDefinitionEn: "A long curved fruit with soft sweet flesh.", imageBrief: "One ripe yellow unpeeled banana.", visualKind: "asset", arpabet: ["B", "AH0", "N", "AE1", "N", "AH0"], units: [["b", ["B"]], ["a", ["AH0"], "common-pattern"], ["n", ["N"]], ["a", ["AE1"]], ["n", ["N"]], ["a", ["AH0"], "common-pattern"]], decodingBand: "optional-advanced", storyBand: "optional", sentenceIds: [], riskFlags: ["MULTISYLLABLE_OPTIONAL"] }),
  word({ lemma: "rice", senseId: "oewn:07820299-n", partOfSpeech: "noun", themeId: "food", childGlossZh: "米饭；米", childDefinitionEn: "Small grains cooked or used as food.", imageBrief: "One small teal bowl filled with plain cooked white rice.", visualKind: "asset", arpabet: ["R", "AY1", "S"], units: [["r", ["R"]], ["i", ["AY1"], "common-pattern", "The quiet e helps i say its name."], ["c", ["S"], "common-pattern"], ["e", [], "common-pattern", "The final e is quiet."]], decodingBand: "common-pattern", storyBand: "optional", sentenceIds: [], riskFlags: ["SILENT_E_PATTERN"] }),
  word({ lemma: "corn", senseId: "oewn:07747928-n", partOfSpeech: "noun", themeId: "food", childGlossZh: "玉米", childDefinitionEn: "Yellow kernels on an ear that people can eat.", imageBrief: "One fresh ear of yellow corn with its green husk opened.", visualKind: "asset", arpabet: ["K", "AO1", "R", "N"], units: [["c", ["K"]], ["or", ["AO1", "R"], "common-pattern", "Keep o and r together: or."], ["n", ["N"]]], decodingBand: "common-pattern", storyBand: "optional", sentenceIds: [], riskFlags: ["NEW_SELECTED_OR_PATTERN"] }),

  word({ lemma: "run", senseId: "oewn:01930264-v", partOfSpeech: "verb", themeId: "actions", childGlossZh: "跑", childDefinitionEn: "To move quickly on your feet.", imageBrief: "One fictional child running in clear side view.", visualKind: "asset", arpabet: ["R", "AH1", "N"], units: [["r", ["R"]], ["u", ["AH1"]], ["n", ["N"]]], decodingBand: "simple-regular", storyBand: "story-core", sentenceIds: ["sentence-run-can"], riskFlags: ["ACTION_IMAGE_REVIEWED", "FICTIONAL_INCLUSIVE_ART"] }),
  word({ lemma: "jump", senseId: "oewn:01967949-v", partOfSpeech: "verb", themeId: "actions", childGlossZh: "跳", childDefinitionEn: "To push off the ground with your feet.", imageBrief: "One fictional child jumping with both feet off the ground.", visualKind: "asset", arpabet: ["JH", "AH1", "M", "P"], units: [["j", ["JH"]], ["u", ["AH1"]], ["m", ["M"]], ["p", ["P"]]], decodingBand: "simple-regular", storyBand: "story-core", sentenceIds: ["sentence-jump-can"], riskFlags: ["ACTION_IMAGE_REVIEWED", "FICTIONAL_INCLUSIVE_ART"] }),
  word({ lemma: "sit", senseId: "oewn:01545905-v", partOfSpeech: "verb", themeId: "actions", childGlossZh: "坐", childDefinitionEn: "To rest with your body supported from below.", imageBrief: "One fictional child sitting upright on a plain low stool.", visualKind: "asset", arpabet: ["S", "IH1", "T"], units: [["s", ["S"]], ["i", ["IH1"]], ["t", ["T"]]], decodingBand: "simple-regular", storyBand: "story-core", sentenceIds: ["sentence-sit-can"], riskFlags: ["ACTION_IMAGE_REVIEWED", "FICTIONAL_INCLUSIVE_ART"] }),
  word({ lemma: "sleep", senseId: "oewn:00014735-v", partOfSpeech: "verb", themeId: "actions", childGlossZh: "睡觉", childDefinitionEn: "To rest with your eyes closed and mind quiet.", imageBrief: "One fictional child peacefully asleep on a plain floor mat.", visualKind: "asset", arpabet: ["S", "L", "IY1", "P"], units: [["s", ["S"]], ["l", ["L"]], ["ee", ["IY1"], "common-pattern"], ["p", ["P"]]], decodingBand: "common-pattern", storyBand: "story-core", sentenceIds: ["sentence-sleep-can"], riskFlags: ["ACTION_IMAGE_REVIEWED", "FICTIONAL_INCLUSIVE_ART"] }),
  word({ lemma: "eat", senseId: "oewn:01170802-v", partOfSpeech: "verb", themeId: "actions", childGlossZh: "吃", childDefinitionEn: "To take solid food into your body.", imageBrief: "One fictional child clearly eating one apple slice.", visualKind: "asset", arpabet: ["IY1", "T"], units: [["ea", ["IY1"], "common-pattern"], ["t", ["T"]]], decodingBand: "common-pattern", storyBand: "story-core", sentenceIds: ["sentence-eat-can"], riskFlags: ["ACTION_IMAGE_REVIEWED", "FICTIONAL_INCLUSIVE_ART"] }),
  word({ lemma: "sing", senseId: "oewn:01733312-v", partOfSpeech: "verb", themeId: "actions", childGlossZh: "唱歌", childDefinitionEn: "To make musical sounds with your voice.", imageBrief: "One fictional child singing with an open vowel mouth shape.", visualKind: "asset", arpabet: ["S", "IH1", "NG"], units: [["s", ["S"]], ["i", ["IH1"]], ["ng", ["NG"], "common-pattern"]], decodingBand: "common-pattern", storyBand: "story-core", sentenceIds: ["sentence-sing-can"], riskFlags: ["ACTION_IMAGE_REVIEWED", "FICTIONAL_INCLUSIVE_ART"] }),

  word({ lemma: "walk", senseId: "oewn:01908923-v", partOfSpeech: "verb", themeId: "actions", childGlossZh: "走路", childDefinitionEn: "To move forward on your feet by steps.", imageBrief: "One fictional child walking in clear side view.", visualKind: "asset", arpabet: ["W", "AO1", "K"], units: [["w", ["W"]], ["al", ["AO1"], "irregular-heart", "The l is quiet in walk."], ["k", ["K"]]], decodingBand: "irregular-supported", storyBand: "optional", sentenceIds: [], riskFlags: ["IRREGULAR_ORTHOGRAPHY", "ACTION_IMAGE_REVIEWED", "FICTIONAL_INCLUSIVE_ART"] }),
  word({ lemma: "drink", senseId: "oewn:01172332-v", partOfSpeech: "verb", themeId: "actions", childGlossZh: "喝", childDefinitionEn: "To take liquid into your mouth.", imageBrief: "One fictional child drinking water from a clear cup.", visualKind: "asset", arpabet: ["D", "R", "IH1", "NG", "K"], units: [["d", ["D"]], ["r", ["R"]], ["i", ["IH1"]], ["n", ["NG"], "common-pattern", "Before k, n carries the ng sound."], ["k", ["K"]]], decodingBand: "common-pattern", storyBand: "optional", sentenceIds: [], riskFlags: ["ACTION_IMAGE_REVIEWED", "FICTIONAL_INCLUSIVE_ART"] }),
  word({ lemma: "clap", senseId: "oewn:00034108-v", partOfSpeech: "verb", themeId: "actions", childGlossZh: "拍手", childDefinitionEn: "To strike your hands together.", imageBrief: "One fictional child clapping both hands together at chest height.", visualKind: "asset", arpabet: ["K", "L", "AE1", "P"], units: [["c", ["K"]], ["l", ["L"]], ["a", ["AE1"]], ["p", ["P"]]], decodingBand: "simple-regular", storyBand: "optional", sentenceIds: [], riskFlags: ["NEW_SELECTED_CONSONANT_CLUSTER", "ACTION_IMAGE_REVIEWED", "FICTIONAL_INCLUSIVE_ART"] }),

  word({ lemma: "red", senseId: "oewn:00382159-s", partOfSpeech: "adjective", themeId: "colors", childGlossZh: "红色的", childDefinitionEn: "Having the color of a ripe tomato.", imageBrief: "A verified CSS red color field, without a competing object.", visualKind: "color", arpabet: ["R", "EH1", "D"], units: [["r", ["R"]], ["e", ["EH1"]], ["d", ["D"]]], decodingBand: "simple-regular", storyBand: "story-core", sentenceIds: ["sentence-red-shell"], riskFlags: ["CSS_COLOR_VISUAL"] }),
  word({ lemma: "blue", senseId: "oewn:00371931-s", partOfSpeech: "adjective", themeId: "colors", childGlossZh: "蓝色的", childDefinitionEn: "Having the color of a clear daytime sky.", imageBrief: "A verified CSS blue color field, without a competing object.", visualKind: "color", arpabet: ["B", "L", "UW1"], units: [["b", ["B"]], ["l", ["L"]], ["ue", ["UW1"], "common-pattern"]], decodingBand: "common-pattern", storyBand: "story-core", sentenceIds: ["sentence-blue-boat"], riskFlags: ["CSS_COLOR_VISUAL"] }),
  word({ lemma: "green", senseId: "oewn:00377031-s", partOfSpeech: "adjective", themeId: "colors", childGlossZh: "绿色的", childDefinitionEn: "Having the color of fresh grass.", imageBrief: "A verified CSS green color field, without a competing object.", visualKind: "color", arpabet: ["G", "R", "IY1", "N"], units: [["g", ["G"]], ["r", ["R"]], ["ee", ["IY1"], "common-pattern"], ["n", ["N"]]], decodingBand: "common-pattern", storyBand: "story-core", sentenceIds: ["sentence-green-leaf"], riskFlags: ["CSS_COLOR_VISUAL"] }),
  word({ lemma: "yellow", senseId: "oewn:00386818-s", partOfSpeech: "adjective", themeId: "colors", childGlossZh: "黄色的", childDefinitionEn: "Having the color of an egg yolk.", imageBrief: "A verified CSS yellow color field, without a competing object.", visualKind: "color", arpabet: ["Y", "EH1", "L", "OW0"], units: [["y", ["Y"]], ["e", ["EH1"]], ["ll", ["L"], "common-pattern"], ["ow", ["OW0"], "common-pattern"]], decodingBand: "common-pattern", storyBand: "story-core", sentenceIds: ["sentence-yellow-sun"], riskFlags: ["CSS_COLOR_VISUAL", "MULTISYLLABLE_CORE"] }),
  word({ lemma: "one", senseId: "oewn:02193977-s", partOfSpeech: "number", themeId: "colors", childGlossZh: "一；一个", childDefinitionEn: "A single thing, not two or more.", imageBrief: "Exactly one DOM-rendered golden shell.", visualKind: "quantity", arpabet: ["W", "AH1", "N"], units: [["o", ["W", "AH1"], "irregular-heart", "This o carries the heart sound in one."], ["n", ["N"]], ["e", [], "irregular-heart", "The final e is quiet in one."]], decodingBand: "irregular-supported", storyBand: "story-core", sentenceIds: ["sentence-one-shell"], riskFlags: ["IRREGULAR_ORTHOGRAPHY", "DOM_QUANTITY_VISUAL"] }),
  word({ lemma: "two", senseId: "oewn:02194109-s", partOfSpeech: "number", themeId: "colors", childGlossZh: "二；两个", childDefinitionEn: "One more than one.", imageBrief: "Exactly two DOM-rendered golden shells.", visualKind: "quantity", arpabet: ["T", "UW1"], units: [["t", ["T"]], ["wo", ["UW1"], "irregular-heart", "The w is quiet; wo carries the long oo sound."]], decodingBand: "irregular-supported", storyBand: "story-core", sentenceIds: ["sentence-two-boats"], riskFlags: ["IRREGULAR_ORTHOGRAPHY", "DOM_QUANTITY_VISUAL"] }),

  word({ lemma: "three", senseId: "oewn:02194219-s", partOfSpeech: "number", themeId: "colors", childGlossZh: "三；三个", childDefinitionEn: "One more than two.", imageBrief: "Exactly three DOM-rendered golden shells.", visualKind: "quantity", arpabet: ["TH", "R", "IY1"], units: [["th", ["TH"], "common-pattern"], ["r", ["R"]], ["ee", ["IY1"], "common-pattern"]], decodingBand: "common-pattern", storyBand: "optional", sentenceIds: [], riskFlags: ["DOM_QUANTITY_VISUAL"] }),
  word({ lemma: "ten", senseId: "oewn:02194935-s", partOfSpeech: "number", themeId: "colors", childGlossZh: "十；十个", childDefinitionEn: "One more than nine.", imageBrief: "Exactly ten DOM-rendered golden shells.", visualKind: "quantity", arpabet: ["T", "EH1", "N"], units: [["t", ["T"]], ["e", ["EH1"]], ["n", ["N"]]], decodingBand: "simple-regular", storyBand: "optional", sentenceIds: [], riskFlags: ["DOM_QUANTITY_VISUAL"] }),
] as const;
